Repository openemr/openemr, pull requests merged in 2018-12, with the labels that each got.

#2004 Upgrade min php 7 1 1
  build.xml
  common/compatibility/Checker.php
  composer.json
  composer.lock
Labels: Status: Needs Review

#2007 Rest api capabilities upgrade
  _rest_config.php
  _rest_routes.inc.php
  apis/dispatch.php
  rest_controllers/AuthRestController.php
Labels: Status: Reviewed

#2021 Adding a review option to the about us page.
  interface/main/about_page.php
  public/images/review-logo.png
Labels: Status: Needs Review

#1999 Minor npm version bumps for dwv and moment
  package-lock.json
  package.json
Labels: Status: Needs Review

#2002 work in progress to consolidate HCFA 1500 into one class in namespace…
  interface/billing/billing_process.php
  library/billing/src/HCFA_1500.php
  library/billing/src/HCFA_Info.php
  library/billing/src/X12_5010_837P.php
  library/gen_hcfa_1500.inc.php
  library/gen_hcfa_1500_02_12.inc.php
Labels: Status: Needs Review, Status: Needs Work

#2046 using OemrUI class in Fees > Fee Sheet, Billing, Payment, Checkout, Batch Payments, Posting
  interface/billing/billing_report.php
  interface/billing/era_payments.php
  interface/billing/new_payment.php
  interface/billing/search_payments.php
  interface/forms/fee_sheet/new.php
  interface/patient_file/front_payment.php
  interface/patient_file/pos_checkout.php
  library/globals.inc.php
  library/js/oeUI/oeFileUploads.js
  library/oeUI/src/OemrUI.php
Labels: Status: Needs Review

#2034 pe form fixes
  interface/forms/physical_exam/lines.php
  interface/forms/physical_exam/new.php
  interface/forms/physical_exam/report.php
Labels: Status: Needs Review

#2050 Enable drowpdown tab in the patient menu
  library/menu/src/PatientMenuRole.php
Labels: Status: Needs Review, Status: Needs Work

#2045 class modernization of library/billing.inc
  contrib/forms/evaluation/C_FormEvaluation.class.php
  contrib/forms/prosthesis/C_FormProsthesis.class.php
  contrib/forms/review_of_systems/C_FormReviewOfSystems.class.php
  interface/billing/adjustment_reason_codes.php
  interface/billing/billing_process.php
  interface/billing/claim_status_codes.php
  interface/billing/print_billing_report.php
  interface/billing/remark_codes.php
  interface/billing/sl_eob_process.php
  interface/billing/ub04_dispose.php
  interface/forms/eye_mag/save.php
  interface/forms/fee_sheet/new.php
  interface/main/authorizations/authorizations.php
  interface/patient_file/deleter.php
  interface/patient_file/encounter/cash_receipt.php
  interface/patient_file/encounter/diagnosis.php
  interface/patient_file/encounter/diagnosis_full.php
  interface/patient_file/encounter/superbill_codes.php
  interface/patient_file/front_payment.php
  interface/patient_file/history/encounters.php
  interface/patient_file/pos_checkout.php
  interface/patient_file/printed_fee_sheet.php
  interface/patient_file/report/custom_report.php
  interface/reports/appt_encounter_report.php
  interface/reports/custom_report_range.php
  interface/reports/edi_270.php
  interface/reports/edi_271.php
  interface/reports/encounters_report.php
  library/FeeSheet.class.php
  library/api.inc
  library/billing.inc
  library/billing/src/BillingUtilities.php
  library/billing/src/HCFA_1500.php
  library/billing/src/X12_5010_837P.php
  library/sl_eob.inc.php
  myportal/soap_service/server_med_rec.php
  portal/portal_payment.php
  portal/report/portal_custom_report.php
Labels: Status: Ready for Integration

#2056 creating ParseERA class and updating X12 5010 remit codes
  interface/billing/billing_report.php
  interface/billing/edit_payment.php
  interface/billing/era_payments.php
  interface/billing/new_payment.php
  interface/billing/sl_eob_process.php
  interface/billing/sl_eob_search.php
  library/billing/src/BillingUtilities.php
  library/billing/src/ParseERA.php
  library/edihistory/edih_io.php
  library/edihistory/test_edih_835_accounting.php
  library/parse_era.inc.php
Labels: Status: Needs Review, Status: Reviewed

#2052 Changes in the patient messages
  interface/patient_file/summary/pnotes_full.php
  interface/patient_file/summary/pnotes_full_add.php
  library/pnotes.inc
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review, Status: Needs Work

#2057 Fix encounter POS
  interface/forms/newpatient/common.php
  library/classes/POSRef.class.php
Labels: Status: Needs Review

#2060 sleob billing class created
  interface/billing/edit_payment.php
  interface/billing/era_payments.php
  interface/billing/new_payment.php
  interface/billing/payment_pat_sel.inc.php
  interface/billing/sl_eob_invoice.php
  interface/billing/sl_eob_process.php
  interface/billing/sl_eob_search.php
  interface/patient_file/deleter.php
  interface/patient_file/front_payment.php
  interface/reports/collections_report.php
  library/billing/src/BillingUtilities.php
  library/billing/src/SLEOB.php
  library/billrep.inc
  library/invoice_summary.inc.php
  library/payment.inc.php
  library/sl_eob.inc.php
  portal/portal_payment.php
Labels: Status: Needs Review, Status: Needs Work

#2065 drug drug interaction update by Sherwin
  controllers/C_Prescription.class.php
  library/globals.inc.php
  templates/prescription/general_list.html
  version.php
Labels: Status: Needs Review

#2068 Portal Update Forum Request
  library/globals.inc.php
  portal/_header.php
  portal/home.php
Labels: Status: Needs Review, Status: Reviewed

#2075 authentication: fix undefined ``$provider`` variable in ``verify_user_gacl_group``
  library/auth.inc
  library/authentication/login_operations.php
Labels: Status: Needs Review

#2077 robots.txt
  robots.txt
Labels: Hardening

#2079 Replaced qtip2 tooltip with plain javascript tooltip
  interface/main/display_documents.php
Labels: Status: Needs Review

#2073 updated package versions
  package.json
Labels: Status: Needs Review

#2074 Translation fix
  interface/patient_file/summary/pnotes_full.php
Labels: Status: Needs Review
