Repository openemr/openemr, pull requests merged in 2018-09, with the labels that each got.

#1846 Style fixes (Mainly RTL)
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
  interface/main/dated_reminders/dated_reminders_add.php
  interface/main/messages/messages.php
  interface/patient_file/summary/pnotes_full.php
  interface/patient_file/summary/pnotes_full_add.php
  interface/themes/ajax_calendar.css
  interface/themes/colors/openemr5/bootstrap.scss
  interface/themes/core/forms.scss
  interface/themes/core/patient/notes.scss
  interface/themes/oe-common/acl-common.scss
  interface/themes/rtl.scss
  interface/therapy_groups/therapy_groups_views/groupDetailsGeneralData.php
  interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
Labels: Status: Needs Review

#1837 New build docs
  CONTRIBUTING.md
  README.md
  contrib/util/docker/docker-compose.yml
  docker-compose.yml
  gulpfile.js
  interface/README.md
  package-lock.json
  package.json
Labels: Status: Needs Review, Status: Needs Work

#1860 Portal Two update and bug fixes
  portal/messaging/messages.php
  portal/messaging/secure_chat.php
  portal/patient/scripts/app/onsitedocuments.js
  portal/portal_payment.php
  portal/sign/assets/signpad.css
  portal/sign/css/signer.css
Labels: Status: Needs Review, Status: Needs Work

#1869 Implementing U2F authentication.
  composer.json
  composer.lock
  interface/main/left_nav.php
  interface/main/main_screen.php
  interface/main/tabs/menu/menus/standard.json
  interface/usergroup/mfa_registrations.php
  interface/usergroup/mfa_u2f.php
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin.php
  library/js/u2f-api.js
  sites/default/documents/custom_menus/Custom.json
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Ready for Integration

#1821 change eligibility batch from ssn to policy number, minor fix to filename with extra dot
  interface/reports/edi_270.php
  library/edi.inc
Labels: Status: Needs Review
