Repository openemr/openemr, pull requests merged in 2018-11, with the labels that each got.

#1950 CTL Revision
  interface/forms/eye_mag/SpectacleRx.php
  interface/forms/eye_mag/css/style.css
  interface/forms/eye_mag/js/eye_base.php
  interface/forms/eye_mag/php/eye_mag_functions.php
  interface/forms/eye_mag/view.php
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review, Status: Needs Work

#1934 trying psr0 with x12 gen 837 p
  interface/billing/billing_process.php
  library/billing/src/Claim.php
  library/billing/src/X12837P.php
  library/gen_x12_837.inc.php
  library/gen_x12_837i.inc.php
Labels: Status: Needs Review, Status: Needs Work

#1959 put adj group codes on same line for 2ndary claims
  library/billing/src/X12837P.php
Labels: Status: Needs Review

#1962 Patient menu fixes
  interface/patient_file/history/history.php
  interface/patient_file/report/patient_report.php
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/stats_full.php
  interface/patient_file/transaction/transactions.php
  interface/reports/external_data.php
  interface/reports/pat_ledger.php
  library/menu/src/PatientMenuRole.php
  library/options.inc.php
Labels: Status: Needs Review, Status: Needs Work

#1963 using request, session, global pid to select patient
  interface/main/calendar/add_edit_event.php
Labels: Status: Needs Review

#1966 in_array() warning Reported on Forum by Sherwin
  controllers/C_Document.class.php
  library/options.inc.php
  library/patient.inc
Labels: Status: Reviewed

#1967 added acl check for create new patient link
  interface/main/calendar/find_patient_popup.php
Labels: Status: Needs Review

#1949 MedEx api 5.0.2
  interface/main/messages/messages.php
  interface/main/messages/save.php
  interface/patient_tracker/patient_tracker.php
  library/MedEx/API.php
  library/MedEx/MedEx.php
  library/MedEx/MedEx_background.php
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review, Status: Needs Work

#1969 Bugs fixes in the prescriptions screens
  controllers/C_Prescription.class.php
  templates/prescription/general_edit.html
  templates/prescription/general_list.html
Labels: Status: Needs Review, Status: Needs Work

#1996 Removing `npm-run-all` as dependency
  package-lock.json
  package.json
Labels: Status: Needs Review
