Repository openemr/openemr, pull requests merged in 2018-06, with the labels that each got.

#1678 Fixes in the loading of default tabs
  interface/main/main_screen.php
  interface/main/tabs/main.php
Labels: Status: Needs Review

#1679 Apply limit to names shown in document helper
  library/ajax/document_helpers.php
Labels: Status: Needs Review, Status: Needs Work

#1684 patient image fix when external id is different than id
  interface/main/tabs/js/patient_data_view_model.js
Labels: Status: Needs Review

#1687 Minor fixes and updates
  interface/usergroup/addrbook_list.php
  library/dialog.js
  templates/documents/general_list.html
Labels: Status: Needs Review

#1693 Initial support for nginx and php-fpm for openemr docker development environment
  contrib/util/docker/README.md
  contrib/util/docker/stuff/configs/dev-php-fpm-7-2/php.ini
  contrib/util/docker/stuff/configs/nginx/nginx.conf
  contrib/util/docker/stuff/dockers/dev-php-fpm-7-2/Dockerfile
  docker-compose.yml
Labels: Status: Needs Review

#1712 Drag and resize help modal using jquery-ui
  config/config.yaml
  interface/billing/sl_eob_search.php
  interface/help_modal.php
  interface/usergroup/adminacl.php
Labels: Status: Needs Review

#1713 Restyled Miscellaneous Billing Options HCFA with help file
  Documentation/help_files/cms_1500_help.php
  interface/forms/misc_billing_options/new.php
  library/globals.inc.php
Labels: Status: Needs Review, Status: Needs Work

#1717 Restyling - don't forget RTL languages..
  interface/forms/newpatient/common.php
  interface/package-lock.json
  interface/themes/core/text.scss
  interface/themes/rtl.css
  interface/themes/rtl_style_ash_blue.css
  interface/themes/rtl_style_burgundy.css
  interface/themes/rtl_style_cadmium_yellow.css
  interface/themes/rtl_style_chocolate.css
  interface/themes/rtl_style_cobalt_blue.css
  interface/themes/rtl_style_coral.css
  interface/themes/rtl_style_deep_purple.css
  interface/themes/rtl_style_dune.css
  interface/themes/rtl_style_emerald.css
  interface/themes/rtl_style_forest_green.css
  interface/themes/rtl_style_light.css
  interface/themes/rtl_style_manila.css
  interface/themes/rtl_style_mauve.css
  interface/themes/rtl_style_mustard_green.css
  interface/themes/rtl_style_olive.css
  interface/themes/rtl_style_pdf.css
  interface/themes/rtl_style_pink.css
  interface/themes/rtl_style_powder_blue.css
  interface/themes/rtl_style_red.css
  interface/themes/rtl_style_sienna.css
  interface/themes/rtl_style_tangerine.css
  interface/themes/style_ash_blue.css
  interface/themes/style_burgundy.css
  interface/themes/style_cadmium_yellow.css
  interface/themes/style_chocolate.css
  interface/themes/style_cobalt_blue.css
  interface/themes/style_coral.css
  interface/themes/style_deep_purple.css
  interface/themes/style_dune.css
  interface/themes/style_emerald.css
  interface/themes/style_forest_green.css
  interface/themes/style_light.css
  interface/themes/style_manila.css
  interface/themes/style_mauve.css
  interface/themes/style_mustard_green.css
  interface/themes/style_olive.css
  interface/themes/style_pink.css
  interface/themes/style_powder_blue.css
  interface/themes/style_red.css
  interface/themes/style_sienna.css
  interface/themes/style_tangerine.css
Labels: Status: Needs Review

#1719 tab rtl fixes and documentation changes
  interface/README.md
  interface/themes/rtl_tabs_style_compact.css
  interface/themes/rtl_tabs_style_full.css
Labels: Status: Needs Review

#1714 Restyled Form Vitals
  interface/forms/vitals/templates/vitals/general_new.html
  interface/patient_file/encounter/trend_form.php
Labels: Status: Needs Review

#1718 Use standard components in issue dialog
  interface/patient_file/summary/add_edit_issue.php
Labels: Status: Needs Review, Status: Needs Work

#1720 Restyled Procedure order to match the other restyled pages
  interface/forms/procedure_order/new.php
  library/globals.inc.php
Labels: Status: Needs Review

#1722 Restyled messages, dated reminders and added styling to integrate Recall Board
  Documentation/help_files/message_center_help.php
  interface/main/dated_reminders/dated_reminders.php
  interface/main/dated_reminders/dated_reminders_add.php
  interface/main/dated_reminders/dated_reminders_log.php
  interface/main/messages/messages.php
  library/MedEx/API.php
  library/dated_reminder_functions.php
  library/globals.inc.php
Labels: Status: Needs Review

#1615 wrong fax file destination in dialog.
  interface/fax/faxq.php
Labels: Status: Reviewed

#1724 Layout item display when list entry are missing
  interface/forms/LBF/report.php
  library/options.inc.php
Labels: Status: Ready for Integration, Status: Reviewed

#1731 small fix for graph js alert
  interface/patient_file/encounter/trend_form.php
Labels: Status: Needs Review, Status: Needs Work

#1737 fix SBR group name, number and fix duplicate onset date
  library/gen_x12_837.inc.php
Labels: Status: Needs Review
