Repository openemr/openemr, pull requests merged in 2018-04, with the labels that each got.

#1537 Adjust form tag placement
  interface/super/edit_list.php
Labels: Status: Needs Review, Status: Needs Work

#1538 Always list active drugs/inventory items first
  interface/drugs/drug_inventory.php
Labels: Status: Needs Review

#1536 Flow board begin date
  interface/patient_tracker/patient_tracker.php
  library/globals.inc.php
Labels: Status: Needs Review

#1545 Fetch bills for specific encoutner
  library/patient.inc
Labels: Status: Needs Review

#1546 recurring appointments categories in bold
  interface/patient_file/summary/demographics.php
Labels: Status: Needs Review

#1543 pad zip to 9 for 837, support letters icn resubmission
  library/gen_x12_837.inc.php
  sql/4_2_2-to-5_0_0_upgrade.sql
  sql/5_0_1-to-5_0_2_upgrade.sql
  version.php
Labels: Status: Needs Review, Status: Needs Work

#1550 Some menu and menu role work
  entities/User.php
  interface/main/tabs/menu/menu_db.php
  interface/main/tabs/menu/menu_json.php
  interface/main/tabs/menu/menu_updates.php
  interface/main/tabs/menu/menus/patient_menus/standard.json
  interface/patient_file/summary/demographics.php
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin.php
  interface/usergroup/usergroup_admin_add.php
  library/menu/src/MainMenuRole.php
  library/menu/src/MenuRole.php
  library/menu/src/PatientMenuRole.php
  sites/default/documents/custom_menus/patient_menus/Custom.json
  sql/5_0_0-to-5_0_1_upgrade.sql
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
  version.php
Labels: Status: Needs Review

#1554 global for amount of messages displayed in patient file
  interface/patient_file/summary/pnotes_fragment.php
  library/globals.inc.php
  version.php
Labels: Status: Needs Review, Status: Needs Work

#1557 fixed email text that was misaligned when being send to patients. Re…
  controllers/C_Document.class.php
Labels: Status: Needs Review

#1534 Logout from expired session
  interface/globals.php
  interface/login/login.php
  library/auth.inc
Labels: Status: Needs Review

#1562 Use of built-in color picker for appt categories
  interface/main/calendar/modules/PostCalendar/pntemplates/default/admin/submit_category.html
Labels: Status: Needs Review

#991 Remove dynarch calendar libraries
  library/dynarch_calendar.css
  library/dynarch_calendar.js
  library/dynarch_calendar_en.inc.php
  library/dynarch_calendar_en.js
  library/dynarch_calendar_setup.js
Labels: Status: Needs Review

#1565 ccda background service remove from edit globals
  interface/super/edit_globals.php
Labels: Priority: Blocking

#1556 Preventing recurrent appointment issues
  interface/main/calendar/modules/PostCalendar/pnuserapi.php
  interface/patient_file/report/custom_report.php
  interface/patient_file/summary/demographics.php
  library/appointments.inc.php
  library/encounter_events.inc.php
Labels: Status: Needs Review, Status: Needs Work

#1581 fix for #1580
  interface/patient_file/report/custom_report.php
Labels: Status: Needs Review, Status: Needs Work

#1588 Recall Populate using $pid from Session
  interface/main/messages/js/reminder_appts.js
  interface/main/messages/save.php
  library/MedEx/API.php
Labels: Status: Needs Review, Status: Needs Work

#1590 Updated ACL help file, minor styling changes
  interface/billing/sl_eob_search.php
  interface/forms/fee_sheet/new.php
  interface/themes/style_ash_blue.css
  interface/themes/style_burgundy.css
  interface/themes/style_cadmium_yellow.css
  interface/themes/style_chocolate.css
  interface/themes/style_cobalt_blue.css
  interface/themes/style_coral.css
  interface/themes/style_deep_purple.css
  interface/themes/style_dune.css
  interface/themes/style_emerald.css
  interface/themes/style_forest_green.css
  interface/themes/style_mauve.css
  interface/themes/style_mustard_green.css
  interface/themes/style_olive.css
  interface/themes/style_pink.css
  interface/themes/style_powder_blue.css
  interface/themes/style_red.css
  interface/themes/style_sienna.css
  interface/themes/style_tangerine.css
  interface/usergroup/adminacl.php
  interface/usergroup/adminacl_help.php
  library/globals.inc.php
Labels: Status: Needs Review
