Repository openemr/openemr, pull requests merged in 2019-03, with the labels that each got.

#2255 fix online drug lookup
  library/classes/RXList.class.php
Labels: Status: Needs Review

#2257 crypto support for document templates
  interface/patient_file/download_template.php
  interface/super/manage_document_templates.php
Labels: Status: Needs Review

#2256 [ISSUE-2053] Add variable binding to IN clauses to prevent SQL injection
  interface/billing/billing_report.php
  library/billrep.inc
Labels: Status: Needs Review, Status: Needs Work

#2262 Fix Creation of SSL Certificates
  interface/usergroup/ssl_certificates_admin.php
  library/create_ssl_certificate.php
Labels: Status: Needs Review

#2261 Adding validation of NPI number
  interface/weno/validate.php
  library/weno/src/TransmitData.php
Labels: Status: Needs Review, Status: Needs Work

#2263 replace file_get_contents with oeHttp
  controllers/C_Prescription.class.php
  library/classes/RXList.class.php
  library/weno/src/TransmitData.php
Labels: Status: Needs Review

#2268 Eligibility rework
  interface/reports/edi_270.php
  interface/reports/edi_271.php
  library/edi.inc
  library/globals.inc.php
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review

#2260 dlgopen Fix
  interface/forms/eye_mag/view.php
Labels: Status: Needs Review

#2266 Integrated MultiFactor Based Authentication with App Based TOTP, take 2.
  composer.json
  composer.lock
  interface/globals.php
  interface/main/main_screen.php
  interface/usergroup/mfa_registrations.php
  interface/usergroup/mfa_totp.php
  library/classes/Installer.class.php
  library/classes/Totp.class.php
  library/crypto.php
  library/translation.inc.php
  setup.php
  sql/database.sql
Labels: Status: Needs Review

#2254 fold writable directories into documents directory
  Documentation/INSTALL
  Documentation/Readme_edihistory.html
  Documentation/help_files/openemr_installation_help.php
  Documentation/help_files/sl_eob_help.php
  contrib/util/ubuntu_package_scripts/production/openemr.conf
  contrib/util/ubuntu_package_scripts/production/postinst
  contrib/util/ubuntu_package_scripts/production/preinst
  interface/billing/billing_process.php
  interface/billing/customize_log.php
  interface/billing/era_payments.php
  interface/billing/get_claim_file.php
  interface/billing/sl_eob_process.php
  interface/billing/sl_eob_search.php
  interface/billing/ub04_dispose.php
  interface/globals.php
  interface/main/left_nav.php
  interface/orders/receive_hl7_results.inc.php
  interface/patient_file/letter.php
  library/edihistory/edih_csv_inc.php
  setup.php
  sites/default/documents/edi/README.txt
  sites/default/documents/era/README.txt
  sites/default/documents/letter_templates/sample
  sites/default/documents/procedure_results/README
Labels: Status: Needs Review

#2276 eligibility updates
  library/edi.inc
Labels: Status: Needs Review

#2284 Fix typos
  gacl/admin/acl_debug.php
  interface/main/messages/lab_results_messages.php
  interface/modules/zend_modules/public/js/carecoordination/jquery.js
  interface/modules/zend_modules/public/js/carecoordination/ui/jquery-ui.custom.js
  interface/modules/zend_modules/public/js/carecoordination/ui/jquery.ui.mouse.js
  interface/modules/zend_modules/public/js/lib/jquery-ui.js
  interface/modules/zend_modules/public/js/lib/jquery.treeview-1.4.1/lib/jquery.js
  library/admin/src/AdminEvents.php
  library/ajax/addlistitem.php
  library/amc.php
  library/classes/rulesets/Amc/library/AbstractAmcReport.php
  library/globals.inc.php
  library/html2pdf/vendor/tecnickcom/tcpdf/include/tcpdf_static.php
  library/js/jquery.treeview-1.4.1/lib/jquery.js
  portal/patient/_global_config.php
  portal/patient/fwk/libs/verysimple/HTTP/Context.php
  portal/patient/fwk/libs/verysimple/Phreeze/ConnectionSetting.php
  portal/patient/fwk/libs/verysimple/Phreeze/Controller.php
  portal/patient/fwk/libs/verysimple/Phreeze/Criteria.php
  portal/patient/fwk/libs/verysimple/Phreeze/Dispatcher.php
  portal/patient/fwk/libs/verysimple/Phreeze/Phreezable.php
  portal/patient/fwk/libs/verysimple/Phreeze/QueryBuilder.php
  portal/patient/fwk/libs/verysimple/Phreeze/Reporter.php
  public/assets/manual-added-packages/modernizr-3-5-0/modernizr-build.js
  sql/2_6_0-to-2_6_1_upgrade.sql
  sql/3_2_0-to-4_0_0_upgrade.sql
  sql/4_0_0-to-4_1_0_upgrade.sql
  sql/4_1_1-to-4_1_2_upgrade.sql
  sql/database.sql
  sql/defaults.sql
  sql/example_patient_data.sql
Labels: Status: Needs Review, Status: Needs Work

#2286 new feature
  common/http/oeHttp.php
  common/http/oeHttpRequest.php
  interface/patient_file/summary/demographics.php
  interface/reports/edi_270.php
  interface/reports/edi_271.php
  library/edi.inc
Labels: Status: Needs Review

#2287 add eligibility to insurance setup
  controllers/C_InsuranceCompany.class.php
  interface/reports/edi_270.php
  library/classes/InsuranceCompany.class.php
  library/edi.inc
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
  templates/insurance_companies/general_edit.html
Labels: Status: Needs Review

#2300 Remove old patient portal
  interface/globals.php
  interface/modules/zend_modules/public/index.php
  interface/patient_file/summary/create_portallogin.php
  interface/patient_file/summary/dashboard_header.php
  library/globals.inc.php
  patients/add_edit_event_user.php
  patients/css/base.css
  patients/css/patientspage.css
  patients/css/tables.css
  patients/find_appt_popup_user.php
  patients/get_allergies.php
  patients/get_amendments.php
  patients/get_appointments.php
  patients/get_lab_results.php
  patients/get_medications.php
  patients/get_patient_documents.php
  patients/get_patient_info.php
  patients/get_problems.php
  patients/images/ajax-loader.gif
  patients/images/background.png
  patients/index.php
  patients/logout.php
  patients/summary_pat_portal.php
  patients/verify_session.php
  portal/account/account.lib.php
Labels: Status: Needs Review

#2223 Changes to list options edit
  interface/super/edit_list.php
Labels: Status: Needs Review, Status: Needs Work

#2304 Resolve issues with PR #2294
  library/edihistory/test_edih_835_accounting.php
  library/edihistory/test_edih_sftp_files.php
Labels: Status: Needs Review

#2318 Portal updates and general bug fixes
  ccdaservice/serveccda.js
  interface/patient_file/encounter/forms.php
  library/translation.inc.php
  portal/_header.php
  portal/get_lab_results.php
  portal/home.php
  portal/import_template_ui.php
  portal/lib/appsql.class.php
  portal/logout.php
  portal/messaging/secure_chat.php
  portal/patient/templates/OnsiteDocumentListView.tpl.php
  portal/patient/templates/ProviderHome.tpl.php
  portal/patient/templates/_Footer.tpl.php
  portal/patient/templates/_FormsHeader.tpl.php
  portal/patient/templates/_Header.tpl.php
  portal/patient/templates/_ProviderHeader.tpl.php
  portal/sign/assets/journal.eot
  portal/sign/assets/journal.svg
  portal/sign/assets/journal.ttf
  portal/sign/assets/journal.woff
  portal/sign/assets/pen.cur
  portal/sign/assets/signature_pad.umd.js
  portal/sign/assets/signer.js
  portal/sign/assets/signer_api.js
  portal/sign/assets/signer_modal.tpl.php
  portal/sign/assets/signhere.png
  portal/sign/assets/signpad.css
  portal/sign/assets/signpad.js
  portal/sign/css/signer.css
  portal/sign/css/signer_modal.css
  portal/sign/lib/save-signature.php
  portal/sign/lib/show-signature.php
  portal/sign/lib/sigconvert.php
Labels: Status: Reviewed

#2317 add bht claim id per kevmccor
  interface/billing/billing_process.php
Labels: Status: Needs Review

#2278 Block regular user from creating administrator
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin.php
  interface/usergroup/usergroup_admin_add.php
  library/acl.inc
Labels: Status: Needs Review, Status: Needs Work

#2320 portal fixes
  interface/globals.php
  portal/index.php
  portal/logout.php
Labels: Status: Ready for Integration

#2321 secure the admin files edit feature
  interface/super/manage_site_files.php
Labels: Status: Needs Review

#2325 Fixes #2324 Rest API Fatal Error.
  API_README.md
  interface/globals.php
Labels: Status: Ready for Integration

#2335 api token crypto secure and another minor change
  rest_controllers/AuthRestController.php
Labels: Status: Needs Review

#2334 Update deprecated $(document).ready in add_edit_event.php
  interface/main/calendar/add_edit_event.php
  package-lock.json
Labels: Status: Needs Review
