Repository openemr/openemr, pull requests merged in 2019-08, with the labels that each got.

#2593 Move Blank Forms from Reports to Miscellaneous, since they are not re…
  interface/main/tabs/menu/menus/standard.json
  sites/default/documents/custom_menus/Custom.json
Labels: Status: Needs Review

#2598 fix in Miscellaneous menu item permissions
  interface/main/tabs/menu/menus/standard.json
  sites/default/documents/custom_menus/Custom.json
Labels: Status: Needs Review

#2591 Feature more options to search box
  interface/main/tabs/templates/patient_data_template.php
  interface/themes/oe-common/main-common.scss
  library/globals.inc.php
Labels: Status: Needs Review

#2581 Add hover over background colour transition in .menuLabel
  interface/main/tabs/templates/menu_template.php
  interface/main/tabs/templates/user_data_template.php
  interface/themes/oe-common/help-files-common.scss
  interface/themes/rtl_style_pdf.css
  interface/themes/tabs_style_compact.css
  interface/themes/tabs_style_full.css
Labels: Status: Needs Review

#2545 Fix date format patient file
  interface/patient_file/summary/add_edit_issue.php
  interface/patient_file/summary/stats_full.php
Labels: Status: Needs Review

#2571 Organize Admin. menu, Remove items from Miscellaneous-relative to #2301
  interface/main/tabs/menu/menus/standard.json
  sites/default/documents/custom_menus/Custom.json
Labels: Status: Needs Review

#2617 remove cookie when remove the session
  src/Common/Session/SessionUtil.php
Labels: Status: Needs Work

#2614 Some new features
  controllers/C_Document.class.php
  interface/forms/LBF/new.php
  interface/patient_file/download_template.php
  interface/patient_file/front_payment.php
  interface/super/edit_layout.php
  library/options.inc.php
  library/options.js.php
  portal/_header.php
  portal/import_template_ui.php
  portal/lib/doc_lib.php
  portal/lib/download_template.php
  portal/patient/_machine_config.php
  portal/patient/libs/Controller/OnsiteDocumentController.php
  portal/patient/scripts/app/onsiteactivityviews.js
  portal/patient/scripts/app/onsitedocuments.js
  portal/patient/scripts/app/onsiteportalactivities.js
  portal/patient/scripts/app/patientdata.js
  portal/patient/templates/OnsiteDocumentListView.tpl.php
  portal/patient/templates/ProviderHome.tpl.php
  portal/patient/templates/_Footer.tpl.php
  portal/patient/templates/_FormsHeader.tpl.php
  portal/sign/assets/signer_api.js
  portal/sign/assets/signer_modal.tpl.php
  portal/sign/assets/signit.php
  portal/sign/css/signer_modal.css
  portal/sign/lib/save-signature.php
  portal/sign/lib/show-signature.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  templates/documents/general_list.html
  templates/documents/general_upload.html
  version.php
Labels: Status: Needs Review, Status: Needs Work

#2577 Percent-based price levels
  library/FeeSheet.class.php
  library/FeeSheetHtml.class.php
  library/globals.inc.php
  version.php
Labels: Status: Needs Review, Status: Needs Work

#2622 backport v5.0.3 PR #2614 and #2615 for 5.0.2 patch 1
  controllers/C_Document.class.php
  interface/billing/billing_process.php
  interface/billing/billing_report.php
  interface/forms/LBF/new.php
  interface/login/login.php
  interface/patient_file/download_template.php
  interface/patient_file/front_payment.php
  interface/super/edit_layout.php
  library/options.inc.php
  library/options.js.php
  portal/_header.php
  portal/import_template_ui.php
  portal/lib/doc_lib.php
  portal/lib/download_template.php
  portal/patient/_machine_config.php
  portal/patient/libs/Controller/OnsiteDocumentController.php
  portal/patient/scripts/app/onsiteactivityviews.js
  portal/patient/scripts/app/onsitedocuments.js
  portal/patient/scripts/app/onsiteportalactivities.js
  portal/patient/scripts/app/patientdata.js
  portal/patient/templates/OnsiteDocumentListView.tpl.php
  portal/patient/templates/ProviderHome.tpl.php
  portal/patient/templates/_Footer.tpl.php
  portal/patient/templates/_FormsHeader.tpl.php
  portal/sign/assets/signer_api.js
  portal/sign/assets/signer_modal.tpl.php
  portal/sign/assets/signit.php
  portal/sign/css/signer_modal.css
  portal/sign/lib/save-signature.php
  portal/sign/lib/show-signature.php
  sql/database.sql
  sql/patch.sql
  templates/documents/general_list.html
  templates/documents/general_upload.html
Labels: Status: Needs Review, Status: Needs Work

#2621 Add constant description, make constants translatable
  interface/batchcom/batchcom.php
  library/MedEx/API.php
  portal/messaging/secure_chat.php
Labels: Status: Needs Review, Status: Needs Work

#2624 invalid escaping to html
  interface/billing/billing_process.php
Labels: Status: Ready for Integration

#2625 js translation support proposal
  config/config.yaml
  interface/main/tabs/js/tabs_view_model.js
  interface/main/tabs/main.php
  interface/patient_file/summary/demographics.php
  library/ajax/i18n_generator.php
  library/ajax/phpvars_to_js.php
  library/js/utility.js
  package.json
Labels: Status: Needs Review

#2628 mariadb fix
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review

#2608 Bye Bye Frames
  custom/readme_search.txt
  custom/search.php
  interface/billing/billing_report.php
  interface/billing/sl_eob_invoice.php
  interface/forms/eye_mag/js/eye_base.php
  interface/forms/eye_mag/php/eye_mag_functions.php
  interface/forms/newGroupEncounter/common.php
  interface/forms/newpatient/common.php
  interface/login/login.php
  interface/main/daemon_frame.php
  interface/main/left_nav.php
  interface/main/main_screen.php
  interface/main/main_title.php
  interface/main/messages/js/reminder_appts.js
  interface/main/messages/messages.php
  interface/main/tabs/js/include_opener.js
  interface/main/tabs/js/tabs_view_model.js
  interface/main/tabs/main.php
  interface/orders/single_order_results.inc.php
  interface/patient_file/encounter/forms.php
  interface/patient_file/front_payment.php
  interface/patient_file/summary/demographics.php
  interface/patient_tracker/patient_tracker.php
  interface/themes/rtl.scss
  interface/themes/rtl_style_pdf.css
  interface/therapy_groups/therapy_groups_views/groupDetailsGeneralData.php
  interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
  library/dialog.js
  library/globals.inc.php
  portal/_header.php
  templates/documents/general_view.html
  version.php
Labels: Status: Needs Review

#2627 Got a request that it is mandatory for the header and footer by CMS
  interface/forms/LBF/printable.php
  library/encounter.inc
  library/patient.inc
Labels: Status: Needs Review, Status: Needs Work
