Repository openemr/openemr, pull requests merged in 2019-01, with the labels that each got.

#2093 Strengthen part of username and password creation process
  setup.php
Labels: Status: Needs Review, Status: Needs Work

#2092 Remove qtip2
  interface/forms/eye_mag/SpectacleRx.php
  interface/forms/eye_mag/a_issue.php
  interface/forms/eye_mag/help.php
  interface/forms/eye_mag/js/eye_base.php
  interface/forms/eye_mag/php/Anything_simple.php
  interface/forms/eye_mag/view.php
  interface/main/display_documents.php
Labels: Status: Needs Review

#2102 Bind sql parameters spreadsheet (#2095)
  library/spreadsheet.inc.php
Labels: Status: Needs Review

#2099 Portal V2 Online Payment Universal Gateway.
  composer.json
  composer.lock
  interface/main/tabs/js/user_data_view_model.js
  interface/main/tabs/main.php
  interface/main/tabs/templates/patient_data_template.php
  library/billing/src/PaymentGateway.php
  library/dated_reminder_functions.php
  library/globals.inc.php
  portal/_header.php
  portal/assets/css/style.css
  portal/home.php
  portal/lib/appsql.class.php
  portal/lib/paylib.php
  portal/patient/scripts/app/onsiteactivityviews.js
  portal/portal_payment.php
  portal/sign/css/signer.css
Labels: Status: Ready for Integration

#2105 Update the GUI so that it is uses current terminology
  interface/practice/ins_search.php
  library/billing/src/X12_5010_837P.php
  library/classes/InsuranceCompany.class.php
  library/gen_x12_837i.inc.php
  templates/insurance_companies/general_edit.html
Labels: Status: Needs Review, Status: Needs Work

#2113 Fixing issue #2097
  library/calendar.inc
Labels: Status: Needs Review, Status: Needs Work

#2108 Added encryption and decryptStandard to globals
  ccr/transmitCCD.php
  interface/batchcom/batch_phone_notification.php
  interface/cmsportal/portal.inc.php
  interface/eRxGlobals.php
  interface/eRx_xml.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
  interface/modules/zend_modules/module/Documents/src/Documents/Plugin/Documents.php
  interface/weno/jsonScript.php
  library/classes/CouchDB.class.php
  library/direct_message_check.inc
  library/globals.inc.php
  library/reminders.php
  modules/sms_email_reminder/batch_phone_notification.php
  myportal/soap_service/server_med_rec.php
Labels: Status: Needs Review, Status: Needs Work

#2131 Portal
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Ready for Integration

#2139 Setup script bootstrapped with new theme selector - Take 2
  Documentation/help_files/openemr_installation_help.php
  library/classes/Installer.class.php
  public/images/stylesheets/style_ash_blue.png
  public/images/stylesheets/style_burgundy.png
  public/images/stylesheets/style_cadmium_yellow.png
  public/images/stylesheets/style_chocolate.png
  public/images/stylesheets/style_cobalt_blue.png
  public/images/stylesheets/style_coral.png
  public/images/stylesheets/style_deep_purple.png
  public/images/stylesheets/style_dune.png
  public/images/stylesheets/style_emerald.png
  public/images/stylesheets/style_forest_green.png
  public/images/stylesheets/style_light.png
  public/images/stylesheets/style_manila.png
  public/images/stylesheets/style_mauve.png
  public/images/stylesheets/style_mustard_green.png
  public/images/stylesheets/style_olive.png
  public/images/stylesheets/style_pink.png
  public/images/stylesheets/style_powder_blue.png
  public/images/stylesheets/style_red.png
  public/images/stylesheets/style_sienna.png
  public/images/stylesheets/style_tangerine.png
  setup.php
Labels: Status: Needs Review

#2149 Disable napa cache
  package.json
Labels: Status: Needs Review

#2155 Bootstrapped admin.php for multisite installation
  Documentation/help_files/openemr_installation_help.php
  Documentation/help_files/openemr_multisite_admin_help.php
  admin.php
  library/classes/Installer.class.php
  setup.php
Labels: Status: Needs Review, Status: Needs Work

#2154 [ISSUE-2053] Add variable binding to prevent SQL injection attacks
  library/acl.inc
  library/billing/src/Claim.php
  library/classes/Address.class.php
  library/classes/CategoryTree.class.php
  library/classes/Company.class.php
  library/classes/Document.class.php
  library/classes/InsuranceCompany.class.php
  library/classes/InsuranceNumbers.class.php
  library/classes/Note.class.php
  library/classes/ORDataObject.class.php
  library/classes/Patient.class.php
  library/classes/Pharmacy.class.php
  library/classes/PhoneNumber.class.php
  library/classes/Prescription.class.php
  library/create_ssl_certificate.php
  library/encounter.inc
  library/forms.inc
  library/lab.inc
  library/log.inc
  library/options.inc.php
  library/standard_tables_capture.inc
Labels: Status: Needs Review, Status: Needs Work

#2159 Prescription fixes
  interface/patient_file/summary/demographics.php
  templates/prescription/general_edit.html
  templates/prescription/general_list.html
Labels: Status: Needs Review, Status: Needs Work
