Repository openemr/openemr, pull requests merged in 2019-11, with the labels that each got.

#2766 minor ldap changes
  library/authentication/login_operations.php
  library/authentication/password_change.php
Labels: Status: Needs Review

#2756 Adding info field to facilities mechanism
  interface/usergroup/facilities.php
  interface/usergroup/facilities_add.php
  interface/usergroup/facility_admin.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  src/Services/FacilityService.php
Labels: Status: Needs Review, Status: Needs Work

#2772 add dx history finder for procedure order form
  interface/forms/procedure_order/new.php
  interface/orders/single_order_results.inc.php
  interface/patient_file/encounter/find_code_history.php
Labels: Status: Needs Review

#2770 update hashing
  contrib/util/installScripts/InstallerAuto.php
  interface/globals.php
  interface/login/login.php
  interface/main/main_screen.php
  interface/main/pwd_expires_alert.php
  interface/patient_file/summary/create_portallogin.php
  interface/usergroup/mfa_totp.php
  interface/usergroup/user_admin.php
  interface/usergroup/user_info.php
  interface/usergroup/user_info_ajax.php
  interface/usergroup/usergroup_admin.php
  library/ESign/Encounter/Controller.php
  library/ESign/Form/Controller.php
  library/auth.inc
  library/authentication/common_operations.php
  library/authentication/login_operations.php
  library/authentication/password_change.php
  library/authentication/password_hashing.php
  library/authentication/privDB.php
  library/classes/Installer.class.php
  library/globals.inc.php
  library/sql.inc
  portal/account/account.lib.php
  portal/account/index_reset.php
  portal/get_patient_info.php
  portal/patient/libs/Model/DAO/UserMap.php
  portal/patient/libs/Reporter/UserReporter.php
  setup.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  src/Common/Auth/AuthHash.php
  src/Common/Auth/AuthUtils.php
  src/Entities/User.php
  src/RestControllers/AuthRestController.php
  version.php
Labels: Status: Needs Review

#2786 5.0.2.3_MedEx
  interface/main/messages/messages.php
  interface/patient_tracker/patient_tracker.php
  library/MedEx/API.php
  library/MedEx/MedEx.php
  library/MedEx/MedEx_background.php
Labels: Status: Needs Review

#2781 Flex tab container and bootstrap playing nice
  interface/login/login.php
  interface/main/calendar/add_edit_event.php
  interface/main/calendar/find_patient_popup.php
  interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
  interface/main/main_info.php
  interface/patient_file/encounter/find_code_history.php
  interface/themes/ajax_calendar.css
  interface/themes/tabs_style_compact.css
  interface/themes/tabs_style_full.css
  library/dialog.js
Labels: Status: Needs Review

#2789 Several updates related to session variables and password
  interface/batchcom/batchEmail.php
  interface/billing/edi_270.php
  interface/drugs/drugs.inc.php
  interface/forms/CAMOS/content_parser.php
  interface/forms/eye_mag/save.php
  interface/forms/eye_mag/view.php
  interface/forms/fee_sheet/review/fee_sheet_queries.php
  interface/forms/group_attendance/functions.php
  interface/forms/vitals/FormVitals.class.php
  interface/main/calendar/add_edit_event.php
  interface/main/calendar/index.php
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
  interface/main/dated_reminders/dated_reminders_add.php
  interface/main/dated_reminders/dated_reminders_log.php
  interface/main/display_documents.php
  interface/main/main_screen.php
  interface/main/pwd_expires_alert.php
  interface/main/tabs/main.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CcdController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/encountermanager/index.phtml
  interface/modules/zend_modules/module/Ccr/src/Ccr/Controller/CcrController.php
  interface/patient_file/front_payment.php
  interface/patient_file/pos_checkout.php
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/immunizations.php
  interface/patient_file/summary/shot_record.php
  interface/super/edit_globals.php
  interface/usergroup/mfa_registrations.php
  interface/usergroup/mfa_totp.php
  interface/usergroup/mfa_u2f.php
  interface/usergroup/user_admin.php
  interface/usergroup/user_info.php
  interface/usergroup/user_info_ajax.php
  interface/usergroup/usergroup_admin.php
  library/FeeSheet.class.php
  library/classes/Document.class.php
  library/classes/Prescription.class.php
  library/clinical_rules.php
  library/custom_template/add_custombutton.php
  library/custom_template/ajax_code.php
  library/custom_template/custom_template.php
  library/custom_template/personalize.php
  library/custom_template/updateDB.php
  library/dated_reminder_functions.php
  library/globals.inc.php
  library/sanitize.inc.php
  myportal/index.php
  portal/portal_payment.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  src/Billing/BillingUtilities.php
  src/Common/Auth/AuthHash.php
  src/Common/Auth/AuthUtils.php
  src/Common/Logging/EventAuditLogger.php
  tests/unit/BaseHarness.class.php
  version.php
Labels: Status: Needs Review

#2790 allow 2019 ecqm value set
  interface/code_systems/list_staged.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review

#2800 Fix for Patient Portal Responsiveness (#2793)
  portal/account/register.php
  portal/assets/css/base.css
  portal/assets/css/register.css
  portal/assets/css/style.css
  portal/index.php
  portal/patient/templates/PatientListView.tpl.php
Labels: Status: Needs Review

#2804 Ability to add new routes to the routes map array, in a each zend module.
  _rest_routes.inc.php
  src/Events/RestApiExtend/RestApiCreateEvent.php
  tests/eventdispatcher/RestApiEventHookExample/Module.php
  tests/eventdispatcher/RestApiEventHookExample/autoload_classmap.php
  tests/eventdispatcher/RestApiEventHookExample/composer.json
  tests/eventdispatcher/RestApiEventHookExample/config/module.config.php
  tests/eventdispatcher/RestApiEventHookExample/info.txt
Labels: Status: Needs Review

#2812 NTE segment in PID leads to rejected results
  interface/orders/receive_hl7_results.inc.php
Labels: Status: Ready for Integration, Status: Reviewed

#2814 attr() needed argument
  library/edihistory/edih_835_html.php
Labels: Status: Ready for Integration, Status: Reviewed

#2823 updated 3rd party composer packages
  composer.json
  composer.lock
Labels: Status: Needs Review, Status: Needs Work
