Repository openemr/openemr, pull requests merged in 2019-05, with the labels that each got.

#2401 internal api call clarifications
  common/http/oeHttp.php
  common/http/oeHttpRequest.php
  controllers/C_Prescription.class.php
  interface/reports/edi_270.php
  library/weno/src/TransmitData.php
  phpfhir/libs/controller/ClientAppController.php
Labels: Status: Needs Review, Status: Needs Work

#2408 fix warnings and improve 837 view
  interface/billing/edih_view.php
  library/edihistory/edih_csv_data.php
  library/edihistory/edih_csv_inc.php
Labels: Status: Needs Review

#2407 Decrease encounter tab container height to prevent scroll bar.
  interface/patient_file/encounter/encounter_top.php
  library/tabs/src/TabsWrapper.php
  portal/patient/templates/OnsiteDocumentListView.tpl.php
Labels: Status: Needs Review, Status: Reviewed

#2413 Emulate frames left nav 'Any' search
  interface/main/finder/dynamic_finder.php
  interface/main/finder/dynamic_finder_ajax.php
  interface/main/tabs/js/user_data_view_model.js
  interface/main/tabs/templates/patient_data_template.php
Labels: Status: Needs Review, Status: Reviewed

#2416 appt finder locale date support and some security updates
  interface/main/calendar/find_appt_popup.php
Labels: Status: Needs Review

#2426 seed for the error log escape project
  library/billing/src/X12_5010_837P.php
  library/htmlspecialchars.inc.php
  portal/account/account.lib.php
Labels: Status: Needs Review

#2431 Responsive Vertical Menu For Tab Based Layout Take 2
  interface/main/tabs/js/application_view_model.js
  interface/main/tabs/main.php
  interface/main/tabs/templates/user_data_template.php
  interface/themes/color_base.scss
  interface/themes/colors/openemr5/tabs-full.scss
  interface/themes/oe-common/all-common-import.scss
  interface/themes/oe-common/main-common.scss
  interface/themes/oe-common/procedures-common.scss
  interface/themes/style_light.scss
  interface/themes/style_manila.scss
  interface/themes/tabs_style_compact.css
  interface/themes/tabs_style_full.css
  library/globals.inc.php
Labels: Status: Needs Review, Status: Needs Work

#2433 Fix Related Patient Notes
  interface/orders/list_reports.php
  interface/orders/single_order_results.inc.php
  interface/orders/single_order_results.php
  interface/patient_file/summary/pnotes_full.php
  interface/patient_file/summary/pnotes_full_add.php
  interface/themes/core/patient/notes.scss
  interface/themes/rtl_style_pdf.css
  interface/themes/style_pdf.css
  library/dialog.js
Labels: Status: Needs Review, Status: Needs Work

#2439 api support for ajax calls (that is secured from csrf)
  API_README.md
  _rest_config.php
  _rest_routes.inc.php
  apis/dispatch.php
  common/http/HttpRestRouteHandler.php
  common/http/oeHttp.php
  common/http/oeHttpRequest.php
  interface/main/main_screen.php
  phpfhir/libs/controller/ClientAppController.php
  rest_controllers/AuthRestController.php
  tests/api/tempFileTestInternalApi.php
Labels: Status: Needs Review

#2415 Change JS functions for browsers compatibility (edit_list.php)
  interface/super/edit_list.php
Labels: Status: Needs Review

#2441 Escaping functions
  common/logging/Logger.php
  common/utils/RandomGenUtils.php
  controllers/C_Document.class.php
  interface/billing/sl_eob_search.php
  interface/drugs/dispense_drug.php
  interface/drugs/drugs.inc.php
  interface/forms/eye_mag/php/taskman_functions.php
Labels: Status: Needs Review, Status: Needs Work

#2444 add appointments and some better demographics to superbill
  interface/patient_file/printed_fee_sheet.php
  interface/patient_file/report/custom_report.php
  interface/reports/appointments_report.php
Labels: Status: Needs Review

#2447 htmlspecialchars fixes
  interface/orders/orders_results.php
Labels: Status: Needs Review, Status: Needs Work
