Repository openemr/openemr, pull requests merged in 2019-02, with the labels that each got.

#2173 Feature/fix allergic reaction translation
  interface/patient_file/summary/stats.php
Labels: Status: Needs Review, Status: Needs Work

#2199 Fix for invoice edits close
  interface/billing/sl_eob_invoice.php
  interface/billing/sl_eob_search.php
  interface/patient_file/history/encounters.php
  interface/reports/collections_report.php
Labels: Status: Needs Review

#2170 Adding business address 2
  interface/usergroup/facilities.php
  interface/usergroup/facilities_add.php
  interface/usergroup/facility_admin.php
  services/FacilityService.php
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review, Status: Needs Work

#2201 updated to apache 2.4 syntax
  Documentation/help_files/openemr_installation_help.php
  contrib/util/ubuntu_package_scripts/development/git-openemr.conf
  contrib/util/ubuntu_package_scripts/production/openemr.conf
  setup.php
Labels: Status: Needs Review

#2203 Three NewCrop eRx fixes
  interface/eRx.php
  interface/eRxXMLBuilder.php
  interface/main/tabs/js/custom_bindings.js
  interface/main/tabs/js/tabs_view_model.js
Labels: Status: Needs Review

#2195 Fix/forms delete form name error
  interface/patient_file/encounter/delete_form.php
Labels: Status: Needs Review, Status: Needs Work

#2210 Front Office Collection Report - Facility and Provider Filters
  interface/reports/front_receipts_report.php
Labels: Status: Needs Review, Status: Needs Work

#2211 Crypto updates
  common/compatibility/Checker.php
  interface/billing/billing_process.php
  interface/billing/billing_report.php
  interface/billing/customize_log.php
  library/billing/src/Claim.php
  library/crypto.php
  library/globals.inc.php
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#1895 Portal fixes back port
  interface/forms/newpatient/common.php
  interface/main/tabs/js/user_data_view_model.js
  interface/main/tabs/main.php
  interface/main/tabs/templates/patient_data_template.php
  library/ajax/dated_reminders_counter.php
  library/ajax/facility_ajax_code.php
  library/classes/POSRef.class.php
  library/dated_reminder_functions.php
  library/dialog.js
  library/globals.inc.php
  library/options.inc.php
  portal/_header.php
  portal/home.php
  portal/import_template_ui.php
  portal/lib/doc_lib.php
  portal/lib/download_template.php
  portal/lib/portal_mail.inc
  portal/messaging/messages.php
  portal/messaging/secure_chat.php
  portal/patient/libs/Controller/ProviderController.php
  portal/patient/scripts/app/onsitedocuments.js
  portal/patient/templates/OnsiteDocumentListView.tpl.php
  portal/patient/templates/_Footer.tpl.php
  portal/portal_payment.php
  portal/sign/assets/signpad.css
  portal/sign/css/signer.css
  sql/database.sql
  sql/patch.sql
  version.php
Labels: Status: Needs Work

#2214 edi 270 batch eligibilty fixes
  library/edi.inc
Labels: Status: Needs Review

#2215 make Column escape flexible #2212
  library/billing/src/BillingUtilities.php
  library/formdata.inc.php
  library/registry.inc
Labels: Status: Needs Review, Status: Reviewed

#2226 escape column names in sql statements #2141
  library/api.inc
  library/auth.inc
  library/forms.inc
Labels: Status: Needs Review, Status: Needs Work

#2229 escape table column names #2141
  interface/patient_file/summary/stats.php
  library/lists.inc
  library/pnotes.inc
  library/transactions.inc
Labels: Status: Needs Review, Status: Needs Work

#2234 [ISSUE-1350] Modify all table references of `pid` to type bigint
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#2238 drive storage encryption
  controllers/C_Document.class.php
  interface/forms/eye_mag/php/taskman_functions.php
  interface/forms/eye_mag/report.php
  interface/patient_file/report/custom_report.php
  library/classes/Document.class.php
  library/crypto.php
  portal/report/portal_custom_report.php
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#2244 Set secure_upload on as default
  library/globals.inc.php
  sql/database.sql
Labels: Status: Needs Review, Status: Needs Work

#2232 new feature - custom assets
  config/config.yaml
  custom/assets/README
  custom/assets/css/README
  custom/assets/custom.yaml.example
  custom/assets/js/README
  library/core/src/Header.php
Labels: Status: Needs Review, Status: Needs Work

#2253 Migrate smarty compile dir into documents and make cache optional
  Documentation/INSTALL
  Documentation/help_files/openemr_installation_help.php
  contrib/util/ubuntu_package_scripts/production/postinst
  contrib/util/ubuntu_package_scripts/production/preinst
  docker-compose.yml
  gacl/admin/gacl_admin.inc.php
  gacl/admin/templates_c/README
  interface/globals.php
  interface/main/calendar/modules/PostCalendar/pcSmarty.class.php
  interface/main/calendar/modules/PostCalendar/pntemplates/cache/README
  interface/main/calendar/modules/PostCalendar/pntemplates/compiled/README
  library/classes/Controller.class.php
  setup.php
Labels: Status: Needs Review
