Repository openemr/openemr, pull requests merged in 2019-06, with the labels that each got.

#2460 Fully responsive globals.php with vertical menu
  interface/super/edit_globals.php
  interface/themes/color_base.scss
  interface/themes/colors/openemr5/edit_globals_colors.scss
  interface/themes/colors/openemr5/tabs-full.scss
  interface/themes/colors/style_ash_blue.scss
  interface/themes/colors/style_cadmium_yellow.scss
  interface/themes/colors/style_chocolate.scss
  interface/themes/colors/style_cobalt_blue.scss
  interface/themes/colors/style_emerald.scss
  interface/themes/colors/style_mauve.scss
  interface/themes/colors/style_mustard_green.scss
  interface/themes/colors/style_powder_blue.scss
  interface/themes/colors/style_red.scss
  interface/themes/colors/style_tangerine.scss
  interface/themes/core.scss
  interface/themes/core/edit_globals.scss
  interface/themes/core/oe-mobile.scss
  interface/themes/style_light.scss
  interface/themes/style_manila.scss
  interface/themes/tabs_style_compact.css
  library/globals.inc.php
  library/js/oeUI/universalTooltip.js
Labels: Status: Needs Review, Status: Reviewed

#2458 few fixes for batch eligibility
  interface/reports/edi_270.php
  library/edi.inc
Labels: Status: Needs Review

#2462 Zend Module Event Dispatcher w/ Consolidated Menu
  interface/globals.php
  interface/main/left_nav.php
  interface/main/tabs/menu/menu_json.php
  interface/modules/zend_modules/module/Application/Module.php
  interface/modules/zend_modules/module/Application/config/module.config.php
  interface/modules/zend_modules/module/Application/src/Application/Listener/ModuleMenuSubscriber.php
  interface/modules/zend_modules/public/index.php
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin_add.php
  src/Core/ModulesApplication.php
  src/Menu/MainMenuRole.php
  src/Menu/MenuEvent.php
Labels: Status: Needs Review

#2464 zip needs flags on php 7.1?
  ccr/createCCR.php
  custom/ajax_download.php
  interface/usergroup/ssl_certificates_admin.php
  library/edihistory/edih_archive.php
  library/edihistory/edih_uploads.php
  library/standard_tables_capture.inc
  portal/get_patient_documents.php
Labels: Status: Needs Review

#2465 Changes in PrescriptionTemplates module
  interface/modules/zend_modules/module/PrescriptionTemplates/config/module.config.php
  interface/modules/zend_modules/module/PrescriptionTemplates/src/PrescriptionTemplates/Controller/HtmlTemplatesController.php
  interface/modules/zend_modules/module/PrescriptionTemplates/src/PrescriptionTemplates/Controller/PdfTemplatesController.php
Labels: Status: Needs Review

#2470 weno drug sql import fails window
  library/classes/Prescription.class.php
  library/sql_upgrade_fx.php
Labels: Status: Needs Review

#2475 bug fixins
  library/classes/Prescription.class.php
  library/classes/Provider.class.php
  library/classes/Tree.class.php
  modules/sms_email_reminder/batch_phone_notification.php
  modules/sms_email_reminder/batch_reminders.php
  modules/sms_email_reminder/cron_email_notification.php
  modules/sms_email_reminder/cron_functions.php
  modules/sms_email_reminder/cron_sms_notification.php
  modules/sms_email_reminder/readme.txt
  modules/sms_email_reminder/sms_clickatell.php
  modules/sms_email_reminder/sms_tmb4.php
  portal/_header.php
  portal/account/account.lib.php
  portal/account/register.php
  portal/add_edit_event_user.php
  portal/find_appt_popup_user.php
  portal/get_lab_results.php
  portal/get_patient_documents.php
  portal/get_patient_info.php
  portal/home.php
  portal/import_template_ui.php
  portal/index.php
  portal/messaging/messages.php
  portal/messaging/secure_chat.php
  portal/portal_payment.php
  portal/report/pat_ledger.php
  portal/report/portal_custom_report.php
  portal/report/portal_patient_report.php
  portal/sign/lib/save-signature.php
  portal/sign/lib/show-signature.php
  portal/verify_session.php
  sites/default/LBF/LBFathbf.plugin.php
  sites/default/LBF/LBFathv.plugin.php
  sites/default/LBF/LBFgcac.plugin.php
  sites/default/LBF/LBFvbf.plugin.php
  sites/default/statement.inc.php
  templates/pharmacies/general_list.html
  templates/prescription/general_edit.html
  templates/prescription/general_list.html
  templates/x12_partners/general_edit.html
  templates/x12_partners/general_list.html
Labels: Status: Needs Work

#2476 more bug fixes
  interface/main/calendar/modules/PostCalendar/pnadmin.php
  interface/main/calendar/modules/PostCalendar/pntemplates/default/admin/submit_category.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/outlook_ajax_template.html
Labels: Status: Needs Work

#2480 already json encoded in form php init
  interface/billing/ub04_form.php
  interface/forms/misc_billing_options/new.php
  interface/forms/misc_billing_options/save.php
Labels: Status: Ready for Integration

#2493 Screens of reminders with local format date
  interface/main/dated_reminders/dated_reminders_add.php
  interface/main/dated_reminders/dated_reminders_log.php
  library/dated_reminder_functions.php
Labels: Status: Needs Review

#2492 Dg/fix delete in forms
  interface/patient_file/encounter/forms.php
Labels: Status: Needs Review, Status: Needs Work

#2495 fix payment method in receipts report - alerted by forum post
  interface/reports/receipts_by_method_report.php
Labels: Status: Needs Review

#2500 remove twig
  build.xml
  composer.json
  composer.lock
  interface/globals.php
  src/Core/Header.php
Labels: Status: Needs Review

#2505 Fixes #1524 CCDA Warnings, Dependency resolution in modules
  interface/modules/zend_modules/module/Application/src/Application/Controller/SendtoController.php
  interface/modules/zend_modules/module/Carecoordination/config/module.config.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/ccd/upload.phtml
  interface/modules/zend_modules/module/Ccr/config/module.config.php
  interface/modules/zend_modules/module/Ccr/view/ccr/ccr/index.phtml
  interface/modules/zend_modules/module/Documents/src/Documents/Controller/DocumentsController.php
  interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
  interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
  interface/modules/zend_modules/module/Syndromicsurveillance/view/syndromicsurveillance/syndromicsurveillance/index.phtml
Labels: Status: Needs Review, Status: Needs Work

#2516 5.0.2_medex
  interface/main/messages/js/reminder_appts.js
  interface/main/messages/messages.php
  interface/main/messages/save.php
  interface/patient_tracker/patient_tracker.php
  library/MedEx/API.php
  library/MedEx/MedEx.php
Labels: Status: Needs Review, Status: Needs Work

#2497 Use nation notes templates in any encounter text box.
  config/config.yaml
  interface/main/tabs/main.php
  interface/patient_file/encounter/load_form.php
  interface/patient_file/encounter/view_form.php
  library/ajax/phpvars_to_js.php
  library/ajax/template_context_search.php
  library/custom_template/custom_template.php
  library/dialog.js
  library/js/CustomTemplateApi.js
  library/js/CustomTemplateLoader.js
  library/js/ajax_functions_writer.js
Labels: Status: Needs Review, Status: Needs Work

#2521 composer require pear/archive_tar to update backup script
  composer.json
  composer.lock
  interface/main/backup.php
Labels: Status: Needs Review
