Repository openemr/openemr, pull requests merged in 2019-07, with the labels that each got.

#2524 Fixed session/cookie bug and other related work
  ccdaservice/ccda_gateway.php
  interface/globals.php
  interface/login/login.php
  interface/modules/zend_modules/module/Installer/config/module.config.php
  library/restoreSession.php
Labels: Status: Needs Review

#2523 UX - Expandable Search Patient By Any Demographics - Take 3
  interface/main/finder/dynamic_finder.php
  interface/main/tabs/js/user_data_view_model.js
  interface/main/tabs/main.php
  interface/main/tabs/templates/patient_data_template.php
  interface/themes/buttons/_manilla.scss
  interface/themes/color_base.scss
  interface/themes/oe-common/main-common.scss
  interface/themes/rtl.scss
  interface/themes/style_light.scss
  interface/themes/style_manila.scss
  interface/themes/tabs_style_compact.css
  interface/themes/tabs_style_full.css
  library/globals.inc.php
  src/OeUI/OemrUI.php
Labels: Status: Ready for Integration

#2528 optimizing session/cookies
  _rest_config.php
  ccdaservice/ccda_gateway.php
  ccr/createCCR.php
  composer.json
  interface/globals.php
  interface/login/login.php
  interface/main/main_screen.php
  library/auth.inc
  portal/_header.php
  portal/account/account.php
  portal/account/register.php
  portal/add_edit_event_user.php
  portal/find_appt_popup_user.php
  portal/get_patient_info.php
  portal/home.php
  portal/index.php
  portal/lib/doc_lib.php
  portal/lib/paylib.php
  portal/logout.php
  portal/messaging/handle_note.php
  portal/messaging/messages.php
  portal/messaging/secure_chat.php
  portal/patient/_machine_config.php
  portal/patient/fwk/libs/verysimple/Authentication/Authenticator.php
  portal/patient/fwk/libs/verysimple/HTTP/Context.php
  portal/portal_payment.php
  portal/report/pat_ledger.php
  portal/report/portal_custom_report.php
  portal/report/portal_patient_report.php
  portal/sign/lib/save-signature.php
  portal/sign/lib/show-signature.php
  portal/verify_session.php
  src/Common/Session/SessionUtil.php
  tests/unit/BaseHarness.class.php
Labels: Status: Needs Review

#2532 OeUI class added to some files
  interface/billing/sl_eob_search.php
  interface/forms/fee_sheet/new.php
  interface/forms/misc_billing_options/new.php
  interface/forms/newpatient/common.php
  interface/forms/procedure_order/new.php
  interface/main/messages/messages.php
Labels: Status: Needs Review

#2531 Payment method report fix
  interface/reports/receipts_by_method_report.php
Labels: Status: Needs Review

#2539 Implementation of events and hooks for patient filtering and dynamic global settings
  interface/main/calendar/modules/PostCalendar/pnuserapi.php
  interface/main/finder/dynamic_finder_ajax.php
  interface/main/finder/patient_select.php
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/demographics_full.php
  library/appointments.inc.php
  library/globals.inc.php
  package-lock.json
  src/Events/AbsctactBoundFilterEvent.php
  src/Events/Appointments/AppointmentsFilterEvent.php
  src/Events/Appointments/CalendarFilterEvent.php
  src/Events/BoundFilter.php
  src/Events/Globals/GlobalsInitializedEvent.php
  src/Events/PatientDemographics/UpdateEvent.php
  src/Events/PatientDemographics/ViewEvent.php
  src/Events/PatientFinder/ColumnFilter.php
  src/Events/PatientFinder/PatientFinderFilterEvent.php
  src/Events/PatientSelect/PatientSelectFilterEvent.php
  src/Services/Globals/GlobalSetting.php
  src/Services/Globals/GlobalsService.php
  tests/eventdispatcher/PatientFilterEventHookTest/Module.php
  tests/eventdispatcher/PatientFilterEventHookTest/README
  tests/eventdispatcher/PatientFilterEventHookTest/autoload_classmap.php
  tests/eventdispatcher/PatientFilterEventHookTest/composer.json
  tests/eventdispatcher/PatientFilterEventHookTest/config/blacklist.php
  tests/eventdispatcher/PatientFilterEventHookTest/config/module.config.php
  tests/eventdispatcher/PatientFilterEventHookTest/info.txt
Labels: Status: Needs Review, Status: Needs Work

#2551 refresh fix for issue #2530
  interface/main/tabs/js/user_data_view_model.js
  interface/main/tabs/main.php
  library/auth.inc
  library/globals.inc.php
  version.php
Labels: Status: Needs Review, Status: Needs Work

#2563 Fixes #2562
  interface/reports/ippf_cyp_report.php
Labels: Status: Needs Review

#2565 Fix #2564 - Remove duplicate menu entries
  interface/main/tabs/menu/menus/standard.json
  sites/default/documents/custom_menus/Custom.json
Labels: Status: Needs Review, Status: Needs Work

#2536 Signed-off-by: Sherwin Gaddis <sherwingaddis@gmail.com>
  interface/main/tabs/menu/menus/standard.json
  interface/reports/collections_report.php
Labels: Status: Needs Review

#2569 Delete Addr. Book from Miscellaneous menu
  interface/main/tabs/menu/menus/standard.json
  sites/default/documents/custom_menus/Custom.json
Labels: Status: Needs Review, Status: Ready for Integration, Status: Reviewed

#2573 Add a unique id for the installation
  composer.json
  composer.lock
  interface/super/edit_globals.php
  library/globals.inc.php
  version.php
Labels: Status: Needs Review

#2576 5.0.2_Eye_1
  interface/forms/eye_mag/SpectacleRx.php
  interface/forms/eye_mag/a_issue.php
  interface/forms/eye_mag/css/style.css
  interface/forms/eye_mag/js/canvasdraw.js
  interface/forms/eye_mag/js/eye_base.php
  interface/forms/eye_mag/js/shorthand_eye.js
  interface/forms/eye_mag/php/Anything_simple.php
  interface/forms/eye_mag/php/eye_mag_functions.php
  interface/forms/eye_mag/php/taskman_functions.php
  interface/forms/eye_mag/report.php
  interface/forms/eye_mag/save.php
  interface/forms/eye_mag/taskman.php
  interface/forms/eye_mag/view.php
  interface/forms/newpatient/common.php
  library/clinical_rules.php
  sql/5_0_1-to-5_0_2_upgrade.sql
  sql/database.sql
  version.php
Labels: Priority: Blocking

#2583 Fix box 17 qualifier check
  src/Billing/X12_5010_837P.php
Labels: Status: Needs Review

#2585 Billing Manager Update
  interface/billing/billing_process.php
  interface/billing/billing_report.php
Labels: Status: Needs Review
