Repository openemr/openemr, pull requests merged in 2020-02, with the labels that each got.

#2906 Fix #2904 undefined method in chart traker entity
  src/Entities/ChartTracker.php
  tests/Tests/Unit/Entity/ChartTrackerTest.php
Labels: Status: Needs Review

#2930 Bug fix. Skip 2301C if billing facility and service facility are the…
  src/Billing/X12_5010_837P.php
Labels: Status: Ready for Integration

#2911 easipro
  interface/easipro/pro.php
  interface/main/tabs/menu/menus/patient_menus/standard.json
  library/ajax/easipro_util.php
  library/globals.inc.php
  portal/get_pro.php
  portal/home.php
  sites/default/documents/custom_menus/patient_menus/Custom.json
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  src/Easipro/Easipro.php
  version.php
Labels: Status: Needs Review

#2922 Update ACL and SQL for modules using CLI
  interface/modules/zend_modules/module/Installer/Module.php
  interface/modules/zend_modules/module/Installer/config/module.config.php
  interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
  interface/modules/zend_modules/public/index.php
Labels: Status: Ready for Integration

#2963 Issue Fix #2947: Add dark and superhero themes
  public/images/stylesheets/style_dark.png
  public/images/stylesheets/style_superhero.png
Labels: Status: Needs Review, Status: Needs Work

#2964 Fixes search in Global setting section (Highlight)
  interface/super/edit_globals.php
Labels: Status: Needs Review

#2965 Feat: update all theme screenshot
  public/images/stylesheets/style_ash_blue.png
  public/images/stylesheets/style_burgundy.png
  public/images/stylesheets/style_cadmium_yellow.png
  public/images/stylesheets/style_chocolate.png
  public/images/stylesheets/style_cobalt_blue.png
  public/images/stylesheets/style_coral.png
  public/images/stylesheets/style_deep_purple.png
  public/images/stylesheets/style_dune.png
  public/images/stylesheets/style_emerald.png
  public/images/stylesheets/style_forest_green.png
  public/images/stylesheets/style_mauve.png
  public/images/stylesheets/style_mustard_green.png
  public/images/stylesheets/style_olive.png
  public/images/stylesheets/style_pink.png
  public/images/stylesheets/style_powder_blue.png
  public/images/stylesheets/style_red.png
  public/images/stylesheets/style_sienna.png
  public/images/stylesheets/style_tangerine.png
Labels: Status: Needs Review, Status: Needs Work

#2966 Fixes: Close/Cancle button not working in Export/Import Popup
  custom/export_xml.php
  custom/import_xml.php
Labels: Status: Needs Review

#2968 Added: Issue Template (Feature Request and Bug report)
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/security_report.md
Labels: Status: Needs Review, Status: Needs Work

#2978 Issue Fix #2959: Improve language editor UI
  interface/language/lang_constant.php
  interface/language/lang_definition.php
  interface/language/lang_language.php
  interface/language/lang_manage.php
  interface/language/language.php
Labels: Status: Needs Review

#2979 Activate a tab when it's created
  interface/main/tabs/js/tabs_view_model.js
Labels: Status: Needs Review

#2969 added $ to regex
  src/Common/Http/HttpRestRouteHandler.php
Labels: Status: Ready for Integration

#2982 past_date validation added to the patient DOB
  sql/database.sql
Labels: Status: Needs Work

#2991 Added: PR template for github
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Status: Needs Review

#2993 Issue Fix #2989: Form label field alignment issue
  interface/main/messages/messages.php
Labels: Status: Needs Review

#2995 add return to core/header
  interface/patient_file/printed_fee_sheet.php
  src/Core/Header.php
Labels: Status: Ready for Integration

#2988 empty date checks encapsualted
  interface/patient_file/summary/stats.php
  interface/patient_file/transaction/record_request.php
  library/amc.php
  library/clinical_rules.php
  library/patient.inc
  library/sanitize.inc.php
Labels: Status: Needs Review

#2997 tobacco or any given case fixed for input check
  library/patient.inc
Labels: Status: Needs Review

#3019 improved credentials line
  setup.php
Labels: Status: Needs Review

#3020 fixes #3000
  interface/help_modal.php
Labels: jquery-ui removal

#2985 Modal does not appear after closing it once
  interface/new/new_comprehensive.php
  interface/new/new_search_popup.php
Labels: Status: Needs Work

#3022 Fix #3004 change jquery ui tooltip
  interface/billing/sl_eob_search.php
  interface/orders/types.php
  interface/usergroup/adminacl.php
Labels: Status: Needs Review

#3030 Fix #3029 close p tag
  Documentation/help_files/add_edit_transactions_dashboard_help.php
  Documentation/help_files/adminacl_help.php
  Documentation/help_files/cms_1500_help.php
  Documentation/help_files/common_help.php
  Documentation/help_files/configure_orders_help.php
  Documentation/help_files/fee_sheet_help.php
  Documentation/help_files/history_dashboard_help.php
  Documentation/help_files/issues_dashboard_help.php
  Documentation/help_files/ledger_dashboard_help.php
  Documentation/help_files/medical_dashboard_help.php
  Documentation/help_files/message_center_help.php
  Documentation/help_files/mfa_help.php
  Documentation/help_files/openemr_installation_help.php
  Documentation/help_files/openemr_multisite_admin_help.php
  Documentation/help_files/procedure_provider_help.php
  Documentation/help_files/report_dashboard_help.php
  Documentation/help_files/sl_eob_help.php
  Documentation/help_files/transactions_dashboard_help.php
Labels: Status: Needs Review

#3034 Improved UI: Edit Clinical Reminder - Admin
  interface/patient_file/reminder/clinical_reminders.php
Labels: Status: Needs Review

#3039 Fix #3002 change encounter tabs to bootstrap style
  interface/patient_file/encounter/forms.php
Labels: Status: Needs Review

#3035 Fixed patient encounter gui
  interface/patient_file/encounter/forms.php
Labels: Status: Needs Review
