Repository openemr/openemr, pull requests merged in 2020-06, with the labels that each got.

#3591 expand encounter forms by default
  library/globals.inc.php
  version.php
Labels: Status: Needs Review

#3593 And then there was only one (portal)
  Documentation/privileged_db/example_user_permissions.sql
  interface/cmsportal/history_form.php
  interface/cmsportal/insurance_form.php
  interface/cmsportal/issue_form.php
  interface/cmsportal/lbf_form.php
  interface/cmsportal/list_requests.php
  interface/cmsportal/patient_form.php
  interface/cmsportal/patient_form_ajax.php
  interface/cmsportal/patient_select.php
  interface/cmsportal/portal.inc.php
  interface/cmsportal/upload_form.php
  interface/cmsportal/upload_form_show.php
  interface/forms/LBF/new.php
  interface/main/messages/messages.php
  interface/main/tabs/menu/menus/standard.json
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  interface/orders/single_order_results.inc.php
  interface/patient_file/report/custom_report.php
  interface/patient_file/report/patient_report.php
  interface/patient_file/summary/create_portallogin.php
  interface/patient_file/summary/dashboard_header.php
  interface/patient_file/summary/pnotes_fragment.php
  interface/patient_file/summary/pnotes_full.php
  interface/super/edit_globals.php
  library/ajax/offsite_portal_ajax.php
  library/classes/rulesets/Amc/reports/AMC_314g_1_2_14_STG2/Numerator.php
  library/globals.inc.php
  myportal/index.php
  myportal/soap_service/factory_class.php
  myportal/soap_service/portal_connectivity.php
  myportal/soap_service/server_audit.php
  myportal/soap_service/server_existingpatient.php
  myportal/soap_service/server_mail.php
  myportal/soap_service/server_med_rec.php
  myportal/soap_service/server_newpatient.php
  myportal/soap_service/server_newpatienttoapprove.php
  myportal/soap_service/server_oemruser.php
  myportal/soap_service/server_side.php
  portal/report/portal_custom_report.php
  portal/report/portal_patient_report.php
  sites/default/documents/custom_menus/Custom.json
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#3596 Feat #3595: Multi site administration and database
  admin.php
  sql_upgrade.php
Labels: Status: Needs Review, Status: Needs Work

#3604 CCDA creation mechanism update
  ccdaservice/README.md
  docker-compose.yml
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Form/ModuleconfigForm.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/Configuration.php
  library/globals.inc.php
Labels: Status: Needs Review

#3520 Adding the ability to delete a drug from patient chart
  library/deletedrug.php
  templates/prescription/general_list.html
Labels: Status: Needs Review, Status: Needs Work

#3589 feat: add the bootstrap style and remove outdated code
  interface/patient_file/encounter/find_code_dynamic.php
Labels: Status: Needs Review, Status: Reviewed

#3506 Upgrade Encounter Resource
  API_README.md
  FHIR_README.md
  _rest_config.php
  _rest_routes.inc.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  src/Common/Uuid/UuidRegistry.php
  src/RestControllers/EncounterRestController.php
  src/RestControllers/FHIR/FhirEncounterRestController.php
  src/RestControllers/FHIR/FhirPatientRestController.php
  src/RestControllers/PatientRestController.php
  src/Services/BaseService.php
  src/Services/EncounterService.php
  src/Services/FHIR/FhirEncounterService.php
  src/Services/PatientService.php
  src/Validators/BaseValidator.php
  src/Validators/EncounterValidator.php
  tests/Tests/Api/PatientApiTest.php
  tests/Tests/RestControllers/PatientRestControllerTest.php
  tests/Tests/Services/PatientServiceTest.php
Labels: Status: Needs Review

#2568 Fixed day calendar view to display correct local preference
  interface/main/calendar/add_edit_event.php
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
  interface/patient_file/summary/demographics.php
Labels: Status: Needs Review, Status: Needs Work

#3628 Add Support to Encounter Class UI
  interface/forms/newpatient/common.php
  interface/forms/newpatient/save.php
Labels: Status: Needs Review

#3629 v5.0.2 Profile Tuning
  interface/globals.php
  interface/main/tabs/main.php
  interface/patient_file/history/encounters.php
  interface/patient_file/summary/clinical_reminders_fragment.php
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/disc_fragment.php
  interface/patient_file/summary/labdata_fragment.php
  interface/patient_file/summary/lbf_fragment.php
  interface/patient_file/summary/patient_reminders_fragment.php
  interface/patient_file/summary/pnotes_fragment.php
  interface/patient_file/summary/pnotes_full.php
  interface/patient_file/summary/stats.php
  interface/patient_file/summary/vitals_fragment.php
  library/clinical_rules.php
  library/pid.inc
  src/Common/Session/SessionUtil.php
Labels: Status: Needs Review

#3630 Refactor #3603: refine ippf_upgrade page
  ippf_upgrade.php
Labels: Status: Needs Review

#3602 Refactor: remove outdated font tag
  ippf_upgrade.php
  library/sql_upgrade_fx.php
Labels: Status: Needs Review, Status: Needs Work

#3642 Modernize options_listadd.inc (#3632)
  library/options_listadd.inc
Labels: Status: Needs Review

#3638 updates to registration
  contrib/util/docker/docker-compose.yml
  docker-compose.yml
  interface/globals.php
  interface/main/about_page.php
  interface/main/exceptions/invalid_email_exception.php
  interface/product_registration/exceptions/duplicate_registration_exception.php
  interface/product_registration/product_registration_controller.js
  interface/product_registration/product_registration_controller.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Entities/ProductRegistration.php
  src/Repositories/ProductRegistrationRepository.php
  src/Services/ProductRegistrationService.php
  version.php
Labels: Status: Needs Review

#3646 Add portal flag and supervisor to users
  interface/forms/fee_sheet/new.php
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin.php
  interface/usergroup/usergroup_admin_add.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review, Status: Reviewed

#3649 fixes to remove warnings as browsers start to crack down on missing SameSite attributes
  interface/login/login.php
  src/Common/Session/SessionUtil.php
Labels: Status: Needs Review

#3626 First impression, update the look of the landing page
  interface/themes/colors/openemr5/login.scss
  interface/themes/login_page.scss
Labels: Status: Ready for Integration, Status: Reviewed

#3658 Login Page Overhaul (#3654)
  interface/globals.php
  interface/login/login.php
  interface/themes/ajax_calendar_sass.scss
  interface/themes/color_base.scss
  interface/themes/colors/openemr5/login.scss
  interface/themes/colors/style_ash_blue.scss
  interface/themes/colors/style_burgundy.scss
  interface/themes/colors/style_cadmium_yellow.scss
  interface/themes/colors/style_chocolate.scss
  interface/themes/colors/style_cobalt_blue.scss
  interface/themes/colors/style_coral.scss
  interface/themes/colors/style_deep_purple.scss
  interface/themes/colors/style_dune.scss
  interface/themes/colors/style_emerald.scss
  interface/themes/colors/style_forest_green.scss
  interface/themes/colors/style_mauve.scss
  interface/themes/colors/style_mustard_green.scss
  interface/themes/colors/style_olive.scss
  interface/themes/colors/style_pink.scss
  interface/themes/colors/style_powder_blue.scss
  interface/themes/colors/style_red.scss
  interface/themes/colors/style_sienna.scss
  interface/themes/colors/style_tangerine.scss
  interface/themes/colors/utilities/batch-payments.scss
  interface/themes/colors/utilities/bootstrap-nav-menu.scss
  interface/themes/colors/utilities/bootstrap.scss
  interface/themes/colors/utilities/codes.scss
  interface/themes/colors/utilities/default_variables.scss
  interface/themes/colors/utilities/edit_globals_colors.scss
  interface/themes/colors/utilities/external-data.scss
  interface/themes/colors/utilities/fee-sheet.scss
  interface/themes/colors/utilities/help-files.scss
  interface/themes/colors/utilities/login.scss
  interface/themes/colors/utilities/recall-flow-board.scss
  interface/themes/colors/utilities/ros.scss
  interface/themes/colors/utilities/tabs-full.scss
  interface/themes/core/closeDlgIframe.scss
  interface/themes/core/cursor.scss
  interface/themes/core/navmenu.scss
  interface/themes/core/text.scss
  interface/themes/core/therapy-groups.scss
  interface/themes/login_page.scss
  interface/themes/navigation-slide/_future-bootstrap.scss
  interface/themes/navigation-slide/_manilla.scss
  interface/themes/oe-styles/style_dark.scss
  interface/themes/oe-styles/style_superhero.scss
  interface/themes/theme-defaults.scss
Labels: Status: Needs Review

#3636 Lots of BS4 Fixes (#3633)
  interface/main/calendar/add_edit_event.php
  interface/main/tabs/js/custom_bindings.js
  interface/main/tabs/js/frame_proxies.js
  interface/main/tabs/js/menu_analysis.js
  interface/main/tabs/js/tabs_view_model.js
  interface/main/tabs/js/user_data_view_model.js
  interface/patient_file/encounter/find_code_dynamic.php
  interface/patient_file/summary/add_edit_issue.php
  interface/patient_file/summary/stats_full.php
  interface/patient_tracker/patient_tracker.php
  interface/themes/core/navmenu.scss
  interface/themes/core/tabs.scss
  interface/themes/oe-styles/style_dark.scss
  interface/themes/oe-styles/style_light.scss
  interface/themes/oe-styles/style_manila.scss
  interface/themes/oe-styles/style_superhero.scss
  interface/themes/tabs_style_full.scss
  interface/themes/theme-defaults.scss
  package.json
  src/Core/Header.php
Labels: Status: Needs Review

#3664 issue #3659 fix
  interface/main/tabs/js/tabs_view_model.js
Labels: Status: Needs Review

#3671 fix broken search icon; TypeError: event.stopImmediatePropagation is not a function
  interface/main/tabs/js/user_data_view_model.js
Labels: Status: Needs Review

#3678 added docker documentation
  DOCKER_README.md
  README.md
  docker/README.md
  docker/docker-compose.yml
Labels: Status: Needs Review

#3676 Added support for uuid to vertical tables
  library/sql_upgrade_fx.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Common/Uuid/UuidRegistry.php
  version.php
Labels: Status: Needs Review

#3650 Refactor: refine the flow board page
  interface/patient_tracker/patient_tracker.php
  interface/themes/core/FontAwesome.scss
Labels: Status: Ready for Integration, Status: Reviewed

#3586 Fix #3007: remove jquery-ui and outdated code part1
  interface/drugs/add_edit_drug.php
  interface/fax/fax_dispatch.php
  interface/forms/LBF/new.php
  interface/forms/eye_mag/SpectacleRx.php
  interface/forms/eye_mag/a_issue.php
  interface/forms/eye_mag/php/eye_mag_functions.php
  interface/themes/oe-bootstrap.scss
Labels: Status: Ready for Integration, Status: Reviewed

#3662 Adding/Upgrading Organization Resource
  _rest_routes.inc.php
  interface/batchcom/batch_phone_notification.php
  interface/login/login.php
  interface/orders/pending_followup.php
  interface/reports/appt_encounter_report.php
  interface/reports/daily_summary_report.php
  interface/reports/ippf_daily.php
  interface/reports/ippf_statistics.php
  interface/usergroup/facilities.php
  library/options.inc.php
  library/patient.inc
  modules/sms_email_reminder/batch_phone_notification.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/RestControllers/FHIR/FhirOrganizationRestController.php
  src/RestControllers/FacilityRestController.php
  src/Services/FHIR/FhirOrganizationService.php
  src/Services/FHIR/FhirPractitionerService.php
  src/Services/FacilityService.php
  src/Validators/FacilityValidator.php
  src/Validators/PractitionerValidator.php
  tests/Tests/Api/FacilityApiTest.php
  tests/Tests/Fixtures/BaseFixtureManager.php
  tests/Tests/Fixtures/FHIR/facility.json
  tests/Tests/Fixtures/FacilityFixtureManager.php
  tests/Tests/Fixtures/facility.json
  tests/Tests/RestControllers/FHIR/FhirOrganizationRestControllerTest.php
  tests/Tests/RestControllers/FacilityRestControllerTest.php
  tests/Tests/Services/FHIR/FhirOrganizationServiceCrudTest.php
  tests/Tests/Services/FacilityServiceTest.php
  version.php
Labels: Status: Needs Review

#3681 Batch Payments and other listed changes
  interface/billing/edit_payment.php
  interface/billing/new_payment.php
  interface/billing/payment_master.inc.php
  interface/billing/payment_pat_sel.inc.php
  interface/billing/search_payments.php
  interface/main/tabs/main.php
  library/dialog.js
  library/payment_jav.inc.php
  src/RestControllers/FHIR/FhirQuestionnaireResponseController.php
  src/Services/FHIR/FhirQuestionnaireResponseService.php
Labels: Status: Needs Work

#3688 travis testing updates
  .travis.yml
  ci/nginx_72/docker-compose.yml
  ci/nginx_73/docker-compose.yml
  ci/nginx_74/docker-compose.yml
  ci/nginx_80/docker-compose.yml
  contrib/util/docker/dockers/dev-php-fpm-8-0-redis/Dockerfile
  contrib/util/docker/dockers/dev-php-fpm-8-0/Dockerfile
Labels: Status: Needs Work

#3667 update immunizations table with codes from CDC
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/cvx_codes.sql
  version.php
Labels: Status: Needs Review, Status: Needs Work

#3677 add hex-blob setting to mysqldump in backup.php
  interface/main/backup.php
Labels: Status: Needs Review, Status: Needs Work

#3697 set codetype on update, fix pagination in admin->codes
  interface/patient_file/encounter/superbill_custom_full.php
  sql/5_0_2-to-6_0_0_upgrade.sql
Labels: Status: Needs Review
