Repository openemr/openemr, pull requests merged in 2020-08, with the labels that each got.

#3793 Create Central Style Folder (#3792)
  gulpfile.js
  interface/billing/edih_view.php
  interface/globals.php
  interface/patient_file/history/encounters.php
  interface/patient_file/summary/labdata.php
  interface/patient_tracker/patient_tracker.php
  interface/super/rules/base/template/basic.php
  interface/super/rules/www/css/jQuery.autocomplete.css
  interface/super/rules/www/css/rules.css
  interface/themes/misc/bootstrap_navbar.scss
  interface/themes/misc/edi_history_v2.scss
  interface/themes/misc/encounters.scss
  interface/themes/misc/labdata.scss
  interface/themes/misc/rules.scss
  library/css/encounters.css
Labels: Status: Ready for Integration, Status: Reviewed

#3784 Updated Procedure Resource
  API_README.md
  FHIR_README.md
  _rest_routes.inc.php
  library/sql_upgrade_fx.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/RestControllers/FHIR/FhirProcedureRestController.php
  src/RestControllers/ProcedureRestController.php
  src/Services/AllergyIntoleranceService.php
  src/Services/BaseService.php
  src/Services/ConditionService.php
  src/Services/EncounterService.php
  src/Services/FHIR/FhirProcedureService.php
  src/Services/FacilityService.php
  src/Services/ImmunizationService.php
  src/Services/PractitionerRoleService.php
  src/Services/PractitionerService.php
  src/Services/ProcedureService.php
Labels: Status: Needs Review, Status: Needs Work

#3811 couple drug name fixes
  library/ajax/prescription_drugname_lookup.php
  library/deletedrug.php
  templates/prescription/general_edit.html
  templates/prescription/general_list.html
  templates/prescription/general_lookup.html
Labels: Status: Needs Review

#3790 Upgraded Medication Resource
  API_README.md
  FHIR_README.md
  _rest_routes.inc.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/RestControllers/DrugRestController.php
  src/RestControllers/FHIR/FhirMedicationRestController.php
  src/Services/AllergyIntoleranceService.php
  src/Services/BaseService.php
  src/Services/ConditionService.php
  src/Services/DrugService.php
  src/Services/FHIR/FhirMedicationService.php
Labels: Status: Needs Work

#3823 refactor: refine the patient records request.
  interface/patient_file/transaction/record_request.php
Labels: Status: Needs Review

#3827 add support for encrypting documents stored on couchdb
  controllers/C_Document.class.php
  library/classes/CouchDB.class.php
  library/classes/Document.class.php
  library/globals.inc.php
  src/Common/ORDataObject/ORDataObject.php
  version.php
Labels: Status: Needs Review

#3787 Refactor #3779: remove outdated code, and add the bootstrap form style.
  interface/patient_file/history/history.php
  interface/patient_file/history/history_full.php
  library/options.inc.php
Labels: Status: Ready for Integration, Status: Reviewed

#3794 Update All Dependencies
  config/config.yaml
  interface/modules/zend_modules/module/Multipledb/src/Multipledb/Controller/BaseController.php
  package-lock.json
  package.json
Labels: Status: Needs Review, Status: Needs Work, dependencies

#3732 Fix medex navbar overflow
  library/MedEx/API.php
Labels: Status: Ready for Integration, Status: Reviewed

#3837 Update BS4 to 4.5.2 and Regen Package Lock
  package-lock.json
  package.json
Labels: Status: Ready for Integration, Status: Reviewed

#3798 Feat: add the bootstrap input style in dashboard documents.
  templates/documents/general_list.html
  templates/documents/general_upload.html
Labels: Status: Ready for Integration, Status: Reviewed

#3833 obfuscate sensitive fields in edit globals ui
  interface/super/edit_globals.php
Labels: Status: Needs Review

#3822 Refactor #3817: refine past encounters and documents.
  interface/billing/sl_eob_invoice.php
  interface/patient_file/history/edit_billnote.php
  interface/patient_file/history/encounters.php
Labels: Status: Ready for Integration, Status: Reviewed

#3809 Add support for special sql in module install script
  interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
Labels: Status: Needs Review

#3832 couchdb updates
  ccr/display.php
  composer.json
  composer.lock
  controllers/C_Document.class.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
  interface/modules/zend_modules/module/Documents/src/Documents/Plugin/Documents.php
  interface/patient_file/deleter.php
  interface/super/edit_globals.php
  library/ajax/ccr_import_ajax.php
  library/classes/CouchDB.class.php
  library/classes/Document.class.php
  library/classes/thumbnail/ThumbnailGenerator.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Common/Uuid/UuidRegistry.php
  version.php
Labels: Status: Needs Review

#3826 Refactor: refine the encounter delete form page and modal.
  interface/patient_file/deleter.php
  interface/patient_file/encounter/delete_form.php
  interface/patient_file/encounter/forms.php
Labels: Status: Needs Work, Status: Reviewed

#3846 added uuid mapping mechanism
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Common/Uuid/UuidMapping.php
  src/Common/Uuid/UuidRegistry.php
  version.php
Labels: Status: Needs Review

#3851 Fix #3842: fix the recall board disappear when click the arrow button.
  library/MedEx/API.php
Labels: Status: Needs Review

#3829 All New FHIR Location Resource
  API_README.md
  FHIR_README.md
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirLocationRestController.php
  src/Services/FHIR/FhirLocationService.php
  src/Services/LocationService.php
Labels: Status: Needs Review

#3854 Immunization and other
  interface/patient_file/summary/demographics.php
  interface/reports/immunization_report.php
  library/dialog.js
  src/Billing/EDI270.php
Labels: Status: Needs Review

#3815 js html escaping
  interface/billing/billing_report.php
  interface/easipro/pro.php
  interface/login/login.php
  interface/patient_file/report/custom_report.js
  interface/patient_file/report/custom_report.php
  interface/super/edit_layout.php
  library/js/utility.js
  portal/home.php
  portal/report/portal_custom_report.php
Labels: Status: Needs Review

#3821 Added Endpoints for Prescription/MedicationRequest Resource
  API_README.md
  FHIR_README.md
  _rest_routes.inc.php
  interface/billing/sl_receipts_report.php
  interface/drugs/add_edit_drug.php
  interface/patient_file/encounter/find_code_dynamic.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/RestControllers/FHIR/FhirMedicationRequestRestController.php
  src/RestControllers/FHIR/FhirMedicationStatementRestController.php
  src/RestControllers/PrescriptionRestController.php
  src/Services/DrugService.php
  src/Services/FHIR/FhirMedicationRequestService.php
  src/Services/FHIR/FhirMedicationService.php
  src/Services/FHIR/FhirMedicationStatementService.php
  src/Services/FHIR/FhirProcedureService.php
  src/Services/PrescriptionService.php
Labels: Status: Needs Review

#3865 fix sql error row size too big
  interface/forms/bronchitis/table.sql
  sql/5_0_2-to-6_0_0_upgrade.sql
  version.php
Labels: Status: Needs Review

#3867 Observation Lab [US Core Profile]
  FHIR_README.md
  _rest_routes.inc.php
  interface/orders/types_edit.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/RestControllers/FHIR/FhirObservationRestController.php
  src/Services/FHIR/FhirObservationService.php
  src/Services/ObservationLabService.php
Labels: Status: Needs Review

#3856 refactor: refine the procedure order on summary page.
  interface/orders/order_manifest.php
  interface/orders/single_order_results.inc.php
Labels: Status: Ready for Integration, Status: Reviewed

#3764 Refactor #3267: refine the lab page
  interface/patient_file/summary/labdata.php
Labels: Status: Ready for Integration, Status: Reviewed

#3766 Improve code selection usability in Add/Edit Issue dialog
  .gitignore
  interface/patient_file/encounter/select_codes.php
  interface/patient_file/summary/add_edit_issue.php
Labels: Status: Needs Review, Status: Needs Work

#3739 Fix #3695: refine the MedEx setup and register page
  library/MedEx/API.php
Labels: Status: Ready for Integration, Status: Reviewed

#3830 Refactor: refine the import section page.
  interface/patient_file/ccr_import.php
  interface/patient_file/ccr_pending_approval.php
Labels: Status: Ready for Integration, Status: Reviewed

#3756 Fix Login Page (#3742)
  interface/globals.php
  interface/login/login.php
  interface/themes/login_page.scss
  library/globals.inc.php
Labels: Status: Needs Review

#3883 add monitor portainer link to insane doc
  contrib/util/docker/README.md
Labels: Status: Needs Review, Status: Needs Work

#3878 Make Title column a hyperlink
  interface/patient_file/summary/stats_full.php
Labels: Status: Ready for Integration, Status: Reviewed

#3839 Death of Superhero, Removal of Theme Builder, and Addition of New Themes
  gulpfile.js
  interface/forms/eye_mag/a_issue.php
  interface/forms/eye_mag/view.php
  interface/login/login.php
  interface/main/messages/messages.php
  interface/main/tabs/main.php
  interface/patient_tracker/patient_tracker.php
  interface/themes/ajax_calendar_sass.scss
  interface/themes/color_base.scss
  interface/themes/colors/utilities/bootstrap-nav-menu.scss
  interface/themes/colors/utilities/bootstrap.scss
  interface/themes/colors/utilities/default_variables.scss
  interface/themes/colors/utilities/edit_globals_colors.scss
  interface/themes/colors/utilities/recall-flow-board.scss
  interface/themes/colors/utilities/tabs-full.scss
  interface/themes/compact-theme-defaults.scss
  interface/themes/core.scss
  interface/themes/oe-bootstrap.scss
  interface/themes/oe-styles/style_manila.scss
  interface/themes/oe-styles/style_solar.scss
  interface/themes/tabs_style_full.scss
  interface/themes/themeBuilder.php
  library/globals.inc.php
  package-lock.json
  package.json
  sql/5_0_2-to-6_0_0_upgrade.sql
  src/Core/Header.php
Labels: Status: Needs Review

#3895 feat: convert the strike tag to s tag.
  interface/forms/fee_sheet/new.php
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/outlook_ajax_template.html
  interface/orders/list_reports.php
Labels: Status: Ready for Integration, Status: Reviewed

#3873 Refactor: remove unnecessary oe classes.
  interface/README.md
  interface/billing/billing_report.php
  interface/billing/new_payment.php
  interface/billing/payment_master.inc.php
  interface/billing/sl_eob_invoice.php
  interface/billing/sl_eob_patient_note.php
  interface/forms/care_plan/new.php
  interface/forms/clinical_instructions/new.php
  interface/forms/dictation/new.php
  interface/forms/dictation/view.php
  interface/forms/fee_sheet/new.php
  interface/forms/functional_cognitive_status/new.php
  interface/forms/misc_billing_options/new.php
  interface/forms/newGroupEncounter/common.php
  interface/forms/newpatient/common.php
  interface/forms/observation/new.php
  interface/forms/procedure_order/new.php
  interface/forms/reviewofs/new.php
  interface/forms/reviewofs/view.php
  interface/forms/ros/templates/ros/general_new.html
  interface/forms/soap/templates/general_new.html
  interface/forms/vitals/templates/vitals/general_new.html
  interface/main/dated_reminders/dated_reminders_add.php
  interface/main/dated_reminders/dated_reminders_log.php
  interface/main/messages/messages.php
  interface/orders/procedure_provider_edit.php
  interface/orders/types.php
  interface/orders/types_edit.php
  interface/patient_file/front_payment.php
  interface/patient_file/pos_checkout.php
  interface/patient_file/summary/add_edit_issue.php
  interface/patient_file/summary/dashboard_header.php
  interface/patient_tracker/patient_tracker_status.php
  interface/themes/colors/utilities/bootstrap.scss
  interface/themes/core/text.scss
  interface/themes/rtl_style_pdf.css
  interface/usergroup/adminacl.php
  interface/usergroup/facility_user_admin.php
  interface/usergroup/mfa_totp.php
  interface/usergroup/mfa_u2f.php
Labels: Status: Ready for Integration, Status: Reviewed

#3897 Added Events and hooks for create and update facilities and users
  interface/usergroup/usergroup_admin.php
  src/Events/Facility/FacilityCreatedEvent.php
  src/Events/Facility/FacilityUpdatedEvent.php
  src/Events/User/UserCreatedEvent.php
  src/Events/User/UserUpdatedEvent.php
  src/Services/FacilityService.php
Labels: Status: Needs Review, Status: Needs Work

#3825 Refactor: refine all of the patient visit forms.
  interface/forms/care_plan/new.php
  interface/forms/clinical_instructions/new.php
  interface/forms/dictation/new.php
  interface/forms/functional_cognitive_status/new.php
  interface/forms/misc_billing_options/new.php
  interface/forms/observation/new.php
  interface/forms/reviewofs/new.php
  interface/forms/ros/templates/ros/general_new.html
  interface/forms/soap/templates/general_new.html
  interface/forms/vitals/templates/vitals/general_new.html
  interface/patient_file/encounter/find_code_popup.php
Labels: Status: Needs Review, Status: Needs Work
