Repository openemr/openemr, pull requests merged in 2020-04, with the labels that each got.

#3249 Fixed-alignment
  interface/orders/procedure_stats.php
Labels: Status: Needs Review, Status: Needs Work

#3298 Resource Refactor/Separation [FHIR]
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirEncounterRestController.php
  src/RestControllers/FHIR/FhirOrganizationRestController.php
  src/RestControllers/FHIR/FhirPatientRestController.php
  src/RestControllers/FHIR/FhirQuestionnaireResponseController.php
  src/Services/FHIR/FhirEncounterService.php
  src/Services/FHIR/FhirOrganizationService.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/FHIR/FhirPractitionerService.php
  src/Services/FHIR/FhirQuestionnaireResponseService.php
  src/Services/FHIR/FhirResourcesService.php
  src/Services/FHIR/FhirValidationService.php
  src/Services/FhirResourcesService.php
Labels: Status: Needs Review

#3295 Organization Resource getOne method
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirOrganizationRestController.php
  src/Services/FHIR/FhirOrganizationService.php
Labels: Status: Needs Review

#3316 Fix #3003 clickmap remove jquery ui
  interface/clickmap/template/general_new.html
  library/js/clickmap.js
Labels: Status: Needs Review

#3323 fix #3309: duplicate summary tabs and background color
  interface/clickmap/template/css/clickmap.css
  interface/clickmap/template/general_new.html
Labels: Status: Needs Review, Status: Needs Work

#3318 Option - show only one insurance
  interface/new/new_comprehensive.php
  interface/new/new_comprehensive_save.php
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/demographics_full.php
  interface/patient_file/summary/demographics_save.php
  library/globals.inc.php
Labels: Status: Needs Work

#3328 Fix: remove report.css a tag style.
  interface/forms/eye_mag/css/report.css
Labels: Status: Needs Review

#3335 New services base class
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirPatientRestController.php
  src/Services/BaseService.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/FacilityService.php
  src/Services/PatientService.php
Labels: Status: Needs Review

#3325 Suggestion : Adding ss to the patient_data API
  src/Services/PatientService.php
Labels: Status: Needs Review

#3334 AllergyIntolerance Resource & GET methods FHIR
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirAllergyIntoleranceRestController.php
  src/Services/FHIR/FhirAllergyIntoleranceService.php
Labels: Status: Needs Review

#3180 Using PSR4 in ORDataObject
  contrib/forms/evaluation/FormEvaluation.class.php
  contrib/forms/hand/FormHand.class.php
  contrib/forms/hp_tje_primary/FormHpTjePrimary.class.php
  contrib/forms/hpi/FormHPI.class.php
  contrib/forms/leg_length/FormLegLength.class.php
  contrib/forms/nursing_notes/FormNursingNotes.class.php
  contrib/forms/prior_auth/FormPriorAuth.class.php
  contrib/forms/prosthesis/FormProsthesis.class.php
  contrib/forms/review_of_systems/FormReviewOfSystems.class.php
  contrib/forms/rom/FormROM.class.php
  contrib/forms/ros2/FormROS2.class.php
  contrib/forms/snellen/FormSnellen.class.php
  contrib/forms/soap2/FormSOAP.class.php
  interface/clickmap/AbstractClickmapModel.php
  interface/forms/prior_auth/FormPriorAuth.class.php
  interface/forms/ros/FormROS.class.php
  interface/forms/soap/FormSOAP.class.php
  interface/forms/vitals/FormVitals.class.php
  library/classes/Address.class.php
  library/classes/Company.class.php
  library/classes/Document.class.php
  library/classes/InsuranceCompany.class.php
  library/classes/InsuranceNumbers.class.php
  library/classes/Note.class.php
  library/classes/Patient.class.php
  library/classes/Pharmacy.class.php
  library/classes/PhoneNumber.class.php
  library/classes/Prescription.class.php
  library/classes/Provider.class.php
  library/classes/X12Partner.class.php
  src/Common/ORDataObject/ORDataObject.php
Labels: Status: Needs Review, Status: Needs Work

#3331 [SQL]: Converting tinyint to smallint to store large values
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review, Status: Needs Work

#3303 Fix #3279 warning closing form
  interface/forms/soap/templates/general_new.html
  src/Tabs/TabsWrapper.php
Labels: Status: Needs Work, Status: Ready for Integration

#3321 Add turn API on variable to docker environment
  docker-compose.yml
Labels: Status: Needs Work, Status: Reviewed

#3343 Module Manager Updates
  interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
  interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
  interface/modules/zend_modules/module/Installer/view/installer/installer/configure.phtml
  interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
  interface/modules/zend_modules/public/js/installer/action.js
Labels: Status: Reviewed

#3306 Fixed Validation in API
  src/RestControllers/PatientRestController.php
  src/RestControllers/RestControllerHelper.php
  src/Services/BaseService.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/PatientService.php
Labels: Status: Needs Review, Status: Reviewed

#3351 dialog enhancements
  library/dialog.js
  library/js/utility.js
  phpfhir/libs/controller/ClientAppController.php
  portal/add_edit_event_user.php
  portal/home.php
  portal/report/portal_custom_report.php
  portal/report/portal_patient_report.php
Labels: Status: Needs Review

#3355 [SQL]: Fix #3332 using null instead of blank
  sql/database.sql
Labels: Status: Needs Review

#3360 Create FHIR API guide
  FHIR_README.md
Labels: Status: Needs Review, Status: Needs Work

#3356 Immunization Resource with GET method
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirImmunizationRestController.php
  src/Services/FHIR/FhirAllergyIntoleranceService.php
  src/Services/FHIR/FhirImmunizationService.php
Labels: Status: Needs Review

#3372 [SQL]: Fix #3365 #3367 fix codes table
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/cvx_codes.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review, Status: Needs Work

#3371 Fix #3341: Add the Bootstrap style in available appointments
  interface/main/calendar/find_appt_popup.php
Labels: Status: Needs Review

#3319 multiple fee-sheet issue
  src/Tabs/TabsWrapper.php
Labels: Status: Needs Review, Status: Needs Work

#3379 FHIR Condition Resource
  FHIR_README.md
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirConditionRestController.php
  src/Services/FHIR/FhirConditionService.php
Labels: Status: Needs Review

#3240 Fixes Navbar Brokenness
  interface/main/tabs/main.php
  interface/main/tabs/templates/menu_template.php
  interface/main/tabs/templates/user_data_template.php
  interface/themes/tabs_style_compact.css
  interface/themes/tabs_style_full.css
  interface/themes/theme-defaults.scss
  public/images/menu-logo.svg
Labels: Status: Needs Review

#3385 Patient Service Enhancements for Richer OpenEMR and FHIR R4 Responses
  API_README.md
  FHIR_README.md
  src/RestControllers/PatientRestController.php
  src/RestControllers/RestControllerHelper.php
  src/Services/PatientService.php
Labels: Status: Needs Review

#3400 fix #2892: form inner scrollbar
  interface/patient_file/history/encounters.php
Labels: Status: Needs Review

#3404 Fix #3383 encounter summary dropdown
  interface/patient_file/encounter/forms.php
Labels: Status: Ready for Integration

#3185 Feature : Open Existing Tab
  interface/main/tabs/js/tabs_view_model.js
Labels: Status: Needs Review, Status: Needs Work

#3420 Update NPM and Composer
  composer.lock
  package-lock.json
  package.json
Labels: Status: Needs Review

#3422 [WIP] php 8 fun fix
  controllers/C_Document.class.php
  custom/code_types.inc.php
  custom/qrda_functions.php
  interface/billing/ub04_dispose.php
  interface/eRx_xml.php
  interface/forms/CAMOS/content_parser.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  library/clinical_rules.php
  portal/lib/appsql.class.php
  portal/lib/portal_mail.inc
  portal/lib/portal_pnotes.inc
  src/Billing/BillingUtilities.php
  src/Billing/EDI_270.php
Labels: Status: Needs Review

#3424 time to remove skip_english_translation, not in globals anymore
  interface/language/lang_definition.php
  interface/login/login.php
  interface/super/edit_list.php
  library/options.inc.php
  library/translation.inc.php
  portal/account/register.php
  portal/index.php
Labels: Status: Ready for Integration, Status: Reviewed

#3415 Adding Test Fixtures For Unit/Api Tests
  .travis.yml
  ci/nginx_72/docker-compose.yml
  ci/nginx_73/docker-compose.yml
  ci/nginx_74/docker-compose.yml
  ci/nginx_80/docker-compose.yml
  composer.json
  phpunit.xml
  tests/Tests/E2e/TestOpenemrPage/ExampleE2eTest.php
  tests/Tests/Fixture/FixtureManager.php
  tests/Tests/Fixture/FixtureManagerTest.php
  tests/Tests/Fixture/patients.json
  tests/Tests/README.md
  tests/Tests/Service/PatientServiceTest.php
  tests/bootstrap.php
Labels: Status: Needs Review, Status: Needs Work

#3428 Query error
  interface/forms/observation/new.php
Labels: Status: Needs Review, Status: Needs Work

#3434 move src/Billing to PSR12
  interface/billing/billing_process.php
  interface/billing/billing_report.php
  interface/billing/edi_270.php
  interface/billing/edi_271.php
  interface/billing/era_payments.php
  interface/billing/sl_eob_invoice.php
  interface/billing/sl_eob_process.php
  interface/billing/sl_eob_search.php
  interface/billing/ub04_dispose.php
  interface/patient_file/history/encounters.php
  interface/patient_file/summary/demographics.php
  interface/reports/collections_report.php
  interface/reports/criteria.tab.php
  library/daysheet.inc.php
  library/edihistory/test_edih_835_accounting.php
  library/gen_x12_837i.inc.php
  myportal/soap_service/server_side.php
  src/Billing/BillingReport.php
  src/Billing/BillingUtilities.php
  src/Billing/Claim.php
  src/Billing/EDI270.php
  src/Billing/HCFAInfo.php
  src/Billing/Hcfa1500.php
  src/Billing/InvoiceSummary.php
  src/Billing/ParseERA.php
  src/Billing/PaymentGateway.php
  src/Billing/X125010837I.php
  src/Billing/X125010837P.php
Labels: Status: Ready for Integration, Status: Reviewed

#3433 FHIR Resources Validation fix
  src/RestControllers/FHIR/FhirAllergyIntoleranceRestController.php
  src/RestControllers/FHIR/FhirConditionRestController.php
  src/RestControllers/FHIR/FhirImmunizationRestController.php
  src/RestControllers/FHIR/FhirOrganizationRestController.php
  src/RestControllers/FHIR/FhirProcedureRestController.php
  src/Services/FHIR/FhirAllergyIntoleranceService.php
  src/Services/FHIR/FhirProcedureService.php
Labels: Status: Needs Review

#3397 [SQL]: Fix #3378 fix default timestamp issue
  library/sql_upgrade_fx.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#3439 quick fix
  interface/main/calendar/find_patient_popup.php
Labels: Status: Needs Review

#3440 migrate missing fa-external-link icon to fa-external-link-alt
  Documentation/help_files/adminacl_help.php
  Documentation/help_files/cms_1500_help.php
  Documentation/help_files/configure_orders_help.php
  Documentation/help_files/history_dashboard_help.php
  Documentation/help_files/issues_dashboard_help.php
  Documentation/help_files/medical_dashboard_help.php
  Documentation/help_files/message_center_help.php
  Documentation/help_files/openemr_installation_help.php
  Documentation/help_files/report_dashboard_help.php
  Documentation/help_files/transactions_dashboard_help.php
  src/OeUI/OemrUI.php
Labels: Status: Needs Review

#3442 Validator Component and Patient Service Updates/Tests
  .travis.yml
  phpunit.xml
  src/Services/PatientService.php
  src/Validators/BaseValidator.php
  src/Validators/PatientValidator.php
  src/Validators/ProcessingResult.php
  tests/Tests/Fixtures/FixtureManager.php
  tests/Tests/Fixtures/FixtureManagerTest.php
  tests/Tests/Fixtures/patients.json
  tests/Tests/Service/PatientServiceTest.php
  tests/Tests/Services/PatientServiceTest.php
  tests/Tests/Validators/PatientValidatorTest.php
  tests/Tests/Validators/ProcessingResultTest.php
Labels: Status: Needs Review
