Repository openemr/openemr, pull requests merged in 2020-10, with the labels that each got.

#3944 Adding code , effectiveDate and valueQuantity in Observation FHIR Resource
  src/Services/FHIR/FhirObservationService.php
  src/Services/ObservationLabService.php
Labels: Status: Needs Review

#3945 Refine Administration global page
  interface/super/edit_globals.php
Labels: Status: Ready for Integration, Status: Reviewed

#3943 Adding type in FHIR Encounter and Patient FHIR search by id
  src/Services/EncounterService.php
  src/Services/FHIR/FhirEncounterService.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/PatientService.php
Labels: Status: Needs Review, Status: Needs Work

#3845 Refactor: refine the fee sheet, new encounter form, procedure order pages.
  interface/forms/fee_sheet/new.php
  interface/forms/fee_sheet/review/views/review.php
  interface/forms/newpatient/common.php
  interface/forms/procedure_order/new.php
  interface/orders/find_order_popup.php
  interface/patient_file/encounter/find_code_dynamic.php
  interface/patient_file/encounter/find_code_history.php
  interface/patient_file/summary/add_edit_issue.php
Labels: Status: Ready for Integration, Status: Reviewed

#3955 Priorauth
  contrib/forms/prior_auth/C_FormPriorAuth.class.php
  contrib/forms/prior_auth/FormPriorAuth.class.php
  contrib/forms/prior_auth/info.txt
  contrib/forms/prior_auth/new.php
  contrib/forms/prior_auth/report.php
  contrib/forms/prior_auth/save.php
  contrib/forms/prior_auth/table.sql
  contrib/forms/prior_auth/templates/prior_auth/general_new.html
  contrib/forms/prior_auth/view.php
  interface/forms/prior_auth/C_FormPriorAuth.class.php
  interface/forms/prior_auth/FormPriorAuth.class.php
  interface/forms/prior_auth/info.txt
  interface/forms/prior_auth/report.php
  interface/forms/prior_auth/save.php
  interface/forms/prior_auth/table.sql
  interface/forms/prior_auth/templates/prior_auth/general_new.html
  sql/5_0_2-to-6_0_0_upgrade.sql
  version.php
Labels: Status: Ready for Integration

#3857 refactor: refine the fee section pages.
  interface/billing/billing_process.php
  interface/billing/billing_report.php
  interface/billing/edih_view.php
  interface/billing/era_payments.php
  interface/billing/new_payment.php
  interface/billing/payment_master.inc.php
  interface/billing/payment_pat_sel.inc.php
  interface/billing/print_daysheet_report_num1.php
  interface/billing/search_payments.php
  interface/billing/sl_eob_patient_note.php
  interface/billing/sl_eob_search.php
  interface/patient_file/front_payment.php
  interface/patient_file/pos_checkout.php
  interface/reports/criteria.tab.php
  src/Billing/BillingReport.php
Labels: Status: Ready for Integration, Status: Reviewed

#3962 these chars seem to make everything bold and too big
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Status: Needs Review

#3954 Standardize/improve delete prompt
  interface/patient_file/deleter.php
Labels: Status: Needs Review, Status: Needs Work

#3965 prior auth is admin category
  interface/forms/prior_auth/info.txt
  library/registry.inc
Labels: Status: Needs Review

#3964 working on d2 and d3 for onc 2015
  interface/forms/eye_mag/php/eye_mag_functions.php
  interface/forms/eye_mag/php/taskman_functions.php
  interface/logview/logview.php
  interface/main/backup.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/patient_file/deleter.php
  interface/patient_file/report/patient_report.php
  interface/patient_file/summary/advancedirectives.php
  interface/patient_file/summary/demographics.php
  interface/reports/audit_log_tamper_report.php
  library/ajax/adminacl_ajax.php
  library/classes/CategoryTree.class.php
  library/globals.inc.php
  library/sql.inc
  portal/get_patient_documents.php
  portal/report/portal_patient_report.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Common/Logging/EventAuditLogger.php
  src/Services/DocumentService.php
  version.php
Labels: Status: Needs Review

#3982 Bug Fixes for AllergyIntolerance
  interface/patient_file/summary/add_edit_issue.php
  src/Services/AllergyIntoleranceService.php
  src/Services/FHIR/FhirAllergyIntoleranceService.php
Labels: Status: Needs Review

#3983 Bug fix for Identifier when creating Bundle
  src/Services/FHIR/FhirResourcesService.php
Labels: Status: Needs Work

#3985 Provenance Resource for AllergyIntolerance
  src/Services/AllergyIntoleranceService.php
  src/Services/FHIR/FhirAllergyIntoleranceService.php
  src/Services/FHIR/FhirCareTeamService.php
  src/Services/FHIR/FhirConditionService.php
  src/Services/FHIR/FhirEncounterService.php
  src/Services/FHIR/FhirImmunizationService.php
  src/Services/FHIR/FhirLocationService.php
  src/Services/FHIR/FhirMedicationRequestService.php
  src/Services/FHIR/FhirMedicationService.php
  src/Services/FHIR/FhirObservationService.php
  src/Services/FHIR/FhirOrganizationService.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/FHIR/FhirPractitionerRoleService.php
  src/Services/FHIR/FhirPractitionerService.php
  src/Services/FHIR/FhirProcedureService.php
  src/Services/FHIR/FhirResourcesService.php
  src/Services/FHIR/FhirServiceBase.php
Labels: Status: Needs Review, Status: Needs Work

#3995 fix for the database pooling global
  interface/globals.php
  interface/main/calendar/includes/pnAPI.php
  interface/modules/zend_modules/config/autoload/global.php
  library/ajax/sql_server_status.php
  library/sql.inc
  portal/patient/fwk/libs/verysimple/DB/DataDriver/MySQLi.php
  src/Gacl/Gacl.php
Labels: Status: Needs Review
