Repository openemr/openemr, pull requests merged in 2020-11, with the labels that each got.

#3976 Updates a few Dependencies, including Bootstrap
  package-lock.json
  package.json
Labels: Status: Needs Review

#4013 Authorization Server
  _rest_config.php
  apis/dispatch.php
  composer.json
  composer.lock
  oauth2/.htaccess
  oauth2/authorize.php
  oauth2/provider/.well-known/discovery.php
  oauth2/provider/login.php
  sites/default/documents/certificates/private.key
  sites/default/documents/certificates/public.key
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Common/Auth/OpenIDConnect/Entities/AccessTokenEntity.php
  src/Common/Auth/OpenIDConnect/Entities/AuthCodeEntity.php
  src/Common/Auth/OpenIDConnect/Entities/ClientEntity.php
  src/Common/Auth/OpenIDConnect/Entities/RefreshTokenEntity.php
  src/Common/Auth/OpenIDConnect/Entities/ScopeEntity.php
  src/Common/Auth/OpenIDConnect/Entities/UserEntity.php
  src/Common/Auth/OpenIDConnect/Repositories/AccessTokenRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/AuthCodeRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/IdentityRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/RefreshTokenRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/UserRepository.php
  src/RestControllers/AuthorizationController.php
  tests/api/InternalApiTest.php
Labels: 2015 ONC

#4022 secured the mechanism for oauth key pair and encryption key
  _rest_config.php
  oauth2/authorize.php
  sites/default/documents/certificates/README.md
  sites/default/documents/certificates/private.key
  sites/default/documents/certificates/public.key
  src/RestControllers/AuthorizationController.php
Labels: Status: Needs Review

#4028 check for modules dir for upgr < 4.2.2
  interface/globals.php
Labels: Status: Needs Review

#4036 oauth updates
  API_README.md
  FHIR_README.md
  _rest_config.php
  _rest_routes.inc.php
  apis/dispatch.php
  docker/development-easy-arm32/docker-compose.yml
  docker/development-easy-arm64/docker-compose.yml
  docker/development-easy-light/docker-compose.yml
  docker/development-easy/docker-compose.yml
  oauth2/authorize.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Common/Auth/OpenIDConnect/Repositories/AccessTokenRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
  src/Common/Session/SessionUtil.php
  src/RestControllers/AuthRestController.php
  src/RestControllers/AuthorizationController.php
  tests/api/InternalApiTest.php
  version.php
Labels: Status: Needs Review

#4039 lose code shorty
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#4040 oauth updates
  _rest_config.php
  apis/dispatch.php
  library/globals.inc.php
  oauth2/authorize.php
  oauth2/provider/.well-known/discovery.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Common/Auth/OpenIDConnect/Entities/UserEntity.php
  src/Common/Auth/OpenIDConnect/Grant/CustomPasswordGrant.php
  src/Common/Auth/OpenIDConnect/Repositories/AccessTokenRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/UserRepository.php
  src/Common/Auth/UuidUserAccount.php
  src/RestControllers/AuthorizationController.php
  version.php
Labels: Status: Needs Review, Status: Needs Work

#4051 Update oeHttp client to authorization code grant type.(phase 1)
  src/Common/Http/oeHttp.php
  src/Common/Http/oeHttpRequest.php
  src/Common/Http/oeOAuth.php
  src/RestControllers/AuthorizationController.php
Labels: 2015 ONC, Feature

#4054 Remove Publish Provider Client feature v6.0.0
  interface/main/tabs/menu/menus/patient_menus/standard.json
  interface/patient_file/summary/demographics.php
  library/globals.inc.php
  phpfhir/libs/controller/ClientAppController.php
  phpfhir/libs/controller/oeDispatcher.php
  phpfhir/providerPublishUI.php
  sites/default/documents/custom_menus/patient_menus/Custom.json
Labels: Backend Modernization Project

#4026 E2E test case adding a new system user
  tests/Tests/E2e/CreateStaffTest.php
  tests/Tests/E2e/Pages/LoginPage.php
  tests/Tests/E2e/Pages/MainPage.php
  tests/Tests/E2e/Pages/UsersTab.php
Labels: Status: Needs Review, Status: Needs Work

#4056 capability fhir fix
  _rest_config.php
  apis/dispatch.php
  tests/Tests/Api/ApiTestClientTest.php
  tests/Tests/Api/CapabilityFhirTest.php
Labels: Status: Needs Review

#4058 add logout endpoint to server
  API_README.md
  apis/dispatch.php
  oauth2/authorize.php
  oauth2/provider/.well-known/discovery.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/RestControllers/AuthorizationController.php
Labels: 2015 ONC, Status: Needs Review

#4070 bug fixes
  API_README.md
  apis/dispatch.php
  interface/fax/fax_dispatch.php
  interface/forms/LBF/new.php
  interface/globals.php
  interface/modules/zend_modules/public/index.php
  interface/reports/immunization_report.php
  interface/reports/non_reported.php
  interface/usergroup/usergroup_admin.php
  library/globals.inc.php
  library/patient.inc
  oauth2/authorize.php
  oauth2/provider/.well-known/discovery.php
  oauth2/provider/login.php
  portal/account/account.php
  portal/account/index_reset.php
  portal/account/register.php
  portal/add_edit_event_user.php
  portal/find_appt_popup_user.php
  portal/get_patient_info.php
  portal/index.php
  portal/lib/doc_lib.php
  portal/lib/paylib.php
  portal/messaging/handle_note.php
  portal/messaging/messages.php
  portal/messaging/secure_chat.php
  portal/patient/_app_config.php
  portal/patient/_machine_config.php
  portal/patient/fwk/libs/verysimple/Phreeze/GenericRouter.php
  portal/patient/index.php
  portal/patient/libs/Controller/PatientController.php
  portal/patient/libs/Controller/UserController.php
  portal/patient/scripts/app/patientdata.js
  portal/portal_payment.php
  portal/report/pat_ledger.php
  portal/report/portal_custom_report.php
  portal/report/portal_patient_report.php
  portal/sign/lib/save-signature.php
  portal/sign/lib/show-signature.php
  portal/verify_session.php
  sites/default/config.php
  sites/default/statement.inc.php
  sql_upgrade.php
  src/Common/Csrf/CsrfUtils.php
  src/RestControllers/AuthorizationController.php
  tests/Tests/Api/ApiTestClient.php
  tests/Tests/Api/ApiTestClientTest.php
  tests/Tests/Api/CapabilityFhirTest.php
  tests/Tests/Api/FacilityApiTest.php
  tests/Tests/Api/PatientApiTest.php
  tests/Tests/Api/PractitionerApiTest.php
Labels: Status: Needs Review
