Repository openemr/openemr, pull requests merged in 2020-05, with the labels that each got.

#3451 [SQL]: Fix #3378 fix default timestamp issue `amendments_history`
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#3416 Fix#3005 : Remove EDI History jquery ui
  interface/billing/edih_view.php
  library/css/edi_history_v2.css
Labels: Status: Needs Review

#3417 FHIR Medication Resource
  FHIR_README.md
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirMedicationRestController.php
  src/Services/FHIR/FhirMedicationService.php
Labels: Status: Needs Review

#3452 FHIR MedicationStatement Resource
  FHIR_README.md
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirMedicationStatementRestController.php
  src/Services/FHIR/FhirMedicationStatementService.php
Labels: Status: Needs Review, Status: Needs Work

#3467 Quick Update : FHIR README
  FHIR_README.md
Labels: Status: Needs Review

#3465 Fix #3458: change button layout
  interface/new/new_comprehensive.php
Labels: Status: Needs Review

#3453 Issue 3353 REST API Processing w/Patient Integration
  .travis.yml
  API_README.md
  _rest_routes.inc.php
  ci/nginx_72/docker-compose.yml
  ci/nginx_73/docker-compose.yml
  ci/nginx_74/docker-compose.yml
  ci/nginx_80/docker-compose.yml
  controllers/C_Document.class.php
  phpunit.xml
  src/RestControllers/PatientRestController.php
  src/RestControllers/RestControllerHelper.php
  src/Services/PatientService.php
  src/Validators/ProcessingResult.php
  tests/Tests/Api/ApiTestClient.php
  tests/Tests/Api/ApiTestClientDisabled.php
  tests/Tests/Api/PatientApiDisabled.php
  tests/Tests/Api/PlaceholderTest.php
  tests/Tests/E2e/TestOpenemrPage/ExampleE2eTest.php
  tests/Tests/Fixtures/FixtureManager.php
  tests/Tests/Fixtures/FixtureManagerTest.php
  tests/Tests/Fixtures/patients.json
  tests/Tests/RestControllers/HandleProcessingResultTest.php
  tests/Tests/RestControllers/PatientRestControllerTest.php
  tests/Tests/Services/PatientServiceTest.php
  tests/Tests/Validators/PatientValidatorTest.php
  tests/Tests/Validators/ProcessingResultTest.php
Labels: Status: Needs Review

#3475 api fix for downstream acl checks
  API_README.md
  _rest_config.php
  src/RestControllers/AuthRestController.php
  src/Services/EncounterService.php
Labels: Status: Needs Review

#3477 Add cli commands for installing Laminas modules
  interface/modules/zend_modules/module/Installer/Module.php
  interface/modules/zend_modules/module/Installer/config/module.config.php
  interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
Labels: Status: Needs Review

#3457 Feat #3414: add highlight config
  setup.php
Labels: Status: Ready for Integration

#3489 possible portal fixes
  portal/account/account.lib.php
  portal/patient/_app_config.php
  portal/patient/fwk/libs/verysimple/Phreeze/GenericRouter.php
  portal/patient/fwk/libs/verysimple/Phreeze/Phreezer.php
  portal/patient/index.php
  portal/patient/libs/Controller/OnsiteActivityViewController.php
  portal/patient/libs/Controller/OnsitePortalActivityController.php
  portal/patient/libs/Controller/PortalPatientController.php
  portal/patient/libs/Controller/UserController.php
  portal/patient/scripts/app/patientdata.js
  portal/patient/templates/DefaultError404.tpl.php
  portal/patient/templates/DefaultErrorFatal.tpl.php
Labels: Status: Needs Review, Status: Needs Work

#3493 Backport #3489
  portal/patient/_app_config.php
  portal/patient/fwk/libs/verysimple/Phreeze/GenericRouter.php
  portal/patient/fwk/libs/verysimple/Phreeze/Phreezer.php
  portal/patient/index.php
  portal/patient/libs/Controller/OnsiteActivityViewController.php
  portal/patient/libs/Controller/OnsitePortalActivityController.php
  portal/patient/libs/Controller/PortalPatientController.php
  portal/patient/libs/Controller/UserController.php
  portal/patient/scripts/app/patientdata.js
  portal/patient/templates/DefaultError404.tpl.php
  portal/patient/templates/DefaultErrorFatal.tpl.php
Labels: Status: Ready for Integration

#3494 another place to use ramsey
  ccr/uuid.php
Labels: Status: Ready for Integration

#3469 [SQL]: Fix #3378 fix default date issue `drug_inventory`
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#3500 fix typos for composer deprecation notices
  tests/Tests/Fixtures/FixtureManagerTest.php
  tests/Tests/Validators/ProcessingResultTest.php
Labels: Status: Ready for Integration

#3503 refresh add event to get dashboard pt
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
Labels: Status: Needs Review

#3504 [SQL]: Fix #3378 fix default date issue `drug`
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#3505 Encounter updates
  interface/forms/newpatient/common.php
  interface/forms/newpatient/save.php
  interface/patient_file/encounter/forms.php
  library/ajax/facility_ajax_code.php
  library/encounter_events.inc.php
Labels: Status: Needs Work

#3514 [SQL]: Fix #3378 fix default date issue `insurance_data`
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#3509 Add patient portal rest api
  .travis.yml
  API_README.md
  FHIR_README.md
  _rest_config.php
  _rest_routes.inc.php
  apis/dispatch.php
  docker-compose.yml
  interface/usergroup/mfa_totp.php
  library/ESign/Encounter/Controller.php
  library/ESign/Form/Controller.php
  library/auth.inc
  library/globals.inc.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  src/Common/Auth/AuthUtils.php
  src/Events/RestApiExtend/RestApiCreateEvent.php
  src/RestControllers/AuthRestController.php
  version.php
Labels: Status: Needs Review

#3519 [SQL]: Fix #3378 fix default date time issue onsite_documents table
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Ready for Integration

#3535 quick fix nation notes
  library/js/ajax_functions_writer.js
Labels: Status: Needs Review

#3532 Add FHIR resource tables
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
Labels: Status: Ready for Integration

#3533 uuid registry support and added uuid to patient_data
  interface/globals.php
  interface/modules/zend_modules/config/autoload/global.php
  library/patient.inc
  library/sql_upgrade_fx.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  src/Common/Uuid/UuidRegistry.php
  src/Services/BaseService.php
  src/Services/PatientService.php
  tests/Tests/Fixtures/FixtureManager.php
  version.php
Labels: Status: Needs Review

#3540 Import FontAwesome into SCSS/SASS (#3539)
  .stylelintrc.json
  config/config.yaml
  gulpfile.js
  interface/themes/color_base.scss
  interface/themes/core/FontAwesome.scss
  interface/themes/oe-styles/style_dark.scss
  interface/themes/oe-styles/style_light.scss
  interface/themes/oe-styles/style_manila.scss
  interface/themes/oe-styles/style_superhero.scss
  interface/themes/patientportal-style.scss
Labels: Status: Needs Review

#3526 ensure null date used in codebase for insert/update date in insurance_data table
  interface/billing/billing_report.php
  interface/orders/gen_hl7_order.inc.php
  interface/reports/collections_report.php
  interface/reports/insurance_allocation_report.php
  library/daysheet.inc.php
  library/patient.inc
  src/Billing/BillingReport.php
  src/Billing/BillingUtilities.php
  src/Billing/Claim.php
  src/Billing/SLEOB.php
Labels: Status: Ready for Integration

#3549 storing uuid in byte format rather than string format
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  src/Common/Uuid/UuidRegistry.php
Labels: Status: Needs Review

#3552 minor cleanup of gulpfile
  gulpfile.js
Labels: Status: Needs Review

#3553 change to null date for subscriber_dob
  interface/patient_file/summary/demographics.php
  library/patient.inc
  sql/5_0_2-to-5_0_3_upgrade.sql
  version.php
Labels: Status: Needs Review, Status: Needs Work

#3557 upgrade fixes and minor changes in uuid documentation
  library/sql_upgrade_fx.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  src/Common/Uuid/UuidRegistry.php
  version.php
Labels: Status: Needs Review

#3558 Update FHIR Patient Endpoint to Support Standard API Processing
  .gitignore
  .travis.yml
  _rest_routes.inc.php
  phpunit.xml
  src/Common/Uuid/UuidRegistry.php
  src/RestControllers/FHIR/FhirPatientRestController.php
  src/RestControllers/RestControllerHelper.php
  src/Services/BaseService.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/FHIR/FhirResourcesService.php
  src/Services/FHIR/FhirServiceBase.php
  src/Services/PatientService.php
  src/Validators/PatientValidator.php
  src/Validators/ProcessingResult.php
  tests/Tests/Api/PatientApiTest.php
  tests/Tests/Common/Uuid/UuidRegistryTest.php
  tests/Tests/Fixtures/FixtureManager.php
  tests/Tests/Fixtures/FixtureManagerTest.php
  tests/Tests/Fixtures/fhir-patients.json
  tests/Tests/Fixtures/patients.json
  tests/Tests/README.md
  tests/Tests/RestControllers/FHIR/FhirPatientRestControllerTest.php
  tests/Tests/RestControllers/PatientRestControllerTest.php
  tests/Tests/Services/FHIR/FhirPatientServiceCrudTest.php
  tests/Tests/Services/FHIR/FhirPatientServiceMappingTest.php
  tests/Tests/Services/FHIR/FhirPatientServiceQueryTest.php
  tests/Tests/Services/PatientServiceTest.php
  tests/Tests/Validators/PatientValidatorTest.php
Labels: Status: Needs Review

#3560 add common test to travis and get the portalfhir call working
  .travis.yml
  _rest_routes.inc.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
  src/RestControllers/AuthRestController.php
  version.php
Labels: Status: Needs Review

#3564 using uuid in patient api endpoints
  API_README.md
  FHIR_README.md
  _rest_routes.inc.php
  src/RestControllers/PatientRestController.php
  src/Services/BaseService.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/PatientService.php
  src/Validators/PatientValidator.php
  tests/Tests/Api/PatientApiTest.php
  tests/Tests/RestControllers/PatientRestControllerTest.php
  tests/Tests/Services/PatientServiceTest.php
  tests/Tests/Validators/PatientValidatorTest.php
Labels: Status: Needs Review

#3568 Clinic Rules and Reminders
  library/clinical_rules.php
  library/reminders.php
  src/RestControllers/AuthRestController.php
Labels: Status: Needs Review

#3573 encounter bug fix issue #3449
  interface/forms/newpatient/common.php
  interface/forms/newpatient/save.php
Labels: Status: Needs Review

#3569 Refactor #3527: remove jquery-ui and change to bootstrap components ui
  interface/forms/eye_mag/help.php
  interface/usergroup/facilities_add.php
Labels: Status: Needs Review

#3575 Calendar Fix
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pnuserapi.php
  interface/themes/ajax_calendar_sass.scss
Labels: Status: Needs Review
