Repository openemr/openemr, pull requests merged in 2020-12, with the labels that each got.

#4067 Patient finder improvements
  interface/main/finder/dynamic_finder.php
Labels: Status: Needs Review

#4087 PHP8 fixes
  Documentation/help_files/sl_eob_help.php
  controllers/C_Document.class.php
  controllers/C_Prescription.class.php
  interface/billing/billing_process.php
  interface/billing/billing_report.php
  interface/billing/era_payments.php
  interface/billing/payment_master.inc.php
  interface/billing/payment_pat_sel.inc.php
  interface/billing/search_payments.php
  interface/billing/sl_eob_invoice.php
  interface/billing/sl_eob_search.php
  interface/patient_file/education.php
  interface/patient_file/encounter/find_code_popup.php
  interface/patient_file/pos_checkout.php
  interface/patient_file/report/custom_report.php
  interface/patient_file/report/patient_report.php
  interface/patient_file/summary/disclosure_full.php
  interface/patient_file/summary/immunizations.php
  interface/patient_file/summary/record_disclosure.php
  interface/patient_file/transaction/print_referral.php
  interface/reports/criteria.tab.php
  interface/reports/pat_ledger.php
  library/ajax/payment_ajax.php
  library/classes/Prescription.class.php
  library/options.inc.php
  library/payment.inc.php
  library/registry.inc
  library/report.inc
  sites/default/statement.inc.php
  src/Billing/BillingReport.php
  src/Billing/BillingUtilities.php
  src/Billing/Claim.php
  src/Billing/HCFAInfo.php
  src/Billing/InvoiceSummary.php
  src/Billing/X125010837P.php
  src/Common/Logging/EventAuditLogger.php
  templates/documents/general_list.html
  templates/documents/general_upload.html
  templates/documents/general_view.html
  templates/prescription/general_edit.html
  templates/prescription/general_list.html
Labels: Status: Needs Work

#4107 php8 and misc fixes
  interface/batchcom/batch_reminders.php
  interface/billing/billing_report.php
  interface/billing/print_daysheet_report_num1.php
  interface/forms/LBF/new.php
  interface/forms_admin/forms_admin.php
  interface/language/lang_constant.php
  interface/language/lang_definition.php
  interface/language/lang_language.php
  interface/language/lang_manage.php
  interface/language/language.php
  interface/logview/logview.php
  interface/main/holidays/import_holidays.php
  interface/patient_file/encounter/find_code_dynamic_ajax.php
  interface/patient_file/encounter/superbill_custom_full.php
  interface/patient_file/reminder/patient_reminders.php
  interface/reports/audit_log_tamper_report.php
  interface/reports/report.script.php
  interface/super/edit_layout.php
  interface/super/edit_layout_props.php
  interface/super/edit_list.php
  interface/super/manage_document_templates.php
  interface/super/rules/base/library/ActionRouter.php
  interface/super/rules/controllers/alerts/controller.php
  interface/usergroup/facilities.php
  interface/usergroup/facilities_add.php
  interface/usergroup/ssl_certificates_admin.php
  interface/usergroup/usergroup_admin.php
  interface/usergroup/usergroup_admin_add.php
  library/ESign/Form/Controller.php
  library/daysheet.inc.php
  library/edihistory/edih_segments.php
  library/edihistory/edih_x12file_class.php
  library/reminders.php
  src/Billing/BillingReport.php
  src/Common/Logging/EventAuditLogger.php
  src/OeUI/OemrUI.php
Labels: Status: Needs Review, Status: Needs Work

#4111 After megration hashed salted passwords from 4.2.0 couldn't login due…
  src/Common/Auth/AuthHash.php
Labels: Status: Needs Review, Status: Needs Work

#4090 SMART-FHIR Capability & .well-known statement
  _rest_config.php
  _rest_routes.inc.php
  apis/dispatch.php
  composer.json
  composer.lock
  interface/patient_file/summary/demographics.php
  interface/smart/register-app.php
  library/dialog.js
  oauth2/authorize.php
  public/smart-styles/smart-light.json
  src/Common/Auth/OpenIDConnect/Entities/ClientEntity.php
  src/Common/Auth/OpenIDConnect/IdTokenSMARTResponse.php
  src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
  src/Common/Http/HttpRestRouteHandler.php
  src/Common/Logging/SystemLogger.php
  src/Events/PatientDemographics/RenderEvent.php
  src/FHIR/SMART/Capability.php
  src/FHIR/SMART/SMARTLaunchToken.php
  src/FHIR/SMART/SmartLaunchController.php
  src/RestControllers/AuthorizationController.php
  src/RestControllers/FHIR/FhirMetaDataRestController.php
  src/RestControllers/SMART/SMARTConfigurationController.php
  src/Services/PatientService.php
  tests/Tests/Api/CapabilityFhirTest.php
  tests/Tests/Api/SmartConfigurationTest.php
  tests/Tests/Unit/Common/Auth/OpenIDConnect/Entities/ClientEntityTest.php
  tests/Tests/Unit/FHIR/SMART/SMARTLaunchTokenTest.php
Labels: Status: Needs Review, Status: Needs Work

#4122 mfa u2f oauth fixes and php8 fixes
  interface/main/main_screen.php
  oauth2/provider/login.php
  src/Common/Auth/MfaUtils.php
  src/Common/Auth/OpenIDConnect/Entities/UserEntity.php
  src/RestControllers/AuthorizationController.php
Labels: Status: Needs Work

#4123 support for permissions via scope
  API_README.md
  _rest_config.php
  _rest_routes.inc.php
  apis/dispatch.php
  oauth2/authorize.php
  oauth2/provider/.well-known/discovery.php
  oauth2/provider/jwk.php
  oauth2/provider/login.php
  src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
  src/Common/Logging/SystemLogger.php
  src/RestControllers/RestControllerHelper.php
  tests/Tests/Api/ApiTestClient.php
  tests/Tests/Api/ApiTestClientTest.php
Labels: Status: Needs Work
