Repository openemr/openemr, pull requests merged in 2020-03, with the labels that each got.

#3043 Remove jquery-ui dependency from TabsWrapper.php
  src/Tabs/TabsWrapper.php
Labels: Status: Needs Review, Status: Needs Work

#3025 Remove jquery-ui from batch 3 of scripts
  interface/forms/fee_sheet/new.php
  interface/forms/group_attendance/new.php
  interface/forms/newpatient/common.php
  interface/main/messages/messages.php
  interface/main/pwd_expires_alert.php
  interface/main/tabs/main.php
  interface/new/new_comprehensive.php
  interface/orders/procedure_provider_edit.php
  interface/orders/single_order_results.php
  interface/orders/types_edit.php
Labels: Status: Needs Review

#3026 Remove jquery-ui from batch 4 of scripts
  interface/patient_file/encounter/superbill_custom_full.php
  interface/patient_file/front_payment.php
  interface/patient_file/merge_patients.php
  interface/patient_file/summary/add_edit_issue.php
  interface/patient_file/summary/immunizations.php
  interface/patient_file/summary/pnotes_full.php
  interface/patient_tracker/patient_tracker.php
  interface/therapy_groups/therapy_groups_views/header.php
  interface/usergroup/facilities.php
  interface/usergroup/facility_admin.php
Labels: Status: Needs Review

#3046 Fix #3040 empty note content
  interface/main/onotes/office_comments_full.php
Labels: Status: Needs Review

#3050 fix: issue template typo
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Status: Needs Review

#3051 Fix#3047 remove outdated syntax
  interface/reports/immunization_report.php
Labels: Status: Needs Review

#3054 Encounter tabs UI improved
  interface/patient_file/encounter/forms.php
Labels: Status: Needs Review

#3056 UI improvements: Report -> Procedure search popup
  interface/patient_file/encounter/find_code_popup.php
Labels: Status: Needs Review

#3059 UI Improvements: Add new Procedure provider popup
  interface/orders/procedure_provider_edit.php
Labels: Status: Needs Review

#3058 layout should have a name
  interface/super/edit_layout_props.php
Labels: Status: Needs Review

#3064 Fix #3061 facilities modal
  interface/usergroup/facilities_add.php
  interface/usergroup/facility_admin.php
Labels: Status: Needs Review

#3066 Changed Add Facility checkboxes to new UI following Edit Facility
  .gitignore
  composer.json
  interface/usergroup/facilities_add.php
Labels: Status: Needs Review, Status: Needs Work

#3074 UI Imrovement: Admin -> Address Book
  interface/usergroup/addrbook_list.php
Labels: Status: Needs Review

#3069 Fix #3062 calendar text link
  interface/main/calendar/modules/PostCalendar/pnadmin.php
Labels: Status: Needs Review

#3087 Add support for expand/collapse specific forms in the encounter summa…
  interface/patient_file/encounter/forms.php
Labels: Status: Needs Review

#3080 Fix #3070 refine test table
  interface/main/calendar/modules/PostCalendar/pnadmin.php
Labels: Status: Needs Review

#3028 Remove jquery-ui from batch 6 of scripts
  library/js/oeUI/universalTooltip.js
  portal/patient/templates/OnsiteDocumentListView.tpl.php
  portal/patient/templates/_FormsHeader.tpl.php
  setup.php
  src/OeUI/OemrUI.php
  templates/documents/general_list.html
  templates/prescription/general_edit.html
Labels: Status: Needs Review, Status: Needs Work

#3086 fixups
  composer.json
  interface/billing/billing_report.php
  interface/main/tabs/templates/patient_data_template.php
  interface/themes/oe-common/main-common.scss
  library/dialog.js
Labels: Status: Ready for Integration

#3037 Remove jquery-ui from batch 1 of scripts
  admin.php
  custom/download_qrda.php
  interface/billing/search_payments.php
  interface/billing/ub04_form.php
Labels: Status: Needs Review

#3096 fixed Remove tab button
  src/Tabs/TabsWrapper.php
Labels: Status: Needs Review

#3098 fixed heading to Add Mode
  interface/orders/types.php
Labels: Status: Needs Review

#3089 Fix #3081 categories button and confirm form
  interface/main/calendar/includes/pnHTML.php
  interface/main/calendar/modules/PostCalendar/pnadmin.php
Labels: Status: Needs Review

#3023 validation based check on generate_form_field method
  interface/cmsportal/history_form.php
  interface/cmsportal/patient_form.php
  interface/forms/LBF/new.php
  interface/forms/eye_mag/a_issue.php
  interface/new/new_comprehensive.php
  interface/patient_file/summary/demographics_full.php
  interface/patient_file/transaction/add_transaction.php
  interface/usergroup/facility_user_admin.php
  library/js/xl/jquery-datetimepicker-2-5-4.js.php
  library/options.inc.php
  sql/5_0_2-to-5_0_3_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review

#3111 Fixed uneven body top
  interface/main/tabs/main.php
Labels: Status: Needs Review

#3115 Misleading Add/Edit Drug Form
  interface/drugs/add_edit_drug.php
Labels: Status: Needs Review

#3116 Fix #3077 remove jqueryui
  interface/code_systems/cqm_valueset_howto.php
  interface/code_systems/dataloads_ajax.php
  interface/code_systems/icd10_howto.php
  interface/code_systems/icd9_howto.php
  interface/code_systems/rxnorm_howto.php
  interface/code_systems/snomed_howto.php
Labels: Status: Needs Review, Status: Needs Work

#3117 Drug Inventory UI
  interface/drugs/drug_inventory.php
Labels: Status: Needs Review

#3121 Fix #3104 refine install code set
  interface/super/load_codes.php
Labels: Status: Needs Review

#3127 Quick Fix CONTRIBUTING.md link
  CONTRIBUTING.md
Labels: Status: Needs Review

#3120 BS4 & UI suggestions
  interface/code_systems/dataloads_ajax.php
  interface/code_systems/icd10_howto.php
  interface/code_systems/icd9_howto.php
  interface/code_systems/list_staged.php
  interface/code_systems/rxnorm_howto.php
Labels: Status: Needs Review

#3126 Drug Inventory Group Lot Numbers
  interface/drugs/drug_inventory.php
Labels: Status: Needs Review

#3031 some fixes
  interface/forms/eye_mag/save.php
  interface/main/backup.php
  interface/usergroup/user_info.php
  library/custom_template/ajax_code.php
Labels: Status: Ready for Integration

#3133 Improved: Edit and Add Facility Button position and size
  interface/usergroup/facilities_add.php
  interface/usergroup/facility_admin.php
Labels: Status: Needs Review

#3132 Fixed NavBar Style
  interface/main/tabs/main.php
Labels: Status: Needs Review, Status: Needs Work

#3134 Fix #3130: load compendium title
  interface/orders/load_compendium.php
Labels: Status: Needs Review, Status: Needs Work

#3128 Fix #3099: add bootstrap table style and remove outdated syntax
  interface/forms_admin/forms_admin.php
Labels: Status: Needs Review

#3148 docs: add API_README.md command highlight
  API_README.md
Labels: Status: Needs Review

#3149 docs: change http link to https link
  CONTRIBUTING.md
Labels: Status: Needs Review

#3150 docs: add command to view php logs within openemr docker
  CONTRIBUTING.md
Labels: Status: Needs Review, Status: Needs Work

#3151 Quick Fix - Drug inventory Table
  interface/drugs/drug_inventory.php
Labels: Status: Needs Review

#3153 Add edit lot BS4 updates
  interface/drugs/add_edit_lot.php
Labels: Status: Needs Review

#3154 removed deprecated jquery's ready function
  interface/code_systems/dataloads_ajax.php
  interface/forms/fee_sheet/review/initialize_review.js
  interface/modules/zend_modules/public/js/installer/action.js
  tests/api/InternalApiTest.php
Labels: Status: Needs Review, Status: Needs Work

#3156 fixes Outdated drug destroyed interface
  interface/reports/destroyed_drugs_report.php
Labels: Status: Needs Review

#3157 fix: upgrade datatables to bootstrap 4 theme
  interface/main/finder/dynamic_finder.php
Labels: Status: Needs Review, Status: Needs Work

#3145 Fix #3129 cash rec form aligment
  interface/billing/sl_receipts_report.php
Labels: Status: Needs Review, Status: Needs Work

#3079 [WIP] Added Loading in tabs
  interface/main/main_screen.php
  interface/main/tabs/js/tabs_view_model.js
  interface/main/tabs/main.php
  interface/main/tabs/templates/tabs_template.php
Labels: Status: Needs Review

#3167 UI Improvement: Document Template Management
  interface/super/manage_document_templates.php
Labels: Status: Needs Review

#3171 removed jquery's deprecated ready method
  interface/main/tabs/js/custom_bindings.js
  interface/reports/daily_summary_report.php
  interface/super/rules/www/js/bucket.js
  interface/super/rules/www/js/custom.js
  interface/super/rules/www/js/detail.js
  interface/super/rules/www/js/edit.js
  interface/super/rules/www/js/list.js
  interface/super/rules/www/js/typeahead.js
  library/options_listadd.inc
  portal/sign/assets/signer_api.js
Labels: Status: Needs Review

#3175 Fix #3174 patient encounter form field alignment
  interface/forms/newpatient/common.php
Labels: Status: Needs Review, Status: Needs Work

#3184 Explanatory Error Message
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
Labels: Status: Needs Review

#3186 Fix #3179 Update font awesome
  config/config.yaml
  interface/themes/core/FontAwesome.scss
  package.json
Labels: Status: Needs Review, Status: Needs Work

#3190 Create patient encounter API
  API_README.md
  _rest_routes.inc.php
  src/RestControllers/EncounterRestController.php
  src/Services/EncounterService.php
Labels: Status: Needs Review, Status: Needs Work

#3202 Fix #2949: add diagnostics to navbar
  interface/main/tabs/menu/menus/standard.json
Labels: Status: Needs Review, Status: Needs Work

#3197 Replace top menu with BS4 navbar
  interface/main/tabs/main.php
  interface/main/tabs/templates/menu_template.php
  interface/main/tabs/templates/tabs_template.php
  interface/main/tabs/templates/user_data_template.php
  interface/themes/core/navmenu.scss
  interface/themes/tabs_style_compact.css
  interface/themes/tabs_style_full.css
  library/globals.inc.php
  src/Menu/PatientMenuRole.php
Labels: Status: Needs Review

#3204 add leading slash to medex require
  interface/main/messages/save.php
Labels: Status: Ready for Integration

#3206 Main cleanup continued
  interface/main/tabs/templates/patient_data_template.php
  library/options.inc.php
Labels: Status: Ready for Integration

#3172 Fix issue with being unable to import pharmacies due to ssl cipher mi…
  src/Common/Http/oeHttpRequest.php
  src/Pharmacy/Services/ImportPharmacies.php
Labels: Status: Needs Review

#3198 FHIR API Error Response
  src/RestControllers/FhirPatientRestController.php
  src/Services/FhirResourcesService.php
Labels: Status: Needs Review

#3192 Implemented Post and Put feature in FHIRPatientRestController and added their routes.
  _rest_routes.inc.php
  src/RestControllers/FhirPatientRestController.php
  src/Services/FhirResourcesService.php
Labels: Status: Needs Review

#3187 Fixed #3001 Remove jquery-ui
  interface/login/login.php
  interface/main/about_page.php
  interface/product_registration/product_registration_controller.js
Labels: Status: Needs Review

#3214 fix: update font awesome refresh to sync icon
  interface/billing/billing_report.php
  interface/forms/fee_sheet/review/js/fee_sheet_core.js
  interface/login/login.php
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
  interface/main/finder/dynamic_finder.php
  interface/main/tabs/templates/patient_data_template.php
  interface/patient_file/encounter/find_code_history.php
  interface/patient_tracker/patient_tracker.php
  interface/weno/ajax_sample_code.php
  interface/weno/confirm.php
  portal/messaging/messages.php
Labels: Status: Needs Review

#3215 feat #3205 : improve diagnostics gui
  interface/main/calendar/modules/PostCalendar/pnadmin.php
Labels: Status: Needs Review, Status: Needs Work

#3225 fix: search-plus and search-minus icons broken
  interface/themes/core/FontAwesome.scss
Labels: Status: Needs Review

#3227 Fix: Curly brace style in RestController methods
  src/RestControllers/AppointmentRestController.php
  src/RestControllers/EncounterRestController.php
  src/RestControllers/FhirPatientRestController.php
  src/RestControllers/InsuranceCompanyRestController.php
  src/RestControllers/InsuranceRestController.php
  src/RestControllers/ListRestController.php
  src/RestControllers/MessageRestController.php
  src/RestControllers/PatientRestController.php
Labels: Status: Needs Review

#3224 Fix: register email input lost form-control style
  interface/login/login.php
  interface/main/about_page.php
Labels: Status: Needs Review

#3212 Basic Search patient by address, gender, phone
  _rest_routes.inc.php
  src/RestControllers/FhirPatientRestController.php
  src/Services/PatientService.php
Labels: Status: Needs Review

#3211 Add patient encounter PUT API
  API_README.md
  _rest_routes.inc.php
  src/RestControllers/EncounterRestController.php
  src/Services/EncounterService.php
Labels: Status: Needs Review, Status: Needs Work

#2986 Contribution: Handwritten Notes (#2942)
  config/config.yaml
  contrib/forms/handwritten-notes/hw-notes.php
  contrib/forms/handwritten-notes/info.txt
  contrib/forms/handwritten-notes/new.php
  contrib/forms/handwritten-notes/table.sql
  contrib/forms/handwritten-notes/view.php
  package-lock.json
  package.json
Labels: Status: Needs Review

#3237 Fix #2914 Increased Maxlength for mime types
  interface/super/edit_list.php
Labels: Status: Needs Review

#3243 Fix #3107 mult language tool style
  interface/language/lang_constant.php
  interface/language/lang_definition.php
  interface/language/lang_language.php
  interface/language/lang_manage.php
  interface/language/language.php
Labels: Status: Needs Review

#3229 Fix: Object not found in Miscellaneous/authorizations
  interface/themes/core/navmenu.scss
Labels: Status: Needs Review

#3258 Fix: css style background url
  interface/themes/core/navmenu.scss
Labels: Status: Needs Review

#3252 Added ValidationService
  src/RestControllers/FhirPatientRestController.php
  src/Services/FhirResourcesService.php
  src/Services/FhirValidationService.php
Labels: Status: Needs Review

#3183 Fixed : Deprecated Warinings
  interface/modules/zend_modules/module/Application/src/Application/Listener/Listener.php
  interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
  interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  interface/modules/zend_modules/module/Documents/src/Documents/Plugin/Documents.php
Labels: Status: Needs Review

#3250 Fix #3248 appointment search bs4
  interface/main/calendar/modules/PostCalendar/pntemplates/default/style/ajax_search.css
  interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
Labels: Status: Needs Review

#3271 fix: add miss btn-group style
  interface/main/calendar/add_edit_event.php
Labels: Status: Needs Review

#3256 Finished COVID form
  contrib/forms/covid19/cdc-pui-case-report-form/new.php
  contrib/forms/covid19/cdc-pui-case-report-form/print.php
  contrib/forms/covid19/cdc-pui-case-report-form/templates/form.html.twig
Labels: COVID-19, Status: Needs Review

#3278 fixed fa-icon
  interface/usergroup/adminacl.php
Labels: Status: Needs Review

#3275 Suggestion: using btn-group on action button can be confusing
  interface/login/login.php
Labels: Status: Needs Review

#3223 Fix #3166 eob invoice bs4 updates
  interface/billing/sl_eob_invoice.php
Labels: Status: Needs Review, Status: Needs Work

#3283 Integrating the "Flow Board" form to Bootstrap 4
  interface/patient_tracker/patient_tracker.php
Labels: Status: Needs Review

#3274 Quick-fix: Only activate the latest tab
  src/Tabs/TabsWrapper.php
Labels: Status: Needs Review

#3296 fix: change to button tag and add FontAwesome icon
  interface/main/calendar/modules/PostCalendar/pntemplates/default/user/ajax_search.html
Labels: Status: Needs Review

#3263 Fixed "double scroll-bar" bug on modals
  library/dialog.js
Labels: Status: Needs Review
