Repository openemr/openemr, pull requests merged in 2020-07, with the labels that each got.

#3679 Refactor: refine the message section pages
  interface/main/dated_reminders/dated_reminders.php
  interface/main/dated_reminders/dated_reminders_add.php
  interface/main/dated_reminders/dated_reminders_log.php
  interface/main/finder/multi_patients_finder.php
  interface/main/messages/messages.php
Labels: Status: Ready for Integration, Status: Reviewed

#3668 More BS4 Fixes
  interface/forms/group_attendance/new.php
  interface/forms/group_attendance/report.php
  interface/forms/newGroupEncounter/common.php
  interface/forms/newGroupEncounter/report.php
  interface/main/finder/dynamic_finder.php
  interface/main/tabs/main.php
  interface/new/new.php
  interface/new/new_comprehensive.php
  interface/new/new_search_popup.php
  interface/patient_file/encounter/superbill_custom_full.php
  interface/patient_file/reminder/active_reminder_popup.php
  interface/patient_file/reminder/patient_reminders.php
  interface/patient_file/summary/dashboard_header.php
  interface/patient_file/summary/dashboard_header_simple_return.php
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/demographics_full.php
  interface/super/edit_list.php
  interface/themes/colors/utilities/default_variables.scss
  interface/themes/core/FontAwesome.scss
  interface/themes/oe-common/acl-common.scss
  interface/themes/oe-styles/style_dark.scss
  interface/themes/oe-styles/style_light.scss
  interface/themes/oe-styles/style_manila.scss
  interface/themes/oe-styles/style_superhero.scss
  interface/themes/patientportal-style.scss
  interface/themes/theme-defaults.scss
  interface/therapy_groups/therapy_groups_views/addGroup.php
  interface/therapy_groups/therapy_groups_views/appointmentComponent.php
  interface/therapy_groups/therapy_groups_views/groupDetailsGeneralData.php
  interface/therapy_groups/therapy_groups_views/groupDetailsParticipants.php
  interface/therapy_groups/therapy_groups_views/header.php
  interface/therapy_groups/therapy_groups_views/listGroups.php
  interface/therapy_groups/therapy_groups_views/pastMeetingsComponent.php
  library/options.inc.php
  library/options_listadd.inc
  portal/patient/styles/style.css
  portal/patient/templates/OnsiteActivityViewListView.tpl.php
  portal/patient/templates/OnsitePortalActivityListView.tpl.php
  portal/patient/templates/ProviderHome.tpl.php
  portal/patient/templates/_Footer.tpl.php
  portal/patient/templates/_Header.tpl.php
  portal/patient/templates/_ProviderHeader.tpl.php
  src/Menu/PatientMenuRole.php
  templates/documents/general_list.html
  templates/documents/general_queue.html
  templates/documents/general_upload.html
  templates/documents/general_view.html
Labels: Status: Needs Review

#3680 Add UI List for Provide Role/Specialty with ValueSet
  .travis.yml
  interface/forms/LBF/new.php
  interface/new/new_comprehensive.php
  interface/patient_file/history/history_full.php
  interface/patient_file/summary/demographics_full.php
  interface/patient_file/transaction/add_transaction.php
  interface/super/edit_layout.php
  interface/usergroup/facility_user.php
  interface/usergroup/facility_user_admin.php
  library/options.inc.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review, Status: Needs Work

#3709 Added FHIR Endpoints for PractitionerRole
  FHIR_README.md
  _rest_routes.inc.php
  src/RestControllers/FHIR/FhirPractitionerRoleRestController.php
  src/Services/FHIR/FhirPractitionerRoleService.php
  src/Services/PractitionerRoleService.php
  src/Validators/PractitionerRoleValidator.php
Labels: Status: Needs Review, Status: Needs Work

#3711 fix: firefox vertical align center
  interface/themes/login_page.scss
Labels: Status: Ready for Integration, Status: Reviewed

#3718 Refactor: remove oudated javascript attribute
  contrib/forms/specialist_notes/new.php
  contrib/forms/specialist_notes/view.php
  controllers/C_Prescription.class.php
  custom/import_xml.php
  gacl/admin/templates/phpgacl/debug.tpl
  interface/de_identification_forms/find_drug_popup.php
  interface/fax/fax_dispatch.php
  interface/forms/CAMOS/notegen.php
  interface/forms/CAMOS/rx_print.php
  interface/forms/LBF/new.php
  interface/forms/LBF/printable.php
  interface/forms/newGroupEncounter/save.php
  interface/forms/physical_exam/edit_diagnoses.php
  interface/forms/procedure_order/new.php
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html
  interface/orders/procedure_provider_edit.php
  interface/orders/single_order_results.php
  interface/orders/types_edit.php
  interface/patient_file/deleter.php
  interface/patient_file/education.php
  interface/patient_file/front_payment.php
  interface/patient_file/history/edit_billnote.php
  interface/patient_file/history/history_full.php
  interface/patient_file/letter.php
  interface/patient_file/pos_checkout.php
  interface/patient_file/printed_fee_sheet.php
  interface/patient_file/problem_encounter.php
  interface/patient_file/rules/patient_data.php
  interface/patient_file/summary/advancedirectives.php
  interface/patient_file/summary/demographics_print.php
  interface/patient_file/summary/pnotes_full.php
  interface/patient_file/summary/pnotes_print.php
  interface/patient_file/summary/print_amendments.php
  interface/patient_file/summary/shot_record.php
  interface/patient_tracker/patient_tracker_status.php
  interface/reports/inventory_activity.php
  interface/reports/ippf_daily.php
  interface/reports/ippf_statistics.php
  interface/super/edit_layout_props.php
  interface/usergroup/user_info.php
  library/spreadsheet.inc.php
Labels: Status: Needs Review

#3703 Fix: remove invalid code syntax.
  contrib/forms/assessment_intake/view.php
  contrib/forms/contacts/new.php
  contrib/forms/contacts/view.php
  contrib/forms/evaluation/templates/evaluation/general_new.html
  contrib/forms/hearingtest/new.php
  contrib/forms/hearingtest/view.php
  contrib/forms/obstetrical/new.php
  contrib/forms/obstetrical/view.php
  contrib/forms/pain/new.php
  contrib/forms/pain/view.php
  contrib/forms/vision/new.php
  contrib/forms/vision/view.php
  interface/forms/ankleinjury/new.php
  interface/forms/ankleinjury/view.php
  interface/forms/bronchitis/new.php
  interface/forms/bronchitis/view.php
  interface/forms/note/view.php
  interface/patient_file/summary/demographics_full.php
  interface/patient_file/summary/record_disclosure.php
  interface/usergroup/facilities_add.php
  interface/usergroup/facility_admin.php
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin_add.php
Labels: Status: Needs Review

#3716 improve gacl integration
  Documentation/README.phpgacl
  acl_setup.php
  contrib/util/ubuntu_package_scripts/production/postinst
  gacl/admin/group_admin.php
  gacl/schema.xml
  gacl/setup.php
  library/classes/Installer.class.php
  library/sqlconf.php
  setup.php
  sql/database.sql
  tests/old_unit_dir/InstallerTest.php
Labels: Status: Needs Review

#3674 Refactor: Refine the recall board and new recall pages
  library/MedEx/API.php
Labels: Status: Ready for Integration, Status: Reviewed

#3725 Feat: adjust buttons icon
  interface/patient_file/reminder/patient_reminders.php
  interface/patient_file/summary/demographics_full.php
  src/Menu/PatientMenuRole.php
Labels: Status: Needs Review

#3713 Duplicates In PractitionerRole FHIR Resource
  src/RestControllers/FHIR/FhirPractitionerRoleRestController.php
  src/Services/FHIR/FhirPractitionerRoleService.php
  src/Services/PractitionerRoleService.php
  src/Validators/BaseValidator.php
  src/Validators/PractitionerRoleValidator.php
Labels: Status: Needs Review

#3733 miss the git and compose installation link in md
  CONTRIBUTING.md
Labels: Status: Needs Work

#3729 Immuniazation Resource
  API_README.md
  FHIR_README.md
  _rest_routes.inc.php
  interface/patient_file/summary/immunizations.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Common/Uuid/UuidRegistry.php
  src/RestControllers/FHIR/FhirImmunizationRestController.php
  src/RestControllers/ImmunizationRestController.php
  src/Services/FHIR/FhirImmunizationService.php
  src/Services/ImmunizationService.php
  src/Validators/ImmunizationValidator.php
Labels: Status: Needs Review, Status: Needs Work

#3731 Dicom Rework
  API_README.md
  CONTRIBUTING.md
  FHIR_README.md
  _rest_routes.inc.php
  controllers/C_Document.class.php
  interface/patient_file/summary/immunizations.php
  library/ajax/upload.php
  library/dicom_frame.php
  library/js/dwv/dicom_gui.js
  library/js/dwv/dicom_launcher.js
  library/js/dwv/gui/browser.js
  library/js/dwv/gui/colourMap.js
  library/js/dwv/gui/custom.js
  library/js/dwv/gui/dropboxLoader.js
  library/js/dwv/gui/filter.js
  library/js/dwv/gui/generic.js
  library/js/dwv/gui/help.js
  library/js/dwv/gui/html.js
  library/js/dwv/gui/infoController.js
  library/js/dwv/gui/infoOverlay.js
  library/js/dwv/gui/loader.js
  library/js/dwv/gui/plot.js
  library/js/dwv/gui/resources/help/click.png
  library/js/dwv/gui/resources/help/double_click.png
  library/js/dwv/gui/resources/help/mouse_drag.png
  library/js/dwv/gui/resources/help/mouse_wheel.png
  library/js/dwv/gui/tools.js
  library/js/dwv/gui/undo.js
  package.json
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Common/Uuid/UuidRegistry.php
  src/RestControllers/FHIR/FhirImmunizationRestController.php
  src/RestControllers/ImmunizationRestController.php
  src/Services/FHIR/FhirImmunizationService.php
  src/Services/ImmunizationService.php
  src/Validators/ImmunizationValidator.php
  templates/documents/general_list.html
  templates/documents/general_upload.html
  version.php
Labels: Status: Needs Review

#3743 Added ar_activity.deleted to track voids of payments and adjustments.
  interface/billing/billing_report.php
  interface/billing/edit_payment.php
  interface/billing/indigent_patients_report.php
  interface/billing/payment_master.inc.php
  interface/billing/payment_pat_sel.inc.php
  interface/billing/search_payments.php
  interface/billing/sl_eob_invoice.php
  interface/billing/sl_eob_process.php
  interface/billing/sl_eob_search.php
  interface/billing/sl_receipts_report.php
  interface/forms/fee_sheet/new.php
  interface/patient_file/deleter.php
  interface/patient_file/front_payment.php
  interface/patient_file/pos_checkout.php
  interface/reports/collections_report.php
  interface/reports/pat_ledger.php
  interface/reports/receipts_by_method_report.php
  interface/reports/svc_code_financial_report.php
  library/FeeSheet.class.php
  library/daysheet.inc.php
  library/patient.inc
  library/payment.inc.php
  portal/portal_payment.php
  portal/report/pat_ledger.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/Billing/BillingReport.php
  src/Billing/BillingUtilities.php
  src/Billing/Claim.php
  src/Billing/InvoiceSummary.php
  version.php
Labels: Status: Needs Review

#3750 using getAllServiceLocations in user_admin.php to retrieve facility list
  interface/usergroup/user_admin.php
Labels: Status: Needs Review

#3752 Fix #3734: add override css to fix multiple arrow issue
  interface/patient_file/encounter/find_code_dynamic.php
Labels: Status: Needs Review

#3701 Refactor #3700: refine dashboard disclosures page
  interface/patient_file/summary/disclosure_full.php
  interface/patient_file/summary/record_disclosure.php
Labels: Status: Ready for Integration, Status: Reviewed

#3682 Refactor: refine the patient finder page
  interface/main/finder/dynamic_finder.php
Labels: Status: Needs Work, Status: Ready for Integration, Status: Reviewed

#3755 external dataload fix for RxNorm and necessary change for ICD10
  library/standard_tables_capture.inc
Labels: Status: Needs Review

#3758 add openemr-cmd tool link
  CONTRIBUTING.md
Labels: Status: Needs Review

#3726 Refactor: refine the prescription list and prescription add pages
  templates/prescription/general_edit.html
  templates/prescription/general_list.html
Labels: Status: Ready for Integration, Status: Reviewed

#3753 Refactor: refine the amendments add and edit page.
  interface/patient_file/summary/add_edit_amendments.php
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/list_amendments.php
Labels: Status: Ready for Integration, Status: Reviewed

#3736 Upgrading AllergyIntolerance Resource
  API_README.md
  FHIR_README.md
  _rest_routes.inc.php
  custom/code_types.inc.php
  interface/patient_file/summary/add_edit_issue.php
  interface/patient_file/summary/stats_full.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/database.sql
  src/RestControllers/AllergyIntoleranceRestController.php
  src/RestControllers/FHIR/FhirAllergyIntoleranceRestController.php
  src/Services/AllergyIntoleranceService.php
  src/Services/FHIR/FhirAllergyIntoleranceService.php
  src/Validators/AllergyIntoleranceValidator.php
Labels: Status: Needs Review, Status: Needs Work

#3610 Fix #3542: html doctype attribute
  Documentation/Readme_edihistory.html
  Documentation/help_files/add_edit_transactions_dashboard_help.php
  Documentation/help_files/adminacl_help.php
  Documentation/help_files/cms_1500_help.php
  Documentation/help_files/configure_orders_help.php
  Documentation/help_files/fee_sheet_help.php
  Documentation/help_files/history_dashboard_help.php
  Documentation/help_files/issues_dashboard_help.php
  Documentation/help_files/ledger_dashboard_help.php
  Documentation/help_files/medical_dashboard_help.php
  Documentation/help_files/message_center_help.php
  Documentation/help_files/mfa_help.php
  Documentation/help_files/openemr_installation_help.php
  Documentation/help_files/openemr_multisite_admin_help.php
  Documentation/help_files/procedure_provider_help.php
  Documentation/help_files/report_dashboard_help.php
  Documentation/help_files/sl_eob_help.php
  Documentation/help_files/transactions_dashboard_help.php
  contrib/forms/handwritten-notes/hw-notes.php
  contrib/forms/handwritten-notes/new.php
  contrib/forms/xmlformgen/xslt/new.php.xslt
  contrib/forms/xmlformgen/xslt/print.php.xslt
  contrib/forms/xmlformgen/xslt/show.php.xslt
  contrib/forms/xmlformgen/xslt/view.php.xslt
  gacl/admin/templates/phpgacl/header.tpl
  interface/billing/edih_view.php
  interface/forms/CAMOS/help.html
  interface/forms/newGroupEncounter/common.php
  interface/main/calendar/includes/pnAPI.php
  interface/main/tabs/main.php
Labels: Status: Needs Work, Status: Ready for Integration, Status: Reviewed

#3771 feat: refine the setup page.
  library/classes/Installer.class.php
  setup.php
Labels: Status: Ready for Integration, Status: Reviewed

#3774 update cert/key management script to be future proof
  CONTRIBUTING.md
  interface/usergroup/ssl_certificates_admin.php
  library/create_ssl_certificate.php
  library/openssl.cnf
Labels: Status: Needs Review

#3785 added support for sql ssl cert in setup.php and to testing in dev env…
  CONTRIBUTING.md
  contrib/util/docker/README.md
  contrib/util/docker/docker-compose.yml
  contrib/util/docker/sql-ssl-certs-keys/README.md
  contrib/util/docker/sql-ssl-certs-keys/easy/ca-key.pem
  contrib/util/docker/sql-ssl-certs-keys/easy/ca.pem
  contrib/util/docker/sql-ssl-certs-keys/easy/client-cert.pem
  contrib/util/docker/sql-ssl-certs-keys/easy/client-key.pem
  contrib/util/docker/sql-ssl-certs-keys/easy/client-req.pem
  contrib/util/docker/sql-ssl-certs-keys/easy/server-cert.pem
  contrib/util/docker/sql-ssl-certs-keys/easy/server-key.pem
  contrib/util/docker/sql-ssl-certs-keys/easy/server-req.pem
  contrib/util/docker/sql-ssl-certs-keys/insane/ca-key.pem
  contrib/util/docker/sql-ssl-certs-keys/insane/ca.pem
  contrib/util/docker/sql-ssl-certs-keys/insane/client-cert.pem
  contrib/util/docker/sql-ssl-certs-keys/insane/client-key.pem
  contrib/util/docker/sql-ssl-certs-keys/insane/client-req.pem
  contrib/util/docker/sql-ssl-certs-keys/insane/server-cert.pem
  contrib/util/docker/sql-ssl-certs-keys/insane/server-key.pem
  contrib/util/docker/sql-ssl-certs-keys/insane/server-req.pem
  docker-compose.yml
  library/classes/Installer.class.php
Labels: Status: Needs Review

#3783 Fix #3778: change the add field max length to 63
  interface/super/edit_layout.php
Labels: Status: Needs Review, Status: Needs Work

#3745 Need to remove drug from the patient medication list also.
  library/deletedrug.php
Labels: Status: Needs Review, Status: Needs Work

#3717 Refactor: refine the patient messages and add patient messages pages.
  interface/patient_file/summary/pnotes_full.php
  interface/patient_file/summary/pnotes_full_add.php
Labels: Status: Ready for Integration, Status: Reviewed

#3757 fixed .interval span select width
  interface/super/rules/www/css/rules.css
Labels: Status: Needs Review, Status: Needs Work

#3786 Revert DWV to 0.26 from 0.27.0
  library/dicom_frame.php
  library/js/dwv/assets/dwv/decoders/dwv/rle.js
  library/js/dwv/assets/dwv/dist/dwv.js
  library/js/dwv/assets/dwv/dist/dwv.min.js
  library/js/dwv/dicom_gui.js
  library/js/dwv/dicom_launcher.js
  library/js/dwv/gui/browser.js
  library/js/dwv/gui/colourMap.js
  library/js/dwv/gui/custom.js
  library/js/dwv/gui/dropboxLoader.js
  library/js/dwv/gui/filter.js
  library/js/dwv/gui/generic.js
  library/js/dwv/gui/help.js
  library/js/dwv/gui/html.js
  library/js/dwv/gui/infoController.js
  library/js/dwv/gui/infoOverlay.js
  library/js/dwv/gui/loader.js
  library/js/dwv/gui/plot.js
  library/js/dwv/gui/tools.js
  library/js/dwv/gui/undo.js
Labels: dependencies

#3759 Refactor #3737: refine dashboard immunizations page
  interface/patient_file/summary/immunizations.php
Labels: Status: Needs Review
