Repository openemr/openemr, pull requests merged in 2021-01, with the labels that each got.

#4144 multi site disable file/perm checks
  setup.php
Labels: Status: Needs Review

#4145 immun updates
  interface/patient_file/summary/immunizations.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/cvx_codes.sql
  version.php
Labels: Status: Needs Review

#4169 Patient menu hook
  src/Menu/PatientMenuEvent.php
  src/Menu/PatientMenuRole.php
  tests/eventdispatcher/oe-modify-patient-menu-example/README.md
  tests/eventdispatcher/oe-modify-patient-menu-example/composer.json
  tests/eventdispatcher/oe-modify-patient-menu-example/custom_patient_menu.json
  tests/eventdispatcher/oe-modify-patient-menu-example/openemr.bootstrap.php
Labels: Status: Needs Review, Status: Reviewed

#4164 FHIR Coverage Resource Added
  API_README.md
  FHIR_README.md
  _rest_routes.inc.php
  interface/billing/sl_eob_process.php
  interface/reports/receipts_by_method_report.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/RestControllers/FHIR/FhirCoverageRestController.php
  src/RestControllers/InsuranceCompanyRestController.php
  src/RestControllers/InsuranceRestController.php
  src/Services/FHIR/FhirCoverageService.php
  src/Services/FHIR/FhirOrganizationService.php
  src/Services/FacilityService.php
  src/Services/InsuranceCompanyService.php
  src/Services/InsuranceService.php
  src/Services/OrganizationService.php
  src/Validators/BaseValidator.php
  src/Validators/CoverageValidator.php
  src/Validators/InsuranceValidator.php
Labels: Status: Needs Review, Status: Needs Work

#4176 EventDispatcher hooks for patient create, and patient update
  interface/new/new_comprehensive_save.php
  interface/patient_file/summary/demographics_save.php
  library/patient.inc
  src/Events/Patient/PatientCreatedEvent.php
  src/Events/Patient/PatientUpdatedEvent.php
  src/Services/BaseService.php
  src/Services/PatientService.php
  tests/eventdispatcher/oe-patient-create-update-hooks-example/README.md
  tests/eventdispatcher/oe-patient-create-update-hooks-example/composer.json
  tests/eventdispatcher/oe-patient-create-update-hooks-example/openemr.bootstrap.php
Labels: Status: Needs Review

#4188 autopopulate ndc from drugs table
  interface/forms/fee_sheet/new.php
  library/FeeSheet.class.php
Labels: Status: Needs Review

#4190 Fixing multiple problems with database conversion from old releases.
  library/sql_upgrade_fx.php
Labels: Status: Needs Review, Status: Reviewed

#4193 Esign Bug
  library/ESign/Form/Signable.php
Labels: Status: Needs Review, Status: Reviewed

#4199 Refactor portal base controller scope
  portal/patient/_global_config.php
  portal/patient/fwk/libs/verysimple/Phreeze/PortalController.php
  portal/patient/libs/Controller/AppBasePortalController.php
  portal/patient/libs/Controller/DefaultController.php
  portal/patient/libs/Controller/OnsiteActivityViewController.php
  portal/patient/libs/Controller/OnsiteDocumentController.php
  portal/patient/libs/Controller/OnsitePortalActivityController.php
  portal/patient/libs/Controller/PatientController.php
  portal/patient/libs/Controller/PortalPatientController.php
  portal/patient/libs/Controller/ProviderController.php
Labels: Status: Needs Review

#4177 Smart standalone patientrole migrate
  API_README.md
  FHIR_README.md
  _rest_config.php
  _rest_routes.inc.php
  apis/dispatch.php
  ci/ciLibrary.source
  docker/development-easy-arm32/docker-compose.yml
  docker/development-easy-arm64/docker-compose.yml
  docker/development-easy-light/docker-compose.yml
  docker/development-easy/docker-compose.yml
  docker/development-insane/docker-compose.yml
  interface/smart/admin-client.php
  interface/smart/register-app.php
  library/globals.inc.php
  oauth2/authorize.php
  oauth2/provider/scope-authorize.php
  oauth2/smart/patient-select.php
  src/Common/Acl/AccessDeniedException.php
  src/Common/Acl/AclMain.php
  src/Common/Auth/OpenIDConnect/Entities/UserEntity.php
  src/Common/Auth/OpenIDConnect/Grant/CustomRefreshTokenGrant.php
  src/Common/Auth/OpenIDConnect/IdTokenSMARTResponse.php
  src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
  src/Common/Auth/UuidUserAccount.php
  src/Common/Http/HttpRestParsedRoute.php
  src/Common/Http/HttpRestRequest.php
  src/Common/Http/HttpRestRouteHandler.php
  src/Common/Logging/SystemLogger.php
  src/Common/Session/SessionUtil.php
  src/Events/RestApiExtend/RestApiCreateEvent.php
  src/FHIR/SMART/Capability.php
  src/FHIR/SMART/SmartLaunchController.php
  src/Gacl/Gacl.php
  src/RestControllers/AuthorizationController.php
  src/RestControllers/FHIR/FhirPersonRestController.php
  src/RestControllers/SMART/PatientContextSearchController.php
  src/RestControllers/SMART/SMARTAuthorizationController.php
  src/Services/ConditionService.php
  src/Services/FHIR/FhirPersonService.php
  src/Services/UserService.php
  tests/Tests/Api/ApiTestClient.php
  tests/Tests/Unit/Common/Acl/AclMainTest.php
  tests/Tests/Unit/Common/Auth/OpenIDConnect/Entities/ClientEntityTest.php
  tests/api/InternalApiTest.php
Labels: Status: Needs Review

#4185 Billing process refactor and enhancements
  controllers/C_X12Partner.class.php
  interface/billing/billing_process.php
  interface/billing/billing_report.php
  interface/billing/billing_tracker.php
  interface/billing/get_claim_file.php
  interface/billing/ub04_dispose.php
  interface/billing/ub04_form.php
  interface/billing/ub04_submit.php
  interface/main/tabs/menu/menus/standard.json
  interface/super/edit_globals.php
  library/ajax/billing_tracker_ajax.php
  library/billing_sftp_service.php
  library/classes/X12Partner.class.php
  library/globals.inc.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Billing/BillingProcessor/BillingClaim.php
  src/Billing/BillingProcessor/BillingClaimBatch.php
  src/Billing/BillingProcessor/BillingLogger.php
  src/Billing/BillingProcessor/BillingProcessor.php
  src/Billing/BillingProcessor/GeneratorCanValidateInterface.php
  src/Billing/BillingProcessor/GeneratorInterface.php
  src/Billing/BillingProcessor/LoggerInterface.php
  src/Billing/BillingProcessor/ProcessingTaskInterface.php
  src/Billing/BillingProcessor/Tasks/AbstractGenerator.php
  src/Billing/BillingProcessor/Tasks/AbstractProcessingTask.php
  src/Billing/BillingProcessor/Tasks/GeneratorExternal.php
  src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF.php
  src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF_IMG.php
  src/Billing/BillingProcessor/Tasks/GeneratorUB04Form_PDF.php
  src/Billing/BillingProcessor/Tasks/GeneratorUB04NoForm.php
  src/Billing/BillingProcessor/Tasks/GeneratorUB04X12.php
  src/Billing/BillingProcessor/Tasks/GeneratorX12.php
  src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php
  src/Billing/BillingProcessor/Tasks/TaskMarkAsClear.php
  src/Billing/BillingProcessor/Tasks/TaskReopen.php
  src/Billing/BillingProcessor/Traits/WritesToBillingLog.php
  src/Billing/BillingProcessor/X12RemoteTracker.php
  src/Billing/BillingReport.php
  src/Billing/Claim.php
  src/Billing/X125010837P.php
  src/Services/BaseService.php
  templates/x12_partners/general_edit.html
  templates/x12_partners/general_list.html
Labels: Status: Needs Review, Status: Needs Work
