Repository openemr/openemr, pull requests merged in 2021-04, with the labels that each got.

#4304 a14-onc2015 - Implantable device list
  interface/easipro/pro.php
  interface/patient_file/report/custom_report.php
  interface/patient_file/summary/add_edit_issue.php
  library/ajax/udi.php
  library/dialog.js
  portal/home.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/MedicalDevice/MedicalDevice.php
  version.php
Labels: Status: Needs Review

#4314 Improvements mostly concerning inventory.
  acl_upgrade.php
  interface/drugs/add_edit_drug.php
  interface/drugs/add_edit_lot.php
  interface/drugs/destroy_lot.php
  interface/drugs/drug_inventory.php
  interface/drugs/drugs.inc.php
  interface/forms/LBF/new.php
  interface/forms/fee_sheet/contraception_products/ajax/find_contraception_products.php
  interface/forms/fee_sheet/contraception_products/css/contraception_products.css
  interface/forms/fee_sheet/contraception_products/initialize_contraception_products.php
  interface/forms/fee_sheet/contraception_products/js/view_model.js
  interface/forms/fee_sheet/contraception_products/templates/contraception_products.php
  interface/forms/fee_sheet/new.php
  interface/main/tabs/menu/menus/standard.json
  interface/patient_file/encounter/find_code_popup.php
  interface/patient_file/pos_checkout_ippf.php
  interface/reports/appointments_report.php
  interface/reports/appt_encounter_report.php
  interface/reports/collections_report.php
  interface/reports/inventory_activity.php
  interface/reports/inventory_list.php
  interface/super/edit_list.php
  interface/usergroup/adminacl.php
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin.php
  interface/usergroup/usergroup_admin_add.php
  library/FeeSheet.class.php
  library/FeeSheetHtml.class.php
  library/calendar.inc
  library/classes/Installer.class.php
  library/globals.inc.php
  library/patient.inc
  sites/default/documents/custom_menus/Custom.json
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Billing/BillingUtilities.php
  src/Billing/SLEOB.php
  src/Common/Acl/AclMain.php
  version.php
Labels: Status: Needs Review

#4323 New Clinical Notes
  interface/forms/clinical_notes/info.txt
  interface/forms/clinical_notes/new.php
  interface/forms/clinical_notes/report.php
  interface/forms/clinical_notes/save.php
  interface/forms/clinical_notes/table.sql
  interface/forms/clinical_notes/view.php
  interface/forms/vitals/templates/vitals/general_new.html
  library/custom_template/custom_template.php
  library/js/CustomTemplateApi.js
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review

#4319 Fix to custom filter (via module/event)
  interface/main/finder/dynamic_finder_ajax.php
Labels: Status: Needs Review

#4324 several things
  interface/drugs/add_edit_lot.php
  interface/drugs/drug_inventory.php
  interface/forms/clinical_notes/new.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#4322 use int cast for compares with php8 fatal errors in payment scripts
  interface/billing/payment_pat_sel.inc.php
  library/js/common.js
  library/payment.inc.php
Labels: Status: Needs Review

#4326 centralized xml escaping. also couple sql escaping fixes
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  library/htmlspecialchars.inc.php
Labels: Status: Needs Review

#4329 Fixing import bug in backup.php.
  interface/main/backup.php
Labels: Bug

#4333 Add events on before-patient-create and before-patient-update
  src/Events/Patient/BeforePatientCreatedEvent.php
  src/Events/Patient/BeforePatientUpdatedEvent.php
  src/Services/PatientService.php
Labels: Status: Needs Review

#4335 couple places top_restore was needed
  interface/main/tabs/js/tabs_view_model.js
Labels: Status: Needs Review

#4332 Update packages
  composer.json
  composer.lock
  gulpfile.js
  interface/main/calendar/config.php
  interface/main/calendar/includes/pnAPI.php
  library/ADODB_mysqli_log.php
  library/ADODB_mysqli_mod.php
  library/dicom_frame.php
  library/sql.inc
  package-lock.json
  package.json
  src/Core/TwigExtension.php
  src/Gacl/Gacl.php
  templates/documents/general_list.html
  templates/documents/general_upload.html
Labels: Status: Needs Review

#4266 Donate to open emr
  interface/forms/gad7/gad7.inc.php
  interface/forms/gad7/gad7_javasrc.js
  interface/forms/gad7/info.txt
  interface/forms/gad7/new.php
  interface/forms/gad7/report.php
  interface/forms/gad7/save.php
  interface/forms/gad7/table.sql
  interface/forms/gad7/view.php
Labels: Status: Needs Review, Status: Needs Work

#4353 billing contrast css
  interface/billing/billing_report.php
Labels: Status: Needs Review

#4352 a few billing fixes
  interface/patient_file/history/encounters.php
  library/patient.inc
  src/Billing/InvoiceSummary.php
Labels: Status: Needs Review

#4357 Fixes for LBF rendering.
  interface/forms/LBF/new.php
  library/FeeSheetHtml.class.php
Labels: Status: Needs Review

#4361 Integrate traditional and layout-based forms into their chosen categories in the visit summary dropdowns.
  interface/patient_file/encounter/forms.php
  library/registry.inc
Labels: Status: Needs Review
