Repository openemr/openemr, pull requests merged in 2021-08, with the labels that each got.

#4562 Openemr fhir provenance
  _rest_routes.inc.php
  src/Common/Http/HttpRestParsedRoute.php
  src/RestControllers/FHIR/FhirProvenanceRestController.php
  src/RestControllers/RestControllerHelper.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/FHIR/FhirProvenanceService.php
  tests/Tests/Unit/Common/Http/HttpRestParsedRouteTest.php
Labels: Status: Needs Review

#4505 Issue 4469 (#16)
  interface/patient_file/merge_patients.php
Labels: Status: Needs Review, Status: Needs Work

#4558 Openemr fhir medication request
  interface/forms/eye_mag/save.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/patient_file/deleter.php
  interface/patient_file/summary/add_edit_issue.php
  interface/patient_file/summary/add_edit_issue_medication_fragment.php
  oauth2/provider/scope-authorize.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
  src/RestControllers/AuthorizationController.php
  src/Services/BaseService.php
  src/Services/FHIR/FhirCodeSystemConstants.php
  src/Services/FHIR/FhirMedicationRequestService.php
  src/Services/FHIR/UtilsService.php
  src/Services/ListService.php
  src/Services/MedicationPatientIssueService.php
  src/Services/PatientIssuesService.php
  src/Services/PrescriptionService.php
  version.php
Labels: Status: Needs Review, Status: Needs Work

#4565 make active default setting for care_team_status
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review

#4574 Fix #4573 Openemr fhir token revocation
  _rest_config.php
  apis/dispatch.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Common/Auth/OAuth2KeyConfig.php
  src/Common/Auth/OAuth2KeyException.php
  src/Common/Auth/OpenIDConnect/Entities/ClientEntity.php
  src/Common/Auth/OpenIDConnect/JWT/JsonWebKeyParser.php
  src/Common/Auth/OpenIDConnect/Repositories/AccessTokenRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/ClientRepository.php
  src/Common/Auth/OpenIDConnect/Repositories/RefreshTokenRepository.php
  src/Common/Database/QueryUtils.php
  src/FHIR/SMART/ClientAdminController.php
  src/RestControllers/AuthorizationController.php
  src/Services/TrustedUserService.php
  version.php
Labels: Status: Needs Review, Status: Needs Work

#4580 Disallow administration of users having permissions that the logged-i…
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin.php
  library/ajax/adminacl_ajax.php
  src/Common/Acl/AclExtended.php
Labels: Status: Needs Review

#4579 Openemr fhir offline refresh scope
  interface/smart/register-app.php
  oauth2/provider/scope-authorize.php
  src/Common/Auth/OpenIDConnect/Repositories/RefreshTokenRepository.php
  src/FHIR/SMART/ClientAdminController.php
  src/RestControllers/AuthorizationController.php
  tests/Tests/Api/ApiTestClient.php
  tests/Tests/Api/ApiTestClientTest.php
  tests/Tests/Api/IntrospectionTest.php
Labels: Status: Needs Review

#4575 turn on care coordination modules by default
  docker/development-easy-arm32/docker-compose.yml
  docker/development-easy-arm64/docker-compose.yml
  docker/development-easy-light/docker-compose.yml
  docker/development-easy/docker-compose.yml
  docker/development-insane/docker-compose.yml
  library/classes/Installer.class.php
  setup.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#4576 fix array index for orphan labs for patient matching
  interface/orders/list_reports.php
  interface/orders/patient_match_dialog.php
  interface/orders/receive_hl7_results.inc.php
Labels: Status: Needs Review

#4583 possible pathing fix
  src/Common/Auth/OpenIDConnect/IdTokenSMARTResponse.php
Labels: Status: Needs Review

#4553 era posting work and misc php8 fixes
  interface/billing/billing_report.php
  interface/billing/sl_eob_process.php
  interface/billing/sl_eob_search.php
  interface/forms/fee_sheet/new.php
  interface/forms/fee_sheet/review/fee_sheet_queries.php
  interface/main/calendar/modules/PostCalendar/pnadminapi.php
  interface/main/calendar/modules/PostCalendar/pnuser.php
  interface/main/calendar/modules/PostCalendar/pnuserapi.php
  interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
  interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
  interface/patient_file/deleter.php
  interface/patient_file/history/encounters.php
  library/MedEx/API.php
  library/globals.inc.php
  library/options.inc.php
  library/patient.inc
  sites/default/statement.inc.php
  src/Billing/Claim.php
  src/Billing/InvoiceSummary.php
  src/Billing/ParseERA.php
  src/Menu/MainMenuRole.php
Labels: Status: Needs Review

#4587 fix so displays inactive provider who performed visit on encounter page
  library/FeeSheetHtml.class.php
  library/globals.inc.php
  library/patient.inc
  version.php
Labels: Status: Needs Review

#4596 Update API.php
  library/MedEx/API.php
Labels: Status: Needs Review

#4599 Openemr single patient
  library/sql_upgrade_fx.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  src/Services/CareTeamService.php
  src/Services/CodeTypesService.php
  src/Services/FHIR/FhirMedicationRequestService.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/FHIR/Procedure/FhirProcedureOEProcedureService.php
  src/Services/PatientService.php
  src/Services/PrescriptionService.php
  src/Services/ProcedureService.php
  version.php
Labels: Status: Needs Review

#4588 CQM support
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  library/layout.inc.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Common/System/System.php
  src/Services/EncounterService.php
Labels: Status: Needs Review

#4600 Bulk Export, Security Fixes, Group endpoint support
  _rest_routes.inc.php
  interface/smart/register-app.php
  library/standard_tables_capture.inc
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Common/Auth/OpenIDConnect/Grant/CustomAuthCodeGrant.php
  src/Common/Auth/OpenIDConnect/Grant/CustomClientCredentialsGrant.php
  src/Common/Auth/OpenIDConnect/JWT/JsonWebKeySet.php
  src/Common/Auth/OpenIDConnect/JWT/Validation/UniqueID.php
  src/Common/Auth/OpenIDConnect/Repositories/JWTRepository.php
  src/Common/Uuid/UuidMapping.php
  src/FHIR/Export/ExportJob.php
  src/FHIR/SMART/SMARTLaunchToken.php
  src/FHIR/SMART/SmartLaunchController.php
  src/RestControllers/AuthorizationController.php
  src/RestControllers/FHIR/FhirExportRestController.php
  src/RestControllers/FHIR/FhirGroupRestController.php
  src/RestControllers/PractitionerRestController.php
  src/RestControllers/RestControllerHelper.php
  src/Services/CareTeamService.php
  src/Services/FHIR/DocumentReference/FhirPatientDocumentReferenceService.php
  src/Services/FHIR/FhirCarePlanService.php
  src/Services/FHIR/FhirConditionService.php
  src/Services/FHIR/FhirDeviceService.php
  src/Services/FHIR/FhirEncounterService.php
  src/Services/FHIR/FhirGoalService.php
  src/Services/FHIR/FhirGroupService.php
  src/Services/FHIR/FhirImmunizationService.php
  src/Services/FHIR/FhirMedicationRequestService.php
  src/Services/FHIR/FhirPatientService.php
  src/Services/FHIR/FhirPractitionerService.php
  src/Services/FHIR/FhirProcedureService.php
  src/Services/FHIR/Group/FhirPatientProviderGroupService.php
  src/Services/FHIR/Observation/FhirObservationSocialHistoryService.php
  src/Services/FHIR/Organization/FhirOrganizationFacilityService.php
  src/Services/FHIR/Organization/FhirOrganizationInsuranceService.php
  src/Services/FHIR/Organization/FhirOrganizationProcedureProviderService.php
  src/Services/FHIR/Traits/FhirBulkExportDomainResourceTrait.php
  src/Services/FHIR/UtilsService.php
  src/Services/GroupService.php
  src/Services/PractitionerService.php
  src/Services/Search/CompositeSearchField.php
  src/Services/Search/SearchFieldStatementResolver.php
  tests/Tests/Api/PractitionerApiTest.php
  tests/Tests/Fixtures/practitioners.json
  tests/Tests/RestControllers/PractitionerRestControllerTest.php
  tests/Tests/Unit/Common/Auth/OpenIDConnect/Grant/CustomClientCredentialsGrantTest.php
  version.php
Labels: Status: Needs Review, 2015 ONC
