Repository openemr/openemr, pull requests merged in 2021-05, with the labels that each got.

#4364 Updated Readme File - grammatical error in sentence
  README.md
Labels: Status: Needs Review

#4372 Issue #4316: Minor amendment to FHIR API docs
  FHIR_README.md
Labels: Status: Needs Review

#4355 restoresession cleanup in patient tracker
  interface/main/messages/js/reminder_appts.js
  interface/patient_tracker/patient_tracker.php
Labels: Status: Needs Review

#4377 Session fix
  interface/main/finder/dynamic_finder.php
  interface/main/finder/dynamic_finder_ajax.php
Labels: Status: Needs Review

#4360 These are some minor adjustments to the feature bug fixes
  interface/weno/facilities.php
  interface/weno/rxlogmanager.php
  interface/weno/wenoconnected.php
  src/Rx/Weno/Container.php
  src/Rx/Weno/TransmitProperties.php
Labels: Status: Needs Review, Status: Needs Work

#4376 This form is being donated by Dr. Andy Gauler PhD, MS, LMHC
  contrib/forms/dap/C_FormDAP.class.php
  contrib/forms/dap/FormDAP.class.php
  contrib/forms/dap/info.txt
  contrib/forms/dap/new.php
  contrib/forms/dap/report.php
  contrib/forms/dap/save.php
  contrib/forms/dap/table.sql
  contrib/forms/dap/templates/general_new.html
  contrib/forms/dap/view.php
Labels: Status: Needs Review

#4382 CCDA and Other
  ccdaservice/oe-blue-button-generate/lib/condition.js
  ccdaservice/oe-blue-button-generate/lib/documentLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/allergyEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/encounterEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/immunizationEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/index.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/medicalDeviceEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/medicationEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/problemEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/resultEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/sharedEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/socialHistoryEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/vitalSignEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/fieldLevel.js
  ccdaservice/oe-blue-button-generate/lib/headerLevel.js
  ccdaservice/oe-blue-button-generate/lib/htmlHeaders.js
  ccdaservice/oe-blue-button-generate/lib/leafLevel.js
  ccdaservice/oe-blue-button-generate/lib/sectionLevel.js
  ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
  ccdaservice/oe-blue-button-generate/lib/translate.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/clinicalstatements.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/code-systems.js
  ccdaservice/serveccda.js
  interface/forms/procedure_order/common.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  interface/orders/orders_results.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  version.php
Labels: 2015 ONC

#4386 Reports->Clients->Message List
  interface/main/tabs/menu/menus/standard.json
  interface/reports/message_list.php
  interface/reports/patient_list.php
Labels: Status: Needs Review

#4395 store Rxnorm in prescription table from nlm lookup api
  controllers/C_Prescription.class.php
  interface/patient_file/summary/add_edit_issue.php
  library/ajax/prescription_drugname_lookup.php
  src/Rx/RxList.php
  templates/insurance_companies/general_edit.html
  templates/prescription/general_edit.html
  templates/prescription/general_lookup.html
Labels: Status: Needs Review

#4408 Layout editor fixes to preserve sensitive column names.
  interface/super/edit_layout.php
Labels: Bug

#4392 mu3 stuff - ccda import patient name fix, support for birth name and care team status in demographics
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#4407 Implement ONC CareTeam, Fixed PractitionerRole, Fix critical bug in lookup_code_information
  _rest_routes.inc.php
  custom/code_types.inc.php
  src/Common/Http/HttpRestRouteHandler.php
  src/RestControllers/FHIR/FhirCarePlanRestController.php
  src/RestControllers/FHIR/FhirOrganizationRestController.php
  src/Services/CareTeamService.php
  src/Services/ConditionService.php
  src/Services/FHIR/FhirCarePlanService.php
  src/Services/FHIR/FhirCareTeamService.php
  src/Services/FHIR/FhirCodeSystemUris.php
  src/Services/FHIR/FhirConditionService.php
  src/Services/FHIR/FhirImmunizationService.php
  src/Services/FHIR/FhirOrganizationService.php
  src/Services/FHIR/FhirProvenanceService.php
  src/Services/FHIR/FhirServiceBase.php
  src/Services/FHIR/UtilsService.php
  src/Services/FacilityService.php
  src/Services/ImmunizationService.php
  src/Services/InsuranceCompanyService.php
  src/Services/OrganizationService.php
  src/Services/PractitionerRoleService.php
  src/Services/PractitionerService.php
  src/Services/Search/SearchFieldStatementResolver.php
  src/Services/Search/StringSearchField.php
Labels: Status: Needs Review

#4413 Eye Form Patch 2
  interface/forms/eye_mag/a_issue.php
  interface/forms/eye_mag/css/style.css
  interface/forms/eye_mag/save.php
Labels: Status: Needs Review

#4416 CCDA care team
  ccdaservice/oe-blue-button-generate/lib/entryLevel/sharedEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/headerLevel.js
  ccdaservice/serveccda.js
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
Labels: 2015 ONC

#4415 Improved searching for patients by DOB in dynamic finder.
  interface/main/finder/dynamic_finder_ajax.php
Labels: Status: Needs Review

#4420 migrate twig to separate class
  interface/globals.php
  src/Common/Twig/TwigContainer.php
  src/Common/Twig/TwigExtension.php
Labels: Status: Needs Review

#4421 add default search type to session for fee sheet search for add'l codes
  custom/code_types.inc.php
  interface/forms/eye_mag/view.php
  interface/forms/fee_sheet/new.php
Labels: Status: Needs Review

#4423 CCDA Goals
  ccdaservice/oe-blue-button-generate/lib/documentLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/goalEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/index.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/planOfCareEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/fieldLevel.js
  ccdaservice/oe-blue-button-generate/lib/htmlHeaders.js
  ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/code-systems.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/sections.js
  ccdaservice/serveccda.js
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  version.php
Labels: 2015 ONC, Status: Needs Review

#4425 Adding updates to Weno eRx service
  src/Rx/Weno/Container.php
  src/Rx/Weno/TransmitProperties.php
Labels: Status: Needs Review

#4430 move label to avoid calling multi_patient_finder; prettify dated_remi…
  interface/main/dated_reminders/dated_reminders.php
  interface/main/messages/messages.php
Labels: Status: Needs Review

#4429 Calinc
  interface/main/calendar/modules/PostCalendar/pnuserapi.php
  interface/patient_file/encounter/forms.php
  library/ajax/adminacl_ajax.php
  library/appointments.inc.php
  library/calendar.inc
  library/encounter_events.inc.php
  src/Common/Acl/AclExtended.php
  src/Services/UserService.php
Labels: Status: Needs Review, Status: Needs Work
