Repository openemr/openemr, pull requests merged in 2021-06, with the labels that each got.

#4435 Fix for "Site ID is missing from session data!" when session expires.
  interface/main/tabs/main.php
  interface/main/tabs/timeout_iframe.php
  library/auth.inc
Labels: Status: Needs Review

#4432 ccda importing from commandline and other stuff
  contrib/util/ccda_import/import_ccda.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/module/Installer/Module.php
  interface/modules/zend_modules/module/Installer/config/module.config.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#4439 updated timeout mechanism
  interface/main/tabs/js/user_data_view_model.js
  interface/main/tabs/main.php
  library/ajax/dated_reminders_counter.php
  library/auth.inc
  src/Common/Session/SessionTracker.php
Labels: Status: Needs Review

#4427 New CCDA Templates
  ccdaservice/oe-blue-button-generate/lib/documentLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/functionalStatusEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/index.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/planOfCareEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/htmlHeaders.js
  ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/code-systems.js
  ccdaservice/serveccda.js
  interface/forms/functional_cognitive_status/new.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  interface/patient_file/front_payment.php
  portal/lib/download_template.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
Labels: 2015 ONC

#4445 optimize dev bulk ccda import
  contrib/util/ccda_import/import_ccda.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/module/Installer/Module.php
  interface/modules/zend_modules/module/Installer/config/module.config.php
Labels: Status: Needs Review

#4443 Create menu items for Blank Forms, and organize that and Visit Forms by category.
  interface/main/tabs/menu/menus/standard.json
  interface/patient_file/summary/demographics_print.php
  interface/themes/tabs_style_compact.scss
  interface/themes/tabs_style_full.scss
  sites/default/documents/custom_menus/Custom.json
  src/Menu/MainMenuRole.php
Labels: Status: Needs Review

#4459 Temporary fix for deprecated warnings turning into exceptions.
  interface/globals.php
Labels: Status: Needs Review

#4291 add insurance companies to patient list creation
  interface/reports/clinical_reports.php
  interface/reports/patient_list_creation.php
  library/js/report_helper.js
Labels: Status: Needs Review

#4465 Tag documents to procedures
  controllers/C_Document.class.php
  interface/forms/procedure_order/common.php
  interface/orders/find_order_popup.php
  interface/orders/types.php
  interface/orders/types_edit.php
  interface/patient_file/encounter/find_code_history.php
  library/classes/Document.class.php
  templates/documents/general_view.html
Labels: 2015 ONC

#4463 This is a rewrite of the log sync feature. It is broken up into small…
  interface/super/edit_globals.php
  library/weno_log_sync.php
  src/Rx/Weno/LogDataInsert.php
  src/Rx/Weno/LogImportBuild.php
  src/Rx/Weno/LogProperties.php
Labels: Status: Needs Review

#4467 Turn on templating by default
  interface/forms/care_plan/new.php
  library/globals.inc.php
  sql/6_0_0-to-6_1_0_upgrade.sql
Labels: Status: Needs Review

#4442 UUID bulk fast gen
  library/sql.inc
  src/Common/Database/QueryUtils.php
  src/Common/Uuid/UuidRegistry.php
Labels: Status: Needs Review

#4488 Move ins type codes to database
  controllers/C_InsuranceCompany.class.php
  controllers/C_X12Partner.class.php
  interface/practice/ins_search.php
  library/classes/InsuranceCompany.class.php
  library/classes/Pharmacy.class.php
  sql/5_0_2-to-6_0_0_upgrade.sql
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Services/InsuranceCompanyService.php
  version.php
Labels: Status: Needs Review, Status: Needs Work
