Repository openemr/openemr, pull requests merged in 2021-03, with the labels that each got.

#4219 Eye Progress 1
  .gitignore
  config/config.yaml
  interface/forms/eye_mag/SpectacleRx.php
  interface/forms/eye_mag/a_issue.php
  interface/forms/eye_mag/css/style.css
  interface/forms/eye_mag/js/eye_base.php
  interface/forms/eye_mag/js/jquery-1-10-2/jquery.min.js
  interface/forms/eye_mag/js/jquery-panelslider/jquery.panelslider.min.js
  interface/forms/eye_mag/js/jquery-ui-1-11-4/jquery-ui.min.js
  interface/forms/eye_mag/js/shortcut.js-2-01-B/shortcut.js
  interface/forms/eye_mag/php/eye_mag_functions.php
  interface/forms/eye_mag/php/taskman_functions.php
  interface/forms/eye_mag/report.php
  interface/forms/eye_mag/save.php
  interface/forms/eye_mag/view.php
  interface/main/messages/css/reminder_style.css
  interface/main/messages/js/reminder_appts.js
  interface/patient_file/encounter/forms.php
  interface/patient_tracker/patient_tracker.php
  interface/super/edit_list.php
  interface/themes/tabs_style_compact.scss
  interface/themes/tabs_style_full.scss
  library/MedEx/API.php
  library/MedEx/MedEx.php
  library/MedEx/MedEx_background.php
  public/assets/manual-added-packages/undone.js-0-0-1/.bower.json
  public/assets/manual-added-packages/undone.js-0-0-1/README.md
  public/assets/manual-added-packages/undone.js-0-0-1/grain.jpg
  public/assets/manual-added-packages/undone.js-0-0-1/index.html
  public/assets/manual-added-packages/undone.js-0-0-1/jquery.undone.js
  public/assets/manual-added-packages/undone.js-0-0-1/redo.jquery.json
  public/assets/manual-added-packages/undone.js-0-0-1/undo.jquery.json
  public/assets/manual-added-packages/undone.js-0-0-1/undone.jquery.json
  public/assets/manual-added-packages/undone.js-0-0-1/undone.js
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  templates/prescription/general_list.html
  version.php
Labels: Status: Needs Review

#4233 SurgeryFHIR
  src/Services/FHIR/FhirProcedureService.php
  src/Services/SurgeryService.php
Labels: Status: Needs Review

#4263 MedEx for 6.0.0
  library/MedEx/API.php
Labels: Status: Needs Review

#4264 Return to confirm screen in batch payments
  interface/billing/edit_payment.php
  interface/billing/new_payment.php
  interface/billing/payment_pat_sel.inc.php
  interface/billing/search_payments.php
  interface/forms/LBF/new.php
  library/ajax/payment_ajax.php
  library/payment_jav.inc.php
Labels: Status: Needs Review

#4254 a5 onc 2015
  interface/super/edit_layout.php
  library/options.inc.php
  library/options.js.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  version.php
Labels: Status: Needs Review

#4270 medex icon sql fix
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review

#4277 rewording
  README.md
Labels: Status: Needs Review

#4261 Google Sign-In
  composer.json
  composer.lock
  interface/login/login.php
  interface/usergroup/user_admin.php
  interface/usergroup/usergroup_admin.php
  interface/usergroup/usergroup_admin_add.php
  library/auth.inc
  library/globals.inc.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Common/Auth/AuthUtils.php
  src/Services/UserService.php
Labels: Status: Needs Review, Status: Needs Work

#4273 automated uuid updating service
  library/sql_upgrade_fx.php
  library/uuid.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Common/Uuid/UuidRegistry.php
  version.php
Labels: Status: Needs Review

#4279 optimize uuid building
  src/Common/Uuid/UuidRegistry.php
Labels: Status: Needs Review

#4269 MedEx 6.0.0
  interface/forms/eye_mag/php/eye_mag_functions.php
  interface/forms/eye_mag/view.php
  interface/main/messages/css/reminder_style.css
  interface/main/messages/messages.php
  interface/main/messages/save.php
  interface/main/tabs/templates/tabs_template.php
  interface/patient_file/encounter/forms.php
  interface/patient_tracker/patient_tracker.php
  interface/themes/colors/utilities/tabs-full.scss
  interface/themes/oe-styles/style_manila.scss
  interface/themes/tabs_style_compact.scss
  interface/themes/tabs_style_full.scss
  library/MedEx/API.php
  tests/Tests/E2e/Pages/MainPage.php
Labels: Status: Needs Review, Status: Needs Work

#4286 fix ins search when no phone # entered
  interface/practice/ins_list.php
Labels: Status: Needs Review

#4288 fix related to google sign in
  interface/usergroup/usergroup_admin.php
Labels: Status: Needs Review

#4276 Consolidate ccdaservice to file based project
  ccdaservice/README.md
  ccdaservice/oe-blue-button-generate/LICENSE
  ccdaservice/oe-blue-button-generate/dist/blue-button-generate.js
  ccdaservice/oe-blue-button-generate/index.js
  ccdaservice/oe-blue-button-generate/lib/condition.js
  ccdaservice/oe-blue-button-generate/lib/contentModifier.js
  ccdaservice/oe-blue-button-generate/lib/documentLevel.js
  ccdaservice/oe-blue-button-generate/lib/engine.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/allergyEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/encounterEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/immunizationEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/index.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/medicationEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/payerEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/planOfCareEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/problemEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/procedureEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/resultEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/sharedEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/socialHistoryEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/entryLevel/vitalSignEntryLevel.js
  ccdaservice/oe-blue-button-generate/lib/fieldLevel.js
  ccdaservice/oe-blue-button-generate/lib/headerLevel.js
  ccdaservice/oe-blue-button-generate/lib/htmlHeaders.js
  ccdaservice/oe-blue-button-generate/lib/leafLevel.js
  ccdaservice/oe-blue-button-generate/lib/sectionLevel.js
  ccdaservice/oe-blue-button-generate/lib/sectionLevel2.js
  ccdaservice/oe-blue-button-generate/lib/translate.js
  ccdaservice/oe-blue-button-generate/lib/xmlutil.js
  ccdaservice/oe-blue-button-generate/package.json
  ccdaservice/oe-blue-button-meta/LICENSE
  ccdaservice/oe-blue-button-meta/index.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/clinicalstatements.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/code-systems.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/index.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/sections-constraints.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/sections.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/templates-constraints.js
  ccdaservice/oe-blue-button-meta/lib/CCDA/templates.js
  ccdaservice/oe-blue-button-meta/lib/code-systems.js
  ccdaservice/oe-blue-button-meta/lib/oids.js
  ccdaservice/oe-blue-button-meta/package.json
  ccdaservice/oe-blue-button-util/LICENSE
  ccdaservice/oe-blue-button-util/index.js
  ccdaservice/oe-blue-button-util/lib/arrayset.js
  ccdaservice/oe-blue-button-util/lib/datetime.js
  ccdaservice/oe-blue-button-util/lib/jsonpath/index.js
  ccdaservice/oe-blue-button-util/lib/object.js
  ccdaservice/oe-blue-button-util/lib/objectset.js
  ccdaservice/oe-blue-button-util/lib/predicate.js
  ccdaservice/oe-blue-button-util/package.json
  ccdaservice/package.json
  ccdaservice/serveccda.js
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
Labels: 2015 ONC, Feature, For Prior Version

#4287 add password max length setting
  library/globals.inc.php
  src/Common/Auth/AuthUtils.php
  version.php
Labels: Status: Needs Review

#4295 Fix sql error with MySQL 8 when viewing event log.
  src/Common/Logging/EventAuditLogger.php
Labels: Bug, Status: Needs Review

#4293 Multiple improvements for backup and configuration export/import.
  interface/main/backup.php
  library/layout.inc.php
Labels: Status: Needs Review

#4292 billing fix for corrected claims alphanumeric claim no.
  interface/usergroup/facilities.php
  src/Billing/X125010837P.php
Labels: Status: Needs Review

#4297 Improvements related to layouts and some other things
  custom/code_types.inc.php
  interface/forms/LBF/new.php
  interface/forms/LBF/printable.php
  interface/globals.php
  interface/new/new_comprehensive.php
  interface/patient_file/encounter/find_code_dynamic.php
  interface/patient_file/encounter/find_code_dynamic_ajax.php
  interface/patient_file/history/history_save.php
  interface/patient_file/pos_checkout.php
  interface/patient_file/pos_checkout_ippf.php
  interface/patient_file/pos_checkout_normal.php
  interface/patient_file/transaction/add_transaction.php
  interface/patient_file/void_dialog.php
  interface/super/edit_layout.php
  interface/super/edit_layout_props.php
  interface/super/edit_list.php
  interface/super/layout_service_codes.php
  interface/usergroup/addrbook_list.php
  library/FeeSheet.class.php
  library/checkout_receipt_array.inc.php
  library/contraception_billing_scan.inc.php
  library/globals.inc.php
  library/layout.inc.php
  library/options.inc.php
  library/options.js.php
  library/patient.inc
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  sql/ippf_upgrade.sql
  src/Menu/MainMenuRole.php
  src/Menu/PatientMenuRole.php
  version.php
Labels: Status: Needs Review

#4306 change received message into textarea for easier viewing in messages
  interface/main/messages/messages.php
Labels: Status: Needs Review

#4309 Various bug fixes
  library/js/utility.js
  portal/lib/download_template.php
  portal/patient/libs/Controller/ProviderController.php
  portal/patient/templates/DefaultHome.tpl.php
  portal/patient/templates/OnsiteDocumentListView.tpl.php
  portal/patient/templates/SecureApp.tpl.php
Labels: Status: Needs Review

#4301 fix paper claims and log in billing manager, add fax for insurance companies in practice settings
  interface/billing/billing_process.php
  library/classes/InsuranceCompany.class.php
  library/classes/PhoneNumber.class.php
  src/Billing/BillingProcessor/BillingClaim.php
  src/Billing/BillingProcessor/BillingLogger.php
  src/Billing/BillingProcessor/BillingProcessor.php
  src/Billing/BillingProcessor/Tasks/AbstractGenerator.php
  src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php
  src/Billing/BillingUtilities.php
  src/Billing/Claim.php
  src/Billing/X125010837P.php
  templates/insurance_companies/general_edit.html
  templates/insurance_companies/general_list.html
Labels: Status: Needs Review
