Repository openemr/openemr, pull requests merged in 2021-11, with the labels that each got.

#4612 some future proofing stuff
  .github/workflows/syntax.yml
  .github/workflows/test.yml
  ci/apache_73_105/docker-compose.yml
  ci/apache_74_106/docker-compose.yml
  ci/nginx_73/docker-compose.yml
  ci/nginx_73/php.ini
  ci/nginx_74/docker-compose.yml
  ci/nginx_80/docker-compose.yml
  ci/nginx_81/docker-compose.yml
  composer.json
  composer.lock
  docker/development-easy-light/docker-compose.yml
  docker/development-easy/docker-compose.yml
  docker/development-insane/docker-compose.yml
  interface/themes/compact-theme-defaults.scss
  package-lock.json
  package.json
  src/Common/Auth/OpenIDConnect/IdTokenSMARTResponse.php
  src/Common/Auth/OpenIDConnect/JWT/JsonWebKeyParser.php
  src/Common/Auth/OpenIDConnect/JWT/JsonWebKeySet.php
  src/Common/Auth/OpenIDConnect/JWT/RsaSha384Signer.php
  src/Common/Auth/OpenIDConnect/JWT/Validation/UniqueID.php
  src/Common/Compatibility/Checker.php
Labels: Status: Needs Review

#4716 Move patient date methods into service
  library/patient.inc
  src/Services/PatientService.php
Labels: Status: Needs Review

#4715 Twig module author extensions
  src/Common/Twig/TwigContainer.php
  src/Common/Twig/TwigExtension.php
  src/Events/Core/TwigEnvironmentEvent.php
  templates/error/400.html.twig
  templates/error/general_http_error.html.twig
Labels: Status: Needs Review

#4718 Make fhir search service classes easier to use
  src/Services/Search/FhirSearchWhereClauseBuilder.php
Labels: Status: Needs Review

#4714 Created calendar extension points for modules.
  interface/main/calendar/add_edit_event.php
  interface/main/calendar/modules/PostCalendar/pnadmin.php
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/day_print/outlook_ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/header.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/month_print/outlook_ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week/ajax_template.html
  interface/main/calendar/modules/PostCalendar/pntemplates/default/views/week_print/outlook_ajax_template.html
  interface/main/calendar/modules/PostCalendar/pnuserapi.php
  src/Core/ModulesApplication.php
  src/Events/Appointments/CalendarUserGetEventsFilter.php
  src/Events/Core/ScriptFilterEvent.php
  src/Events/Core/StyleFilterEvent.php
  src/Events/Core/TemplatePageEvent.php
Labels: Status: Needs Review

#4722 control upload button era posting, fix search result headers and buttons, default…
  interface/billing/sl_eob_search.php
  interface/main/calendar/modules/PostCalendar/common.api.php
  interface/patient_file/report/patient_report.php
  interface/reports/report.script.php
Labels: Status: Needs Review

#4719 Encounter Appointment enhancements
  interface/modules/zend_modules/config/application.config.php
  interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
  interface/modules/zend_modules/module/Installer/view/installer/installer/index.phtml
  interface/modules/zend_modules/module/PatientFlowBoard/Module.php
  interface/modules/zend_modules/module/PatientFlowBoard/config/module.config.php
  interface/modules/zend_modules/module/PatientFlowBoard/src/PatientFlowBoard/Listener/PatientFlowBoardEventsSubscriber.php
  library/patient_tracker.inc.php
  src/RestControllers/EncounterRestController.php
  src/Services/AddressService.php
  src/Services/AppointmentService.php
  src/Services/EncounterService.php
  src/Services/PatientTrackerService.php
  src/Services/UserService.php
  src/Validators/EncounterValidator.php
Labels: Status: Needs Review

#4724 Openemr fix 4723 module install script uses OpenEMR sql upgrade service
  interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
  interface/modules/zend_modules/module/Installer/src/Installer/Model/InstModuleTable.php
  interface/modules/zend_modules/public/index.php
  library/sql_upgrade_fx.php
  sql_upgrade.php
  src/Services/Utils/SQLUpgradeService.php
Labels: Status: Needs Review

#4726 Fix #4725 user events, uuid generation
  interface/usergroup/usergroup_admin.php
  src/Events/User/UserCreatedEvent.php
  src/Events/User/UserUpdatedEvent.php
Labels: Status: Needs Review

#4742 A couple of small bug fixes for layouts
  library/options.inc.php
Labels: Bug

#4741 Encounter Screen UI Improvements
  interface/patient_file/encounter/forms.php
  library/ESign/views/form/esign_button.php
  src/Common/Twig/TwigExtension.php
  templates/encounter/forms/navbar.html.twig
Labels: Status: Needs Review, Status: Needs Work

#4740 Insurance section cleanup for medical dashboard overhaul plus misc php8 fixes
  controllers/C_Document.class.php
  interface/billing/sl_eob_process.php
  interface/main/tabs/menu/menus/standard.json
  interface/patient_file/summary/demographics.php
  src/Billing/ParseERA.php
  templates/patient/card/insurance.html.twig
Labels: Status: Needs Review

#4772 Changing the order from ascending to descending
  interface/billing/billing_tracker.php
Labels: Status: Ready for Integration
