Repository openemr/openemr, pull requests merged in 2021-09, with the labels that each got.

#4615 bring on some more api documentation
  API_README.md
  FHIR_README.md
  _rest_routes.inc.php
  src/Services/AppointmentService.php
  swagger/index.html
  swagger/openemr-api.yaml
Labels: Status: Needs Work

#4607 Twig Enhancements
  src/Common/Twig/TwigContainer.php
  src/Common/Twig/TwigExtension.php
  src/Core/Kernel.php
Labels: Status: Needs Review, UI Modernization

#4626 Tab UI improvement
  interface/main/tabs/main.php
  interface/main/tabs/templates/patient_data_template.php
  interface/main/tabs/templates/tabs_template.php
  interface/main/tabs/templates/user_data_template.php
  interface/themes/oe-styles/style_light.scss
Labels: Status: Ready for Integration, Tab Layout, UI Modernization

#4623 Medical Dashboard UI Improvements
  interface/patient_file/summary/dashboard_header.php
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/stats.php
  interface/patient_file/summary/vitals_fragment.php
  library/ajax/user_settings.php
  library/classes/Controller.class.php
  library/clinical_rules.php
  library/options.inc.php
  library/patient.inc
  src/Common/Twig/TwigExtension.php
  src/Menu/PatientMenuRole.php
  src/OeUI/OemrUI.php
  templates/core/unauthorized.html.twig
  templates/patient/card/adv_dir.html.twig
  templates/patient/card/amendments.html.twig
  templates/patient/card/appointments.html.twig
  templates/patient/card/appointments_past.html.twig
  templates/patient/card/billing.html.twig
  templates/patient/card/card_base.html.twig
  templates/patient/card/demographics.html.twig
  templates/patient/card/eligibility.html.twig
  templates/patient/card/erx.html.twig
  templates/patient/card/immunizations.html.twig
  templates/patient/card/insurance.html.twig
  templates/patient/card/loader.html.twig
  templates/patient/card/medical_problems.html.twig
  templates/patient/card/photo.html.twig
  templates/patient/card/recall.html.twig
  templates/patient/card/rx.html.twig
  templates/patient/card/tab_base.html.twig
  templates/patient/card/tp_il.html.twig
  templates/patient/dashboard_header.html.twig
  templates/prescription/general_fragment.html
Labels: Status: Needs Review, UI Modernization

#4629 fix upgrade version selected in dropdown and misc php8 fixes
  interface/patient_file/summary/dashboard_header.php
  sql_upgrade.php
  src/Core/Kernel.php
Labels: Status: Needs Review

#4635 Bootstrapping LBF data entry
  interface/forms/LBF/new.php
  interface/new/new_comprehensive.php
  interface/patient_file/history/history_full.php
  interface/patient_file/summary/demographics_full.php
  interface/super/edit_layout_props.php
  library/options.inc.php
  library/options.js.php
  sql/database.sql
Labels: Status: Needs Review, UI Modernization

#4631 Openemr events scope vitals
  _rest_config.php
  apis/dispatch.php
  src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
  src/Common/Database/QueryUtils.php
  src/Common/Http/HttpRestRequest.php
  src/Events/RestApiExtend/RestApiScopeEvent.php
  src/Events/Services/ServiceSaveEvent.php
Labels: Status: Needs Review

#4645 Fix php8 issue with front payment.
  interface/patient_file/front_payment.php
Labels: Status: Ready for Integration

#4644 Openemr encounters twig kernel
  interface/forms/newpatient/common.php
  interface/forms/newpatient/save.php
  src/Common/Twig/TwigContainer.php
  src/FHIR/SMART/SmartLaunchController.php
  src/Services/EncounterService.php
Labels: Status: Needs Review

#4646 QRDA import
  interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/module/Documents/src/Documents/Controller/DocumentsController.php
  interface/modules/zend_modules/module/Documents/src/Documents/Model/DocumentsTable.php
  interface/modules/zend_modules/public/xsl/qrda.xsl
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Services/Cda/CdaTemplateParse.php
  src/Services/CodeTypesService.php
  version.php
Labels: 2015 ONC
