Repository openemr/openemr, pull requests merged in 2022-10, with the labels that each got.

#5751 Custom patient report cleanup (Fixes: #5744, #5765, #5766)
  interface/patient_file/report/custom_report.php
  interface/super/edit_layout_props.php
  library/options.inc.php
  sql/7_0_0-to-7_0_1_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review

#5811 Additional printed forms cleanup - headers/footers, middle name and suffix visibility
  interface/forms/LBF/printable.php
  interface/patient_file/printed_fee_sheet.php
  interface/patient_file/report/custom_report.php
  interface/patient_file/summary/demographics_print.php
  interface/patient_file/transaction/print_referral.php
  library/patient.inc
Labels: Status: Needs Review

#5777 Google Sign-On with new libraries
  templates/login/login_core.html.twig
Labels: Status: Needs Review

#5825 fixes #5824, reorganize and simplify patient portal widget
  interface/patient_file/summary/demographics.php
  library/options.inc.php
  portal/import_template_ui.php
  src/Patient/Cards/PortalCard.php
  templates/patient/partials/portal.html.twig
Labels: Status: Needs Review

#5868 Missing form validation Questionnaires
  interface/forms/questionnaire_assessments/questionnaire_assessments.php
Labels: Status: Needs Work

#5865 fix for email in portal create credentials widget and portal login
  interface/forms/fee_sheet/new.php
  interface/patient_file/summary/create_portallogin.php
  interface/patient_file/summary/demographics.php
  portal/get_patient_info.php
  portal/import_template.php
  portal/import_template_ui.php
  portal/index.php
  portal/lib/appsql.class.php
  src/Common/Logging/EventAuditLogger.php
  src/Patient/Cards/PortalCard.php
  templates/patient/partials/portal.html.twig
Labels: Status: Needs Review

#5808 commits for Rel 700 p2
  contrib/icd10/2022-Code Descriptions.zip
  contrib/icd10/2023 Code Descriptions in Tabular Order.zip
  contrib/icd10/Zip File 3 2022 ICD-10-PCS Codes File.zip
  contrib/icd10/Zip File 3 2023 ICD-10-PCS Codes File.zip
  interface/billing/edit_payment.php
  interface/billing/payment_pat_sel.inc.php
  interface/billing/search_payments.php
  interface/billing/sl_eob_invoice.php
  interface/forms/LBF/printable.php
  interface/forms/fee_sheet/new.php
  interface/forms/fee_sheet/review/fee_sheet_ajax.php
  interface/forms/fee_sheet/review/fee_sheet_review_view_model.js
  interface/forms/fee_sheet/review/initialize_review.php
  interface/forms/track_anything/create.php
  interface/forms/track_anything/history.php
  interface/forms/track_anything/new.php
  interface/forms/vitals/C_FormVitals.class.php
  interface/forms/vitals/growthchart/chart.php
  interface/forms/vitals/templates/vitals/vitals.html.twig
  interface/patient_file/printed_fee_sheet.php
  interface/patient_file/report/custom_report.php
  interface/patient_file/summary/create_portallogin.php
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/demographics_print.php
  interface/patient_file/summary/track_anything_fragment.php
  interface/patient_file/transaction/print_referral.php
  interface/usergroup/facility_admin.php
  library/classes/X12Partner.class.php
  library/clinical_rules.php
  library/options.inc.php
  library/patient.inc
  portal/get_patient_info.php
  portal/import_template.php
  portal/import_template_ui.php
  portal/index.php
  portal/lib/appsql.class.php
  sql/database.sql
  sql/patch.sql
  src/Billing/Hcfa1500.php
  src/Billing/X125010837P.php
  src/Common/Logging/EventAuditLogger.php
  src/Patient/Cards/PortalCard.php
  templates/patient/partials/portal.html.twig
Labels: patching
