Repository openemr/openemr, pull requests merged in 2022-01, with the labels that each got.

#4800 Hook into code types
  .gitignore
  contrib/venom/README
  custom/code_types.inc.php
  src/Events/Codes/ExternalCodesCreatedEvent.php
Labels: Status: Needs Review, Status: Needs Work

#4730 Adding support for Sphere payment processing
  interface/main/tabs/menu/menus/standard.json
  interface/patient_file/front_payment.php
  interface/reports/payment_processing_report.php
  interface/super/edit_globals.php
  library/globals.inc.php
  portal/lib/paylib.php
  portal/portal_payment.php
  sites/default/documents/custom_menus/Custom.json
  sphere/initial_response.php
  sphere/process_response.php
  sphere/process_revert_response.php
  sphere/token.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Common/Auth/AuthGlobal.php
  src/PaymentProcessing/PaymentProcessing.php
  src/PaymentProcessing/Sphere/Sphere.php
  src/PaymentProcessing/Sphere/SpherePayment.php
  src/PaymentProcessing/Sphere/SphereRevert.php
  src/Services/Globals/GlobalSetting.php
  version.php
Labels: Status: Needs Review

#4811 add a checkbox to show and hide password
  interface/usergroup/user_admin.php
Labels: Status: Needs Review

#4812 Use BS Alerts instead of gritter
  portal/index.php
Labels: Status: Needs Review

#4830 Fix misspelt variable name
  interface/eRxXMLBuilder.php
Labels: Status: Ready for Integration

#4813 Fixed Layout Based Form Validation Failure #4735
  interface/forms/LBF/new.php
Labels: Status: Needs Review

#4849 Calendar: Time Display Format 24 hr global fix for Find Available Appointment
  interface/main/calendar/add_edit_event.php
  interface/main/calendar/find_appt_popup.php
  interface/super/edit_globals.php
Labels: Status: Needs Review

#4845 Move Patient Education URLs into a List
  interface/reports/patient_edu_web_lookup.php
  interface/super/edit_list.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review
