Repository openemr/openemr, pull requests merged in 2022-04, with the labels that each got.

#5067 Multi site install rm keys for new site that wasn't cloned
  library/classes/Installer.class.php
Labels: Status: Needs Review

#5074 theme fixes for multi site clones
  library/classes/Installer.class.php
Labels: Best PR Title of the Year Finalist

#5100 Usps address verification
  composer.json
  composer.lock
  interface/patient_file/summary/demographics.php
  interface/patient_file/summary/demographics_full.php
  interface/practice/address_verify.php
  library/globals.inc.php
  src/Billing/EDI270.php
  src/USPS/USPSAddress.php
  src/USPS/USPSAddressVerify.php
  src/USPS/USPSBase.php
Labels: Status: Needs Review, Status: Needs Work

#4962 Create Transaction API
  _rest_routes.inc.php
  src/Common/Auth/OpenIDConnect/Repositories/ScopeRepository.php
  src/RestControllers/TransactionRestController.php
  src/Services/PatientTransactionService.php
  swagger/openemr-api.yaml
Labels: Status: Needs Review

#5139 Fixes #5127 mapped uuids not saving in registry
  src/Common/Uuid/UuidMapping.php
  src/Common/Uuid/UuidRegistry.php
Labels: 2015 ONC, rel-610

#5138 Fixes #5137 Vitals save data absent value
  interface/forms/vitals/templates/vitals/vitals_textbox.tpl
  interface/forms/vitals/templates/vitals/vitals_textbox_conversion.tpl
  src/Common/Forms/FormVitals.php
Labels: 2015 ONC, rel-610

#5129 Openemr fhir single patient api #5122
  src/Services/CarePlanService.php
  src/Services/FHIR/DocumentReference/FhirClinicalNotesService.php
  src/Services/FHIR/DocumentReference/FhirPatientDocumentReferenceService.php
  src/Services/FHIR/FhirCarePlanService.php
  src/Services/FHIR/FhirImmunizationService.php
  src/Services/FHIR/FhirMedicationRequestService.php
  src/Services/FHIR/FhirOrganizationService.php
  src/Services/FHIR/FhirProvenanceService.php
  src/Services/FHIR/Procedure/FhirProcedureOEProcedureService.php
  src/Services/SurgeryService.php
  tests/Tests/Services/CarePlanServiceTest.php
Labels: 2015 ONC, rel-610

#5132 eye form fixes with merged fix to code type selector and minor billing fixes from upstream
  interface/forms/eye_mag/php/eye_mag_functions.php
  interface/forms/eye_mag/view.php
  interface/patient_file/encounter/find_code_popup.php
  interface/patient_file/summary/add_edit_issue.php
  src/Billing/BillingProcessor/Tasks/AbstractGenerator.php
  src/Billing/BillingProcessor/Tasks/GeneratorHCFA.php
  src/Billing/BillingProcessor/Tasks/GeneratorHCFA_PDF.php
  src/Billing/BillingProcessor/Tasks/GeneratorX12.php
Labels: rel-610

#5136 fix stats and misc dashboard for omit employer section
  interface/patient_file/summary/demographics_save.php
  library/options.inc.php
Labels: rel-610

#5128 handle empty pubpid for documents linked via messages
  interface/main/messages/messages.php
Labels: rel-610

#5141 weno fixes
  interface/patient_file/summary/stats.php
  interface/patient_tracker/patient_tracker.php
  src/Rx/Weno/LogProperties.php
  src/Rx/Weno/TransmitProperties.php
  templates/patient/card/rx.html.twig
Labels: rel-610

#5156 void checkout or reopen global and logic to support
  interface/forms/fee_sheet/new.php
  interface/patient_file/rules/patient_data.php
  interface/reports/pat_ledger.php
  library/FeeSheet.class.php
  library/custom_template/custom_template.php
  library/globals.inc.php
  src/Billing/BillingUtilities.php
Labels: Status: Needs Review

#5263 Openemr fix #5255 forms reason code
  config/config.yaml
  interface/forms/observation/new.php
  interface/forms/observation/observation.js
  interface/forms/observation/save.php
  interface/forms/observation/templates/observation_actions.php
  interface/forms/observation/templates/observation_reason_row.php
  interface/forms/vitals/C_FormVitals.class.php
  interface/forms/vitals/templates/vitals/general_new.html
  interface/forms/vitals/templates/vitals/vitals_actions.tpl
  interface/forms/vitals/templates/vitals/vitals_notes.tpl
  interface/forms/vitals/templates/vitals/vitals_reason_row.tpl
  interface/forms/vitals/templates/vitals/vitals_temp_method.tpl
  interface/forms/vitals/templates/vitals/vitals_textbox.tpl
  interface/forms/vitals/templates/vitals/vitals_textbox_conversion.tpl
  interface/forms/vitals/vitals.css
  interface/forms/vitals/vitals.js
  library/dialog.js
  library/js/reasonCodeWidget.js
  library/smarty/plugins/function.assetVersionNumber.php
  sql/6_1_0-to-7_0_0_upgrade.sql
  sql/database.sql
  src/Common/Forms/FormVitalDetails.php
  src/Common/Forms/FormVitals.php
  src/Common/Forms/ReasonStatusCodes.php
  src/Core/Header.php
  src/Services/VitalsService.php
Labels: Status: Needs Review, Status: Needs Work
