Repository openemr/openemr, pull requests merged in 2022-03, with the labels that each got.

#4997 Openemr work on 4958 amc patient electronic access
  FHIR_README.md
  interface/main/tabs/templates/patient_data_template.php
  interface/patient_file/summary/create_portallogin.php
  interface/patient_file/summary/dashboard_header.php
  interface/patient_file/summary/demographics.php
  interface/reports/cqm.php
  interface/reports/report_results.php
  interface/smart/register-app.php
  library/ajax/execute_cdr_report.php
  library/classes/rulesets/Amc/reports/AMC_315g_2c.php
  library/classes/rulesets/Amc/reports/AMC_315g_2c/Denominator.php
  library/classes/rulesets/Amc/reports/AMC_315g_2c/Numerator.php
  library/classes/rulesets/ReportTypes.php
  library/clinical_rules.php
  portal/account/account.lib.php
  sql/6_1_0-to-7_0_0_upgrade.sql
  sql/database.sql
  src/ClinicialDecisionRules/AMC/CertificationReportTypes.php
  src/FHIR/Config/ServerConfig.php
  src/FHIR/SMART/SmartLaunchController.php
  src/RestControllers/AuthorizationController.php
  templates/emails/partials/patient/email-message-fhir-access.html.twig
  templates/emails/partials/patient/email-message-fhir-access.text.twig
  templates/emails/patient/portal_login/message.html.twig
  templates/emails/patient/portal_login/message.text.twig
  templates/emails/patient/reset_credentials/message.html.twig
  templates/emails/patient/reset_credentials/message.text.twig
  templates/emails/patient/verify_email/message-verify-failed.html.twig
  templates/emails/patient/verify_email/message-verify-failed.text.twig
  templates/emails/patient/verify_email/message-verify-success.html.twig
  templates/emails/patient/verify_email/message-verify-success.text.twig
  templates/patient/partials/portal.html.twig
  templates/patient/portal_login/print.html.twig
Labels: Status: Ready for Integration

#4994 QRDA I exports from CCM
  interface/modules/zend_modules/module/Application/src/Application/Controller/SendtoController.php
  interface/modules/zend_modules/module/Application/view/application/sendto/send.phtml
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CcdController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/ccd/upload.phtml
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/encountermanager/index.phtml
  interface/modules/zend_modules/public/js/application/sendTo.js
  library/globals.inc.php
  sql/6_1_0-to-7_0_0_upgrade.sql
  sql/database.sql
  src/Cqm/QrdaControllers/QrdaReportController.php
  src/Services/Qrda/QrdaReportService.php
  version.php
Labels: Backend Modernization Project, 2015 ONC

#5010 Update for 2022 CQM measures
  sql/6_1_0-to-7_0_0_upgrade.sql
  sql/database.sql
  version.php
Labels: 2015 ONC

#5013 QRDA import parsing fixes
  interface/forms/observation/new.php
  interface/forms/observation/save.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  library/globals.inc.php
  src/Services/Cda/CdaTemplateImportDispose.php
  src/Services/Cda/CdaTemplateParse.php
  src/Services/Qrda/Helpers/Date.php
  src/Services/Qrda/QrdaReportService.php
Labels: 2015 ONC

#5015 fix bug for sending documents and bug in ins search
  controllers/C_Document.class.php
  interface/billing/get_claim_file.php
  interface/practice/ins_search.php
  src/Services/AddressService.php
  src/Services/InsuranceCompanyService.php
  templates/documents/general_view.html
Labels: Status: Needs Review

#5022 Fixed missing field in NM1*41 field.
  sql/example_patient_data.sql
  src/Billing/Claim.php
  src/Billing/X125010837P.php
Labels: Status: Needs Work

#5020 Openemr fix 5003 group calculation
  interface/reports/cqm.php
  library/classes/rulesets/Amc/library/AbstractAmcReport.php
  library/classes/rulesets/ReportManager.php
  library/classes/rulesets/library/RsPopulation.php
  library/clinical_rules.php
  library/report_database.inc
  src/Reports/AMC/Trackers/AMCItemSkipTracker.php
  src/Reports/AMC/Trackers/AMCItemTracker.php
  templates/reports/cqm/_results-table-body.html.twig
  templates/reports/cqm/_results-table-main-sub.html.twig
  templates/reports/cqm/_results-table-plans.html.twig
  templates/reports/cqm/_results-table-provider-group.html.twig
  templates/reports/cqm/_results-table-provider.html.twig
  templates/reports/cqm/amc-results-table.html.twig
  templates/reports/cqm/cqm-results-table.html.twig
  templates/reports/cqm/results-table.html.twig
Labels: Status: Needs Review

#5049 Fixes #5048 - Add Encounter to Transaction Form
  library/layout.inc.php
  library/options.inc.php
  sql/6_1_0-to-7_0_0_upgrade.sql
  sql/database.sql
Labels: Status: Needs Review, Status: Needs Work
