Repository openemr/openemr, pull requests merged in 2022-02, with the labels that each got.

#4860 add referring provider to db en route to encounter form
  interface/forms/misc_billing_options/date_qualifier_options.php
  interface/forms/misc_billing_options/new.php
  interface/forms/misc_billing_options/report.php
  interface/forms/newpatient/common.php
  interface/forms/newpatient/report.php
  interface/forms/newpatient/save.php
  interface/patient_file/deleter.php
  sql/6_0_0-to-6_1_0_upgrade.sql
  sql/database.sql
  src/Billing/Claim.php
  src/Billing/MiscBillingOptions.php
  src/Services/AppointmentService.php
  src/Services/EncounterService.php
  src/Services/PatientService.php
  version.php
Labels: Status: Needs Review

#4914 Fixes #4912 direct message patient update fails
  interface/main/finder/multi_patients_finder.php
  interface/main/messages/messages.php
  library/pnotes.inc
Labels: Status: Needs Work

#4823 use buttons instead of links in pt data template, use better verbiage…
  interface/main/tabs/templates/patient_data_template.php
  interface/patient_file/history/encounters.php
Labels: up for grabs demo

#4952 Promote Patient Finder to top-level menu
  interface/main/tabs/menu/menus/standard.json
  interface/main/tabs/templates/user_data_template.php
  interface/themes/oe-styles/style_light.scss
  sites/default/documents/custom_menus/Custom.json
  tests/Tests/E2e/Pages/MainPage.php
Labels: Status: Needs Work
