Repository openemr/openemr, pull requests merged in 2022-12, with the labels that each got.

#5801 ci: add minimum GitHub token permissions for workflows
  .github/workflows/manual-build-php-fpm-dockers.yml
  .github/workflows/styling.yml
  .github/workflows/syntax.yml
  .github/workflows/test.yml
Labels: Status: Needs Review, Status: Needs Work

#5735 Itemized Invoice
  interface/patient_file/front_payment.php
  interface/patient_file/pos_checkout_normal.php
Labels: Status: Needs Review

#5740 drop support for php 7.4
  .github/workflows/syntax.yml
  .github/workflows/test.yml
  CONTRIBUTING.md
  bin/console
  ci/apache_74_106/docker-compose.yml
  ci/nginx_74/docker-compose.yml
  ci/nginx_74/php.ini
  composer.json
  composer.lock
  contrib/util/ccda_import/import_ccda.php
  interface/modules/zend_modules/config/application.config.php
  interface/modules/zend_modules/module/Acl/src/Acl/Controller/AclController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Installer/Module.php
  interface/modules/zend_modules/module/Installer/config/module.config.php
  interface/modules/zend_modules/module/Installer/src/Installer/Controller/InstallerController.php
  interface/modules/zend_modules/public/index.php
  src/Common/Command/AclModify.php
  src/Common/Command/CcdaImport.php
  src/Common/Command/CcdaNewpatient.php
  src/Common/Command/CcdaNewpatientImport.php
  src/Common/Command/Register.php
  src/Common/Command/ZfcModule.php
  src/Common/Compatibility/Checker.php
  src/Core/ModulesApplication.php
  src/Services/Cda/CdaTemplateImportDispose.php
Labels: Status: Needs Review, PHP

#6041 Fix Overflowing UI
  interface/patient_file/pos_checkout_normal.php
Labels: UI/UX

#6060 Better Page Heading UI
  src/OeUI/OemrUI.php
Labels: can't fix it all in 1 PR
