Repository openemr/openemr, pull requests merged in 2022-11, with the labels that each got.

#5870 CCDA download problems and unstructured documents
  ccdaservice/oe-blue-button-generate/index.js
  ccdaservice/oe-blue-button-generate/lib/documentLevel.js
  ccdaservice/serveccda.js
  interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
  interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php
  interface/modules/zend_modules/module/Application/view/application/sendto/send.phtml
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaGenerator.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceRequestModelGenerator.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/encountermanager/index.phtml
  interface/modules/zend_modules/module/Documents/view/documents/documents/retrieve.phtml
  library/globals.inc.php
  sql/7_0_0-to-7_0_1_upgrade.sql
  sql/database.sql
  src/Services/Cda/CdaTemplateImportDispose.php
  src/Services/Cda/CdaTemplateParse.php
  src/Services/Cda/CdaValidateDocuments.php
  src/Services/Cda/XmlExtended.php
  version.php
Labels: Status: Needs Work

#5892 Patch 2 Add a disable validation to config ccda in connectors
  ccdaservice/oe-blue-button-generate/index.js
  ccdaservice/oe-blue-button-generate/lib/documentLevel.js
  ccdaservice/serveccda.js
  interface/modules/zend_modules/module/Application/src/Application/Model/ApplicationTable.php
  interface/modules/zend_modules/module/Application/src/Application/Plugin/CommonPlugin.php
  interface/modules/zend_modules/module/Application/view/application/sendto/send.phtml
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncountermanagerController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaGenerator.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CcdaServiceRequestModelGenerator.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncounterccdadispatchTable.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/EncountermanagerTable.php
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/carecoordination/upload.phtml
  interface/modules/zend_modules/module/Carecoordination/view/carecoordination/encountermanager/index.phtml
  library/globals.inc.php
  sql/database.sql
  sql/patch.sql
  src/Services/Cda/CdaTemplateImportDispose.php
  src/Services/Cda/CdaTemplateParse.php
  src/Services/Cda/CdaValidateDocuments.php
  src/Services/Cda/XmlExtended.php
  version.php
Labels: Status: Needs Work

#5810 Phq9form final version
  interface/forms/phq9/common.php
  interface/forms/phq9/info.txt
  interface/forms/phq9/new.php
  interface/forms/phq9/phq9.inc.php
  interface/forms/phq9/phq9_javasrc.js
  interface/forms/phq9/report.php
  interface/forms/phq9/save.php
  interface/forms/phq9/table.sql
  interface/forms/phq9/view.php
Labels: Status: Needs Review, Status: Needs Work

#5927 Fix encounter history hover tooltips
  interface/patient_file/history/encounters.php
Labels: Status: Needs Review

#5792 Medex9.28.22
  interface/main/messages/save.php
  library/MedEx/API.php
Labels: Status: Needs Review
