Repository openemr/openemr, pull requests merged in 2022-05, with the labels that each got.

#5142 MRD Card Events
  interface/patient_file/summary/demographics.php
  src/Events/Patient/Summary/Card/CardInterface.php
  src/Events/Patient/Summary/Card/CardModel.php
  src/Events/Patient/Summary/Card/SectionEvent.php
  src/Patient/Cards/PortalCard.php
  templates/patient/card/card_base.html.twig
Labels: Status: Needs Review

#5264 Some export fixes for the backup script.
  interface/main/backup.php
Labels: Bug

#5273 PHPStorm suggested changing this the properties to protected
  library/ESign/DbRow/Signable.php
Labels: Status: Needs Review, Status: Needs Issue

#5269 CCDA Udpates
  ccdaservice/serveccda.js
  interface/modules/zend_modules/module/Application/view/application/sendto/send.phtml
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/EncounterccdadispatchController.php
  src/Services/Cda/CdaTemplateImportDispose.php
  src/Services/DocumentTemplates/DocumentTemplateService.php
Labels: 2015 ONC

#5319 Validation service
  ccdaservice/README.md
  ccdaservice/oe-blue-button-generate/lib/translate.js
  ccdaservice/package-lock.json
  ccdaservice/package.json
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/public/schematrons/ccda/Consolidation.sch
  interface/modules/zend_modules/public/schematrons/qrda1/2022_CMS_QRDA_I.sch
  interface/modules/zend_modules/public/schematrons/qrda1/voc.xml
  interface/modules/zend_modules/public/schematrons/qrda3/2022_CMS_QRDA_Category_III.sch
  interface/modules/zend_modules/public/schematrons/qrda3/voc.xml
  package-lock.json
  package.json
  sql/6_1_0-to-7_0_0_upgrade.sql
  sql/database.sql
  src/Cqm/CqmServiceManager.php
  src/Services/Cda/CdaTemplateParse.php
  src/Services/Cda/CdaValidateDocuments.php
  src/Services/Cda/Schematron.php
  src/Services/Cda/SchematronException.php
  src/Services/Cda/SchematronHelpers.php
  src/Services/Cda/SchematronXPath.php
  src/Services/Qdm/MeasureService.php
  version.php
Labels: Status: Needs Review, 2015 ONC

#5329 Validations view Development
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Controller/CarecoordinationController.php
  interface/modules/zend_modules/module/Carecoordination/src/Carecoordination/Model/CarecoordinationTable.php
  interface/modules/zend_modules/module/Documents/src/Documents/Controller/DocumentsController.php
  src/Cqm/QrdaControllers/QrdaReportController.php
  src/Services/Cda/CdaTemplateImportDispose.php
  src/Services/Cda/CdaValidateDocuments.php
  src/Services/InsuranceCompanyService.php
  src/Services/Qdm/Services/EncounterService.php
  src/Services/Qrda/QrdaReportService.php
Labels: Status: Needs Review
