Repository openemr/openemr, pull requests merged in 2022-09, with the labels that each got.

#5715 Add By Mouth to prescription list options (Fixes #5714)
  sql/7_0_0-to-7_0_1_upgrade.sql
  sql/database.sql
Labels: Status: Needs Work

#5668 Openemr fix 5665 vitals being squashed
  interface/forms/vitals/C_FormVitals.class.php
  interface/forms/vitals/templates/vitals/general_new.html
  interface/forms/vitals/templates/vitals/vitals.html.twig
  interface/forms/vitals/templates/vitals/vitals_actions.html.twig
  interface/forms/vitals/templates/vitals/vitals_actions.tpl
  interface/forms/vitals/templates/vitals/vitals_bmi.html.twig
  interface/forms/vitals/templates/vitals/vitals_bmi_status.html.twig
  interface/forms/vitals/templates/vitals/vitals_growthchart_actions.html.twig
  interface/forms/vitals/templates/vitals/vitals_historical_values.html.twig
  interface/forms/vitals/templates/vitals/vitals_historical_values.tpl
  interface/forms/vitals/templates/vitals/vitals_historical_values_complete.html.twig
  interface/forms/vitals/templates/vitals/vitals_interpretation_selector.html.twig
  interface/forms/vitals/templates/vitals/vitals_interpretation_selector.tpl
  interface/forms/vitals/templates/vitals/vitals_notes.html.twig
  interface/forms/vitals/templates/vitals/vitals_notes.tpl
  interface/forms/vitals/templates/vitals/vitals_reason_row.html.twig
  interface/forms/vitals/templates/vitals/vitals_reason_row.tpl
  interface/forms/vitals/templates/vitals/vitals_temp_method.html.twig
  interface/forms/vitals/templates/vitals/vitals_temp_method.tpl
  interface/forms/vitals/templates/vitals/vitals_textbox.html.twig
  interface/forms/vitals/templates/vitals/vitals_textbox.tpl
  interface/forms/vitals/templates/vitals/vitals_textbox_conversion.html.twig
  interface/forms/vitals/templates/vitals/vitals_textbox_conversion.tpl
  interface/forms/vitals/vitals.css
  library/globals.inc.php
  src/Common/Twig/TwigExtension.php
Labels: Status: Needs Review

#5722 Fix Drugs dispensing in Charges Panel
  interface/drugs/dispense_drug.php
Labels: Status: Needs Review

#5691 consolidate similar x12 gen 837 function
  src/Billing/BillingProcessor/Tasks/GeneratorX12Direct.php
  src/Billing/X125010837P.php
Labels: Status: Needs Review

#5741 fixes for php 7.4 in rel-700
  interface/forms/vitals/C_FormVitals.class.php
  interface/modules/zend_modules/public/index.php
  interface/orders/receive_hl7_results.inc.php
  interface/patient_file/summary/demographics_save.php
  interface/super/edit_layout.php
  library/classes/Controller.class.php
  library/options.inc.php
  src/Common/Http/HttpRestRequest.php
  src/PatientPortal/Chat/ChatController.php
  src/Rx/RxList.php
  src/Services/Cda/CdaValidateDocuments.php
  src/Services/Qdm/Services/ImmunizationAdministeredService.php
Labels: Status: Needs Work, PHP

#5757 Questionnaire encounter report
  interface/forms/questionnaire_assessments/questionnaire_assessments.php
  interface/forms/questionnaire_assessments/report.php
  interface/forms/questionnaire_assessments/save.php
  src/Services/QuestionnaireResponseService.php
  src/Services/QuestionnaireService.php
  src/Services/QuestionnaireTraits.php
Labels: Status: Needs Review, Status: Needs Work

#5762 bring in 2023 icd10
  contrib/icd10/2022-Code Descriptions.zip
  contrib/icd10/2023 Code Descriptions in Tabular Order.zip
  contrib/icd10/Zip File 3 2022 ICD-10-PCS Codes File.zip
  contrib/icd10/Zip File 3 2023 ICD-10-PCS Codes File.zip
  sql/7_0_0-to-7_0_1_upgrade.sql
  sql/database.sql
  version.php
Labels: code set update

#5769 Fixes Left and Right Login Layout Color Not Fully Showing
  interface/login/login.php
Labels: Status: Needs Review

#5784 Fix for graphing of LBF data entered retroactively.
  library/ajax/graphs.php
Labels: Bug
