Repository openemr/openemr, pull requests merged in 2023-01, with the labels that each got.

#5787 Immuinzations export spreadsheet
  interface/billing/billing_tracker.php
  interface/reports/immunization_report.php
  library/ajax/immunization_export.php
  src/Services/SpreadSheetService.php
Labels: Status: Needs Review, Status: Needs Work

#6090 Hook for page action buttons
  interface/main/finder/dynamic_finder.php
  interface/patient_file/summary/demographics.php
  src/Events/UserInterface/ActionButtonInterface.php
  src/Events/UserInterface/BaseActionButtonHelper.php
  src/Events/UserInterface/PageHeadingRenderEvent.php
  src/OeUI/OemrUI.php
  templates/oemr_ui/page_heading/partials/page_heading.html.twig
Labels: Status: Needs Review, Status: Needs Work, UI Modernization, UI/UX

#6079 bug fix
  library/pnotes.inc.php
  portal/add_edit_event_user.php
  portal/find_appt_popup_user.php
  portal/messaging/secure_chat.php
  src/PatientPortal/Chat/ChatController.php
Labels: Status: Needs Review, Status: Needs Work

#6084 Adding Datatables to insurance page
  templates/insurance_companies/general_list.html
Labels: Status: Needs Review, Status: Needs Issue

#6135 Improved login page layout and control
  composer.json
  composer.lock
  interface/login/login.php
  library/globals.inc.php
  public/images/logos/core/login/primary/logo.png
  public/images/logos/core/login/secondary/logo.png
  public/images/logos/core/login/small_logo_1/logo.png
  public/images/logos/core/login/small_logo_2/logo.png
  sites/default/images/logos/core/login/primary/README
  sites/default/images/logos/core/login/secondary/README
  sites/default/images/logos/core/login/small_logo_1/README
  sites/default/images/logos/core/login/small_logo_2/README
  sql/7_0_0-to-7_0_1_upgrade.sql
  src/Events/Core/TemplatePageEvent.php
  src/Services/LogoService.php
  templates/login/base.html.twig
  templates/login/horizontal_band.html.twig
  templates/login/horizontal_box.html.twig
  templates/login/layouts/horizontal_band_left_logo.html.twig
  templates/login/layouts/horizontal_band_right_logo.html.twig
  templates/login/layouts/horizontal_box_left_logo.html.twig
  templates/login/layouts/horizontal_box_right_logo.html.twig
  templates/login/layouts/vertical_band.html.twig
  templates/login/layouts/vertical_box.html.twig
  templates/login/login_core.html.twig
  templates/login/partials/html/acknowledgements.html.twig
  templates/login/partials/html/google_signin.html.twig
  templates/login/partials/html/login_details.html.twig
  templates/login/partials/html/login_failure.html.twig
  templates/login/partials/html/logos.html.twig
  templates/login/partials/html/primary_logo.html.twig
  templates/login/partials/html/product_registration_modal.html.twig
  templates/login/partials/html/relogin.html.twig
  templates/login/partials/html/small_logo.html.twig
  templates/login/partials/html/tagline.html.twig
  templates/login/partials/input/buttons.html.twig
  templates/login/partials/input/facilities.html.twig
  templates/login/partials/input/languages.html.twig
  templates/login/partials/input/password.html.twig
  templates/login/partials/input/username.html.twig
  templates/login/partials/js/google_signin.js.twig
  templates/login/partials/js/product_reg.js.twig
Labels: UI/UX, Feature Enhancement
