Repository openemr/openemr, pull requests merged in 2025-05, with the labels that each got.

#8335 fix: registration modal fix to ensure complete decoupling
  _rest_routes.inc.php
  apis/dispatch.php
  interface/main/about_page.php
  interface/main/tabs/js/tabs_view_model.js
  interface/main/tabs/main.php
  interface/product_registration/product_registration_controller.js
  interface/product_registration/product_registration_controller.php
  library/ajax/track_events.php
  library/telemetry_reporting_service.php
  portal/lib/track_portal_events.php
  src/Services/ProductRegistrationService.php
  src/Telemetry/TelemetryService.php
  version.php
Labels: Status: Needs Release Merge

#8316 Fixing UI For Demographics Form On Big Screens
  interface/patient_file/summary/demographics_full.php
Labels: Status: Needs Release Merge

#8263 Adding validation and disabling duration for in office events
  interface/main/calendar/add_edit_event.php
  library/validation/validation_script.js.php
Labels: Status: Needs Release Merge

#8336 Switch REPLACE INTO with INSERT … ON DUPLICATE KEY UPDATE
  src/Common/ORDataObject/ORDataObject.php
Labels: Priority: Blocking

#8342 Syntax error in stats_full script
  interface/patient_file/summary/stats_full.php
Labels: Status: Needs Release Merge

#8371 fix: do not send usage report if telemetry is turned off
  src/Telemetry/TelemetryService.php
Labels: Status: Needs Release Merge

#8330 chore: Advance Prior Auth - Code enhancements to meet PHP coding standards.
  interface/modules/custom_modules/oe-module-prior-authorizations/public/deleter.php
  interface/modules/custom_modules/oe-module-prior-authorizations/public/index.php
  interface/modules/custom_modules/oe-module-prior-authorizations/public/reports/list_report.php
  interface/modules/custom_modules/oe-module-prior-authorizations/src/Controller/AuthorizationService.php
  interface/modules/custom_modules/oe-module-prior-authorizations/src/Controller/ListAuthorizations.php
Labels: Status: Needs Release Merge

#8384 chore: remove summernote-plugins
  package.json
Labels: Status: Needs Release Merge

#8382 chore: cleanup obsolete icd9 installer code
  library/classes/Installer.class.php
  sql/icd9-codes-insert.sql
  sql/icd9-codes-replace.sql
Labels: Status: Needs Release Merge

#8381 refactor: decouple SQLUpgradeService and SQLUpgradeEvent
  src/Events/Core/SQLUpgradeEvent.php
  src/Services/Utils/Interfaces/ISQLUpgradeService.php
  src/Services/Utils/SQLUpgradeService.php
Labels: Status: Needs Release Merge

#8393 Vitals Graph Fix
  interface/patient_file/encounter/trend_form.php
Labels: Status: Needs Issue
